### ISSUE TITLE
Question: Layout for Buttons 

### ISSUE THREAD

**Issue by Kam21** [SnapKit/SnapKit#102]
Hi All,
I need some help to solve my layout issue.
I am trying to make a UIScrollView by adding buttons similar to below image.
http://designmodo.com/wp-content/uploads/2013/06/Arles-Festival-iPhone-App-V2.0.jpg

I am having trouble setting all Constraints for each button to fit all ios screen size.
Here is my sample code for each button 

scrollView = UIScrollView()
scrollView .addSubview(btn1)
btn1.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(scrollView.snp_top).offset(10)
            make.left.equalTo(scrollView.snp_left).offset(0)
           make.width.equalTo(100)
            make.height.equalTo(100)
        }

scrollView .addSubview(btn2)
btn2.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(scrollView.snp_top).offset(10)
            make.left.equalTo(btn1.snp_left).offset(1)
           make.width.equalTo(100)
            make.height.equalTo(100)
        }

scrollView .addSubview(btn3)
btn3.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(scrollView.snp_top).offset(10)
            make.left.equalTo(btn2.snp_left).offset(1)
           make.width.equalTo(100)
            make.height.equalTo(100)
        }

I am noticing buttons are different size for each screen size and not able to fit all button to a scrollview for different screen size

Can someone help solve the layout issue or provide some guidance to make by scroll view with buttons to fit all screen size?

thank you in advance

**Comment by robertjpayne** [comment]
@Kam21 any reason you're using a scroll view if you're trying to "fit them" to the screen size?

Also you're probably going to be better off using some multipliers rather than constant sizes.

**Comment by Kam21** [comment]
The reason behind using scrollview is I am planning to have around 20 UIButton. 
How  can I use multipliers if I want to have  4 rows and 5 columns inside scrollview?  
Sorry I am new to iOS & Swift.

I am trying to design the following view with top banner and buttons with scrollview.
![myview](https://cloud.githubusercontent.com/assets/8528848/7897675/1c94b752-06b2-11e5-85a0-39495dc378a4.png)


I hope you can help me to solve my layout issue.

**Comment by robertjpayne** [comment]
@Kam21 I'm still not sure that you need to put it in a scroll view? Is there going to be more content that can fit on the screen that the user needs to scroll through?

**Comment by Kam21** [comment]
I will be using an icon for the background for each button and  title. 
Attached exactly is a sample app screen shot.
I couldn't fit my content without scrollview.  I had everything set-up with storyboard but now I am using your library and coding everything without a storyboard. 
![app](https://cloud.githubusercontent.com/assets/8528848/7900047/2d9513fa-070f-11e5-8562-3358c8ac1979.png)

**Comment by jsslai** [comment]
If you have a grid layout I would use UICollectionView instead of adding subviews in scroll view. See https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UICollectionView.html#//apple_ref/doc/uid/TP40012857-UICollectionView

**Comment by robertjpayne** [comment]
Yea I agree with @jsslai it's much better to use a UICollectionView.

In both cases for grids it's a lot better to override layoutSubviews and manually layout the grid items instead of using constraints mostly because it's a lot less convulated.

If you think Of:

```
[00][01][02]
[03][04][05]
[06][07][08]
[09][10][11]
```

The first row would be like:

```swift
[00].snp_makeConstraints { (make) -> Void in
    make.top.left.equalTo(scrollView)
    make.width.equalTo(scrollView.superview!).multipliedBy(0.3333)
}
[01].snp_makeConstraints { (make) -> Void in
    make.top.equalTo(scrollView)
    make.width.equalTo(scrollView.superview!).multipliedBy(0.3333)
    make.left.equalTo([00].snp_right)
}
[02].snp_makeConstraints { (make) -> Void in
    make.top.equalTo(scrollView)
    make.right.equalTo(scrollView.superview!)
    make.left.equalTo([01].snp_right)
}
```

Then the second row would be similar but the top would be equal to the bottoms of the other.

Basically it's a big mess, it's a lot easier to calculate a grid size based on screen size, and then layout the views left to right top to bottom. Or calculate the grid size and use a collection view with flow layout!

**Comment by Kam21** [comment]
Awesome.  I will try it out.

Thanks for your help.

Regards
Kam
