### ISSUE TITLE
Prefix View/ViewController typealiases

### ISSUE THREAD

**Issue by Reflejo** [SnapKit/SnapKit#103]
@robertjpayne Just updated `SnapKit` on our project and now our `ViewController` is conflicting with the public alias.

This is the offending code:

```swift
public typealias ViewController = UIViewController
```

I couldn't find where you are using it though. Would you consider removing it?

**Comment by robertjpayne** [comment]
@Reflejo are you adding SnapKit via source inclusion or a framework?

**Comment by Reflejo** [comment]
@robertjpayne It's a framework

**Comment by robertjpayne** [comment]
Dang, I thought Swift's module name-spacing would protect that...

I did it because OS X has view controllers now and incase we ever expand the API there... I can remove it though.

**Comment by robertjpayne** [comment]
@Reflejo this is resolved in the develop branch -- probably wont release it until after WWDC's Keynote.

**Comment by Reflejo** [comment]
@robertjpayne Awesome, thanks. What's happening @ WWDC keynote? :shipit:

**Comment by robertjpayne** [comment]
@Reflejo probably some breaking Swift changes so I'll need to do a release anyways!

**Comment by freerunnering** [comment]
"I thought Swift's module name-spacing would protect that..."
Then you want `internal` not `public`. [Apple Docs: Swift Access Control] (https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html)

**Comment by robertjpayne** [comment]
@freerunnering I create an extension of the typealias so it has to have the same access modifier as the typealias.

I may prefix both of these typealiases given they will cause conflicts potentially.
