### ISSUE TITLE
Design Pattern behind SnapKit

### ISSUE THREAD

**Issue by steffimueller** [SnapKit/SnapKit#105]
SnapKit is great. Thanks for sharing. 

What is the design pattern behind SnapKit. Is it something like the decorator pattern?

**Comment by robertjpayne** [comment]
@steffimueller not sure I have a good answer for you, it's definitely not a decorator pattern though.

**Comment by steffimueller** [comment]
Which pattern s it?

**Comment by robertjpayne** [comment]
@steffimueller sorry I really don't have an answer for you. It's not like I looked at a design pattern for SnapKit and decided to roll with it.

The best way I explain it is a chaining DSL.

http://en.wikipedia.org/wiki/Domain-specific_language
