### ISSUE TITLE
Question: Easy way of percentages

### ISSUE THREAD

**Issue by ctews** [SnapKit/SnapKit#106]
Hey guys,

maybe it is just a stupid question, but how do I use effectively percentage values with SnapKit? 

For height for example I use: `make.height.equalTo(myView.superview!).multipliedBy(0.5)` for 50% of the height of myView regarding to its superview.

For the top position for example I use: `make.top.equalTo(myView.superview!.bounds.height * 0.5)` to have the top border of myView at 50% of the height of its superview.

This seems kind of stupid to me and I guess I'm just using it wrong. I always did UI programmatically and so I'm used to calculate CGRects by dividing and multiplying points and sizes with different values. But if I have for example 3 labels that have a different yPos but share the same same superview I just wonder how to use Snapkit for this kind of view hierarchy in a smart way.

Sorry for using an issue for that, but there were no explanations or examples especially regarding percentages. Thx in advance!

**Comment by robertjpayne** [comment]
@ctews You can only use multipliers for widths/heights, this is a limitation by Auto Layout not SnapKit.

There's a few ways to manage what you're after:

* You can pin the center of the middle label to the center of the superview. Then pin the top/bottom labels to the center labels

* You could make each label 33.333% of the height of the superview (UILabel centers it's content by default anyways )

Hope this helps.

Cheers

**Comment by ctews** [comment]
Thx @robertjpayne for the answer! This helps :)
