### ISSUE TITLE
Update to Swift 2.0

### ISSUE THREAD

**Issue by krishaamer** [SnapKit/SnapKit#109]
Hi, I'm getting errors in Xcode 7. Do you have plans to update to Swift 2.0?

Thanks,
Kris

**Comment by robertjpayne** [comment]
@krishaamer yup, there is a PR For Swift 2.0 but I don't have time to review it and get a branch setup until early next week!

**Comment by robertjpayne** [comment]
This is currently tracking in the `swift-2.0` branch.

**Comment by hezt95** [comment]
Hi, Robert.
The swift-2.0 branch is stable now?

**Comment by robertjpayne** [comment]
@hezt95 I've been deep under with another project so to be honest I've not had much time to keep it up to date -- but as far as I know it's stable. I am freed up next week to do some work and make sure everything is good to go since Swift 2.0 is stabilising a bit!

**Comment by hezt95** [comment]
@robertjpayne Thanks!

**Comment by orkenstein** [comment]
I buy you a beer when you finish this.

**Comment by robertjpayne** [comment]
@orkenstein the `swift-2.0` branch is up to date as of two days ago. It wont be merged until Xcode 7 goes GM.

**Comment by robertjpayne** [comment]
Just an update to everyone, once Xcode 7 goes GM I'm planning on pushing the Swift branch live. At that point I'll start to work on feature upgrades for iOS 9 features too!

**Comment by orkenstein** [comment]
Cool. I'm using `swift-2.0` for 3 weeks. Works like a charm!!

**Comment by davidrothera** [comment]
Can we pull this in now that Xcode7 is GM? :+1:

**Comment by robertjpayne** [comment]
Yup will do it tonight, sorry want to make sure it's all good to go and need time to ensure the spec is updated and sorts! :+1:

**Comment by HamGuy** [comment]
It seems like the `Swift-2.0` branch dose not support iOS 7

**Comment by robertjpayne** [comment]
@HamGuy what installation method are you using? We've never supported iOS 7.0 outside of directly dragging the source files into your iOS 7.0 app.

**Comment by HamGuy** [comment]
Sorry, my bad.  I had confused

**Comment by HamGuy** [comment]
@krishaamer Sorry, my bad.
I had confused it with some iOS 8 new features in `Constriant.swift`and `ConstraintAttributes.swift` file. : )

**Comment by lexrus** [comment]
Please release a new pod version for Swift 2. Thanks.

**Comment by robertjpayne** [comment]
This has been released on Cocoapods. Unfortunately for now it requires iOS 8.0+ or OS X 10.10+ because it doesn't include proper guard statements for unavailable APIs.
