### ISSUE TITLE
Bug in inset/offset documentation

### ISSUE THREAD

**Issue by TadeasKriz** [SnapKit/SnapKit#110]
I am not sure if I'm doing something wrong, but when I try this from the documentation:

```
let box = UIView()
superview.addSubview(box)

box.snp_makeConstraints { (make) -> Void in
    make.top.equalTo(superview).offset(20)
    make.left.equalTo(superview).offset(20)
    make.bottom.equalTo(superview).offset(20)
    make.right.equalTo(superview).offset(20)
}
```

it does not equal to
```
let box = UIView()
superview.addSubview(box)

box.snp_makeConstraints { (make) -> Void in
    make.edges.equalTo(superview).inset(UIEdgeInsetsMake(20, 20, 20, 20))
}
```

which is referred in the documentation to be the shorter version of the former. The latter one makes the view inset in the superview by 20 pixels from each side. But the former one basically just moves it 20 pixels right and down. Is this intended? I find it very annoying that I need to declare negative offset each time I don't want to have one of the constraints defined.

```
box.snp_makeConstraints { make in
   make.leading.top.equalTo(superview).offset(20)
   make.trailing.equalTo(superview).offset(-20)
}
```

Or am I doing something wrong here? Thanks.

**Comment by robertjpayne** [comment]
@TadeasKriz I think I probably have an error in the documentation then, it's copied from Masonry but the implementation of SnapKit vs Masonry is very different.

With SnapKit I chose to keep the `offset` consistent for any attributes on either the from or to item. That is `offset` will always be `attributeValue + offset`. It's far easier to implement and behaves more like `NSLayoutConstraint` anyways.

I know it's a bit annoying when it comes to edges which is why insets is there. Perhaps what may be more beneficial is to provide a `insets()` overload that would take a single value rather than `UIEdgeInsets` and allow a bit less ambiguous syntax you would like.

Apologies for the documentation confusion. Hope this makes sense too!

**Comment by TadeasKriz** [comment]
Thanks for the quick reply! Adding an extra method `inset()` that would take a single value would be great, but it depends on the behavior. 

If it would work the way that when I write `make.left.top.right.equalTo(superview).inset(20)` it would mean `left + 20, top + 20 and right - 20`, it would be so much easier to write. But then I'm not that sure about how understandable it is.

On the other hand, if I would have to write:
```
make.left.top.equalTo(superview).offset(20)
make.right.equalTo(superview).inset(20)
```
it would probably be more understandable, but then I'm not sure if we really need the method as we can just use `-20` with the offset method (or skip the method and use `equalTo` directly).

What do you think?

**Comment by robertjpayne** [comment]
@TadeasKriz Yea my personal take on it is to always just use negative offsets. I tried to reduce a bit of the Masonry magic in cases like this just for consistencies sake.

You can always use insets right now with a single attribute in SnapKit:

```swift
make.top.left.right.equalTo(otherView).insets(UIEdgeInsetsMake(20,20,20,20))
```

I think it'd just be nice to provide a shorthand insets method. Reality is internally I detect UIEdgeInsets to alter how the constant is calculated ( insets are `* -1` for right/bottom while offsets are not )

**Comment by TadeasKriz** [comment]
@robertjpayne For me the `UIEdgeInsetsMake(20,20,20,20)` is very confusing when I read it, because it tricks me to think it is inset on all sides (even if one of the params was `0`, it would give me the same impression). So probably the single value convenience method would make sense.

**Comment by robertjpayne** [comment]
@TadeasKriz this is in develop now you can now do something like `make.top.left.equalTo(otherView).inset(5)`
