### ISSUE TITLE
Can I constraint ButtonA's bottom to ButtonB's top?

### ISSUE THREAD

**Issue by pangyulei** [SnapKit/SnapKit#117]
If I have ButtonA above ButtonB
I want the span between them is 20.
Can I do this by constraint ButtonA's bottom to ButtonB's top? How? I did not found the example at Docs.

**Comment by robertjpayne** [comment]
@pangyulei we know the doc's don't cover every single case, generally trying to get a bit of the architecture of how to use SnapKit:

```swift
buttonA.snp_makeConstraints { (make) -> Void in
    make.bottom.equalTo(buttonB.snp_top).offset(-20)
}
```

**Comment by pangyulei** [comment]
thx
