### ISSUE TITLE
SnapKit and a UITableViewController with custom UITableViewCells

### ISSUE THREAD

**Issue by orion538** [SnapKit/SnapKit#120]
Hello,

I'm currently using SnapKit to style my UITableViewCells in a UITableViewController. This is however being done too often and slows my UI when scrolling. Would you, as the creators of SnapKit, have a recommended way of going about such a scenario? I could explain you my current solution, but I'd rather have a fresh take on this. What I can say is that I set the constraints in the cellForRowAtIndexPath method. Not the layoutSubviews method of my UITableViewCell or in the updateConstraints method of the tableView. I have the problem of having to update the same UITableViewCell with different constraints if the content changed or the same cell is being reused..

Thanks in advance

**Comment by robertjpayne** [comment]
@orion538 are you using Auto Layout to "auto size" your cells? This is new in iOS 8 and while it's really nice it has significant performance hit for complex cells.

Mind sharing a bit of your cell code? How complex is the cell etc…?

**Comment by orion538** [comment]
I do make use of the Auto Layout features.

My gist that hopefully gives you an idea of the complexity can be found here: https://gist.github.com/orion538/857e018e7b6b7f3eb103

**Comment by robertjpayne** [comment]
@orion538 yea with a table view cell of that complexity you may need to use normal layout for some of the elements (the buttons and labels) by overriding layoutSubviews().

Do you have the constraint code you can paste up too? There may be some optimisations you can do on the constraints but generally speaking looking it it looks like you'll have far too many constraints per cell for it to be super performant.

**Comment by orion538** [comment]
I have updated the gist with a new file containing most of the code of the cell I've shown you:
https://gist.github.com/orion538/857e018e7b6b7f3eb103#file-gistfile2-swift

**Comment by robertjpayne** [comment]
@orion538 yea hmm nothing too out of the ordinary there, just a lot of constraints.

Two things:

* Maybe try to make all the makers snp_remakeConstraints. You may be getting duplicate constraints as you scroll if you're reusing cells.
* Maybe try and re-use as many constraints as you can e.g. if you're reusing the cell you may be able to re-use some of them?

Otherwise it may just be easiest to manually layout the cell using standard frames in an overridden layoutSubviews.

**Comment by orion538** [comment]
Actually I just realized I hadn't modified the snp_makeConstraints to snp_updateConstraints of this cell... Just did. I only update the constant values as far as I know (maybe I anchor the component to a different component at some point, but that shouldn't go wrong). How would one go about reusing constraints? I'm very interested in that. I saw that I can keep references to constraints. Is that the way?

**Comment by robertjpayne** [comment]
@orion538 snp_updateConstraints is good for modifying the constant seldomly as it auto-finds the existing constraint.

If you need a reference:

```
var instanceConstraint: Constraint? = nil
...
self.instanceConstraint = make.top.equalTo(self.contentView.snp_bottom).offset(50).constraint
...
self.instanceConstraint.updateOffset(-50)
```

**Comment by orion538** [comment]
Yes, that would explain why snp_updateConstraints is faster for me than snp_remakeConstraints. I was just wondering if I could manually check if certain constraints already existed and if I need to call snp_updateConstraints. This so that I might be able to speed up the building of the layout. But suppose I gotta use the normal layout if I'd want to speed up my UITableViewController. There's just this slight delay in loading a UITableViewCell when scrolling atm. I was hoping to maybe find an easy fix for this. But if I'm doing nothing abnormal, and you don't see anything weid happening that I might be able to do something to fix my current situation, I'll probably have to resort to the normal layout. I do however not use xib files, but autolayout and size classes are both enabled in my UITableviewController.

**Comment by robertjpayne** [comment]
@orion538 it really just looks like you have a lot of views in each cell hence the layout lag. Luckily in Swift frame based layout is pretty easy since you can modify only parts of the frame in place like:

```
view.frame.origin.x += 20
```

I constantly find myself manually laying out complex cells to get much better scroll performance.

**Comment by orion538** [comment]
Alright I know what to do. Thanks so much for your time and advice.
