### ISSUE TITLE
Example in README not working: UIView does not have a member named snp_makeConstraints

### ISSUE THREAD

**Issue by crucialfelix** [SnapKit/SnapKit#123]
I've set up a a test project and copied the example verbatim. 

SnapKit can be imported, but there are no methods added to UIView.

Specifically: `UIView does not have a member named snp_makeConstraints`

```swift
import SnapKit


class ViewController: UIViewController {

    lazy var box = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.addSubview(box)
        // UIView does not have a member named snp_makeConstraints
        box.snp_makeContraints { (make) -> Void in
            make.width.height.equalTo(50)
            make.center.equalTo(self.view)
        }
    }
    
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

Everything else seems to have built fine and the app runs if that line is commented out.

Targets Support Files/Pods-SnapKit/Pods-SnapKit.debug.xcconfig

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_FRAMEWORK_BUILD_PATH"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited) -iquote "$PODS_FRAMEWORK_BUILD_PATH/SnapKit.framework/Headers"
OTHER_LDFLAGS = $(inherited) -ObjC -framework "SnapKit"
OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SnapKit
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by robertjpayne** [comment]
@crucialfelix 

A couple of questions:

* What version of Xcode are you using?
* What version of Cocoapods are you using?
* What version of iOS are you running on? (Frameworks are only supported on iOS 8.0+)

Have you tried to delete the Pods/ folder and re-running pod install?

**Comment by crucialfelix** [comment]
XCode 6.4
Cocoapods 0.37.2
iOS 8

Just tried trashing Pods and rebuilding. Still not seeing it.

I also tried creating a Constraint to see if that class is found. (nope)

note my test app (and its target) is called SnapKit
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'SnapKit' do
    pod 'SnapKit', '~> 0.12.0'
end
```

**Comment by robertjpayne** [comment]
@crucialfelix I'm like 99% positive your issue will be because your target name is SnapKit as well. You'll probably need that to be SnapKitTest or SnapKitExample or anything but since apps are modules as well.

**Comment by crucialfelix** [comment]
You are 100% correct and I am now 1% smarter than I was before. Thank you !

minor issue which I noticed somebody else posting about: the first time you create the project then the Pods framework is not yet compiled, so xcode still cannot identify the method. build once and after that its fine.

**Comment by robertjpayne** [comment]
@crucialfelix yea not much we can do there :( Typically always recommend build and run first before trying to import any newly installed pods!

Glad it's working for you now.

**Comment by alinaenemezzoglobal** [comment]
I have the same issue, although my integration is based on the Embedded Framework method. I'm following all the steps and just calling import SnapKit and some constraints on a label. I can't build the project but I can see the method is accessible.

**Comment by smileat** [comment]
I have the same issue,still “UIView does not have a member named snp_makeConstraints”，I have set Build Active Architecture Only to YES for Debug。
