### ISSUE TITLE
Apple Mach O XLinker Error, Couldn't find character X.

### ISSUE THREAD

**Issue by charlesvinette** [SnapKit/SnapKit#126]
Hey everyone. I am trying to add SnapKit to my project using cocoapods. Everytime I try, I get a "Build failed" error, telling me XLinker Error, couldn't find character x. I tried with different version of cocoapods and nothing works. I am using the latest version of Xcode.

Any tips? Thanks!

**Comment by robertjpayne** [comment]
@charlesvinette sounds like you need to add `use_frameworks!` to your cocoa pods since that error is when you try to build static libs from Swift code.
