### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by kos9kus** [SnapKit/SnapKit#128]
While compiling:
Undefined symbols for architecture x86_64:
  "__TFE7SnapKitCSo6UIView19snp_makeConstraintsfS0_FFT4makeCS_15ConstraintMaker_T_T_", referenced from:
      __TFC6TellIT24AddNewItemViewController11viewDidLoadfS0_FT_T_ in TellIT-master.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Please any ideas ?
(The latest Xcode version)

**Comment by robertjpayne** [comment]
@kos9kus:

* Xcode 6.4 or 7.0?
* How are you integrating the library?
* Have you tried clean & build or delete derrived data and build?

**Comment by kos9kus** [comment]
Thanks for fast reply 
Xcode 6.4
I added a pod to pod file, as usually do it with another pods  . I tried clean a build many times.
I import library directly as "import SnapChat" and it's worked,
I can't understand if i've already imported the lib through another file why i should do it again, importation happens hierarchically, it seems as arise some bug of xCode,
Am I right?

**Comment by robertjpayne** [comment]
@kos9kus 

A couple of things:

* Make sure in your Podfile you have `use_frameworks!`
* Make sure you `import SnapKit` at the top of each file you want to use it in (Swift does not have the idea of a "prefix" import or shared imports across files)

If that still fails please delete your DerivedData folder you can find it under `Window -> Projects`

**Comment by kos9kus** [comment]
Thanks 
I can follow all your requirements,
*By the way, the problem was gone*

**Comment by robertjpayne** [comment]
@kos9kus ah! If it's fixed than all good was just saying that if you still were having issues.

Cheers! Happy Layouting.
