### ISSUE TITLE
the "and" description missing

### ISSUE THREAD

**Issue by safecat** [SnapKit/SnapKit#129]
in masonry, we can do thing like below
`make.left.right.and.bottom.equalTo(superview);`

looks like there is no "and" in snapkit?

**Comment by robertjpayne** [comment]
@safecat `and` and `with` from Masonry were both purely semantic in the sense that they were no-ops. You should be able to just do `make.left.right.bottom`. They were removed because `with` had some odd side effects with SnapKit's implementation and I decided to remove all semantic no-ops.
