### ISSUE TITLE
Umbrella header for module 'SnapKit' does not include header 'SnapKit'

### ISSUE THREAD

**Issue by KyleXie** [SnapKit/SnapKit#134]
As the title, I got a Swift compiler warning like that. Any body got an idea about what that means? And how to fix it? Thanks!

**Comment by robertjpayne** [comment]
@KyleXie mind explaining your build setup a little bit please? Using Carthage or Cocoapods?

**Comment by KyleXie** [comment]
Hi,  @robertjpayne 

Thanks for reply. I'm using CocoaPods. I added "pod 'SnapKit', '~> 0.13.0'" to my Podfile, and then run "pod install". It works fine, it just that I have no idea what the warning means. You can see from the attachment:
![image](https://cloud.githubusercontent.com/assets/2870241/9298252/14330252-44de-11e5-9a6f-18fdb9505647.png)

**Comment by robertjpayne** [comment]
@KyleXie ah right, Cocoapods must be generating one itself and I've not listed SnapKit.h as a header to include in the podspec!

It's harmless but I'll try and fix this sooner than later.

**Comment by robertjpayne** [comment]
Closing this. I believe this is a Cocoapods bug not SnapKit. Please re-open if this persists with latest Cocoapods and also SnapKit 0.13.0 or 0.14.0

**Comment by haoziy** [comment]
@robertjpayne  I get an other issue ,when I  add "pod 'SnapKit', '~> 0.13.0'" to my Podfile ,It doesn't work, error info like this  
[!] Unable to satisfy the following requirements:

- `SnapKit (~> 0.13.0)` required by `Podfile`

**Comment by robertjpayne** [comment]
@haoziy you should probably try `pod 'SnapKit', '~> 0.19.0'` see if that works?

**Comment by haoziy** [comment]
@robertjpayne thx ,i got it by change version number

**Comment by sozman** [comment]
pod cache clean --all
