### ISSUE TITLE
Cant upload to Appstore with SnapKit installed as submodule.

### ISSUE THREAD

**Issue by arbitur** [SnapKit/SnapKit#135]
I get errors when trying to upload to appstore.

Because I have other pods which cant use the use_framework tag I had to install SnapKit as a submodule.

I followed the instructions on http://snapkit.io/docs/

![skarmavbild 2015-08-19 kl 15 47 23](https://cloud.githubusercontent.com/assets/1361280/9357955/fe539778-4689-11e5-8e8c-96bc07f319fa.png)

**Comment by robertjpayne** [comment]
@arbitur unfortunately you cannot use embedded frameworks regardless of compilation method for iOS 7 targets. The docs are probably not the most clear as it does say you can embed the framework but only for non app store apps.

> While SnapKit supports iOS 7.0, frameworks are not supported for iOS 7.0 so you must manually embed the framework for non app store apps or integrate the source files directly.

You need to do a submodule git checkout but drag the source files manually into your project.

**Comment by arbitur** [comment]
@robertjpayne  Its that easy?? :D

**Comment by robertjpayne** [comment]
@arbitur it's easy but also very frustrating :( Conflicts are much easier when embedding swift source than using it via frameworks.

But yes if you simply add the source files to your project you should be good to go ( maybe fix a conflict if any arise ).
