### ISSUE TITLE
snp_prepareConstraints does not setTranslatesAutoresizingMaskIntoConstraints(false)

### ISSUE THREAD

**Issue by nickvelloff** [SnapKit/SnapKit#136]
Neither does `install()`

Perhaps by design.

Also shouldn't `snp_makeConstraints` return [Constraint] to be used later if needed?

**Comment by robertjpayne** [comment]
@nickvelloff yea the intention for `snp_prepareConstraints` was to not mess with anything but solely generate the constraints.

Though `install` should probably turn off the flag I'll have to give that a think.

As for `snp_makeConstraints` for each constraint(s) you want to keep a reference to:

```
self.storedTopConstraint = make.top.equalTo(other).offset(50).constraint
```

**Comment by robertjpayne** [comment]
The `.constraint` method finalises the 'make' chain and represents all constraints for that single chain. So if you did `make.edges.equalTo(other).constraint` the Constraint returned would actually represent four underlying NSLayoutConstraints.

As far as returning them in the constraint maker methods, I saw little value in getting an array who's order is hard to decipher and utilise so I never implemented it.

**Comment by nickvelloff** [comment]
Thanks for the response. 

My approach has been to set up the constraints as states of the UI and just swap them out (animated) as opposed to storing individual constraints. 

Anyway it is working great for me, was just a heads up. Thanks for the lib!

``` swift
titleLogoCollapsedConstraints = title.snp_prepareConstraints { make in
            make.centerX.equalTo(self)
            make.centerY.equalTo(self)
            make.width.lessThanOrEqualTo(self).multipliedBy(0.75)
        }
titleLogoExpandedConstraints = title.snp_prepareConstraints { make in
       make.left.equalTo(30)
       make.right.equalTo(self).offset(-10)
       make.centerY.equalTo(favLogo.snp_centerY)
}
```
