### ISSUE TITLE
Why not support iOS7?

### ISSUE THREAD

**Issue by 632840804** [SnapKit/SnapKit#145]
I really love your SnapKit, but why your SnapKit do not support iOS7?
In fact, company will require support iOS7, if so, we could not use your SnapKit.

can you make it support iOS7? 

Thanks!

**Comment by robertjpayne** [comment]
@632840804 for now we suggest using 0.13.0 tag and importing the source directly into the project. Working on support for the 0.14.0 / Swift 2.0 version for iOS 7!

**Comment by 632840804** [comment]
Thanks for your reply.

**Comment by trenskow** [comment]
How far is this?
I have an iOS app with support for 7.0, I would like to move to Swift 2.

**Comment by CoderJackyHuang** [comment]
Thanks for your concern.I ask this question just because in Chinese, there are many companies' apps that requires to support iOS 7, so if we want to use SnapKit, it must support to ios 7, otherwise no way for us.

**Comment by lacklock** [comment]
@CoderJackyHuang +10086
