### ISSUE TITLE
Segmentation fault using insets

### ISSUE THREAD

**Issue by mgieselman** [SnapKit/SnapKit#148]
Not a problem with SnapKit but the Xcode 7 GM compiler "segmentation fault: 11" anytime it encounters:

downloadAllButton.snp_makeConstraints { make in
            make.top.equalTo(downloadButton.snp_bottom).offset(10)
            make.left.right.equalTo(view).insets(UIEdgeInsetsMake(10, 10, 10, 10))
        }

the .insets causes the problem.

**Comment by peeinears** [comment]
I'm getting this too.

**Comment by robertjpayne** [comment]
`insets` is now `inset` as noted in the changelog, sorry for the confusion.

**Comment by peeinears** [comment]
Derp, thanks!
