### ISSUE TITLE
Using snp_topLayoutGuideBottom causes views to disappear on Swift 2.0 branch

### ISSUE THREAD

**Issue by andrewpbrett** [SnapKit/SnapKit#150]
I'm setting up a view and trying to pin a subview (it happens to be a `UISwitch`) to the bottom of the topLayoutGuide, like so:

`make.top.equalTo(self.snp_topLayoutGuideBottom).offset(20)`

However, when I do this, the view doesn't appear on the screen, nor when I look in the Debug View Heirarchy view. 

If I switch that line to be:

`make.top.equalTo(self.snp_topLayoutGuideTop).offset(20)`

or

`make.top.equalTo(100)`

Then the view appears on the screen as expected. 

My only other theory is that it's something to do with the fact that it's a `UISwitch` but that seems unlikely. 

(Edit: confirmed that even changing it to a regular `UIView` doesn't change the behavior)

**Comment by robertjpayne** [comment]
@andrewpbrett are you using Swift 2.0 branch or are you using the latest release 0.15.0 that now includes Swift 2.0?

**Comment by andrewpbrett** [comment]
Ahhhh that could be it - I was on the Swift 2.0 branch. I'll try the 0.15.0 release later tonight.

**Comment by andrewpbrett** [comment]
Confirmed that switching to 0.15.0 works like a charm, thanks Robert.
