### ISSUE TITLE
Seg fault: 11 when trying to assign constraint to a global var

### ISSUE THREAD

**Issue by martinliu0** [SnapKit/SnapKit#152]
I want to animate a subview so I added this line of code: 

`self.durationNotificationTopConstraint = make.top.equalTo(self.view.bounds.height).offset(0)`

And this caused a seg fault. I'm using Xcode 7.0, Swift 2.0

**Comment by Ziewvater** [comment]
I'm having the same issue. Trying to save a reference to a constraint declared as

```private var holeNumberCenteringConstraint: Constraint!```

Getting the error message:

```error: use of undeclared type 'Constraint'
    private var holeNumberCenteringConstraint: Constraint!```

**Comment by robertjpayne** [comment]
Please see the docs under `1. References`:

```
var topConstraint: Constraint? = nil

...

// when making constraints
view1.snp_makeConstraints { (make) -> Void in
  self.topConstraint = make.top.equalTo(superview).offset(padding.top).constraint
  make.left.equalTo(superview).offset(padding.left)
}

...
// then later you can call
self.topConstraint.uninstall()

// or if you want to update the constraint
self.topConstraint.updateOffset(5)
```

You're missing a finaliser of `.constraint`

**Comment by Ziewvater** [comment]
I'm setting the constraint variable in the following way

```
self.holeNumber.snp_makeConstraints { (make) -> Void in
    self.holeNumberCenteringConstraint =  make.centerX.equalTo(contentView).constraint
    make.centerY.equalTo(contentView)
    make.width.equalTo(self.holeNumberRing.snp_width)
}
```

and calling 

```
self.holeNumberCenteringConstraint.updateOffset(-8)
```

When doing this, I get a seg fault while building. There are no warnings or errors when I refer to `Constraint` in this manner, but I've found that if I explicitly downcast something to `Constraint` within a function, I get the error `Use of undeclared type 'Constraint'`

**Comment by robertjpayne** [comment]
Is the compiler segfaulting or is it segfaulting at runtime? And did you just upgrade from a previous version to `0.15.0`?

**Comment by Ziewvater** [comment]
It's segfaulting while building. `Podfile.lock` shows that we're using 0.13.0.

**Comment by robertjpayne** [comment]
@Ziewvater hey can you upgrade to `0.15.0` also compiler segfaults in Swift are normally a syntax issue we recently had a breaking change that `insets` was renamed to `inset` and is the most common cause of that from v0.13.0 and on.

**Comment by Ziewvater** [comment]
Okay cool. I'll update once I speak with my team and report back on whether or not the issue persists

**Comment by robertjpayne** [comment]
@Ziewvater the upgrade itself isn't likely to fix it, somewhere you have a syntax error that is causing the segfault, they are extremely frustrating but sometimes if you really hunt in the build log you can see what file and what line of code are causing it.

One other area I know it happens a lot, can you paste one of your `snp_makeConstraints` blocks?

**Comment by Ziewvater** [comment]
The issue disappears when I stop referring to `Constraint` directly in my code. I was able to achieve the same desired effect by using `snp_remakeConstraints`, so I'm not blocked though.

the code I posted above is a good example of what I'm doing most of the time. Basically doing stuff much like the example below:

```
self.commentCountButton.snp_makeConstraints { (make) -> Void in
    make.top.equalTo(parLabel.snp_top)
    make.right.equalTo(contentView).offset(-15)
}
```

**Comment by robertjpayne** [comment]
@Ziewvater I just ran some tests, looks like the compiler segfaults if the variable is a global var, it works fine if it's an ivar of a class or a static var on a class/struct.
