### ISSUE TITLE
Updating Constraint multiplier

### ISSUE THREAD

**Issue by sleekuser** [SnapKit/SnapKit#155]
If I have constraint like
```
progressBarView?.snp_makeConstraints(closure: { make in
        .....
        constraint = make.width.equalTo(self).multipliedBy(1).constraint
    })
```

Is there any way I can update **multiplier** using method like `updateOffset`?

A temporary solution would be to use `progressBarView?.snp_updateConstraints`, but it will be nice to have a direct method like offset does.

**Comment by robertjpayne** [comment]
@sleekuser unfortunately Auto Layout does not support updating the multiplier so we cannot allow it in SnapKit.

**Comment by huguesbr** [comment]
@robertjpayne can you still use `snp_updateConstraints` to update the multiplier?
