### ISSUE TITLE
Constraints not updating with iOS 9 SDK and Swift 2.0 

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [SnapKit/SnapKit#156]
Hi, 

I currently experienced an issue where my constraints won't update, when I call snp_updateConstraints. 
This seems to be an issue since I work with the iOS 9  SDK and Swift 2.0 .

Here's my code: 
```swift 
//Here I'm creating my constraints 
self.backgroundImage.snp_makeConstraints{
            (make) -> Void in
            make.bottom.equalTo(0)
            make.top.equalTo(0)
            make.leading.equalTo(0)
            make.trailing.equalTo(0)
        }

// And here I'm updating them 
backgroundImage.snp_updateConstraints{
                (make) in
                make.bottom.equalTo(y)
                make.top.equalTo(y)
                make.leading.equalTo(y)
                make.trailing.equalTo(y)
            }
```

In my logs you can see that snp_updateConstraints creates a new Constraint and is only updating the new one and not the old one. 
	
__Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)__

(

    "<TouchToWin.LayoutConstraint:0x1704a2fa0@/Users/AlexSFD/Sn0wfreeze-Dev/Projekte/TouchToWin/App/TouchToWin/SingleLotteryVC.swift#110 UIImageView:0x12c644680.top == UIView:0x12c6442e0.top - 113.0>",

    "<TouchToWin.LayoutConstraint:0x1704a3c00@/Users/AlexSFD/Sn0wfreeze-Dev/Projekte/TouchToWin/App/TouchToWin/SingleLotteryVC.swift#110 UIImageView:0x12c644680.top == UIView:0x12c6442e0.top - 11.0>"

)

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev can you post more of your code or the full error message? What is `y` in this situation?

**Comment by Sn0wfreezeDev** [comment]
y is a constant which is calculated by the current offset of the scroll view in front. 
The calculation of y seems alright. When I apply it to my NSLayoutConstraint outlets the animation works as expected. 

Here's the code: 
```swift 
    override func updateViewConstraints() {
        super.updateViewConstraints()
        
        let y  =  self.collectionView.contentOffset.y + self.collectionView.contentInset.top
        if y <=  0 {
            backgroundImage.snp_updateConstraints{
                (make) in
                make.bottom.equalTo(y)
                make.top.equalTo(y)
                make.leading.equalTo(y)
                make.trailing.equalTo(y)
            }   
        }

    }
```

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev I think it may be because you're setting constraints to a constant without a superview:

With the exception of width/height constraints the `equalTo` should always specify the `to item` of the constraint. In most cases this will be the `superview` but not always.

Can you try and update your code to read something like:

`make.top.equalTo(otherView).offset(y)`

And see if the error persists?

**Comment by Sn0wfreezeDev** [comment]
Sadly this does not seem to work in my case. 

Here's the code: 
```swift 
    override func viewDidLoad() {
//....
        self.view.addSubview(self.backgroundImage)
        self.view.sendSubviewToBack(self.backgroundImage)
        self.backgroundImage.snp_makeConstraints{
            (make) in
            make.bottom.equalTo(self.view).offset(0.0)
            make.top.equalTo(self.view).offset(0.0)
            make.trailing.equalTo(self.view).offset(0.0)
            make.leading.equalTo(self.view).offset(0.0)
        }
//...
}


    override func updateViewConstraints() {
        super.updateViewConstraints()
        
        let y  =  self.collectionView.contentOffset.y + self.collectionView.contentInset.top
        if y <=  0 {
            self.backgroundImage.snp_updateConstraints{
                (make) in
                make.bottom.equalTo(self.view).offset(y)
                make.top.equalTo(self.view).offset(y)
                make.trailing.equalTo(self.view).offset(y)
                make.leading.equalTo(self.view).offset(y)
            }
            
        }

    }
```

Logs: 
2015-09-29 10:11:33.904 TouchToWin[1200:396443] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<TouchToWin.LayoutConstraint:0x1700ac420@/Users/AlexSFD/Sn0wfreeze-Dev/Projekte/TouchToWin/App/TouchToWin/SingleLotteryVC.swift#56 UIImageView:0x15d62ad60.bottom == UIView:0x15d646e60.bottom>",
    "<TouchToWin.LayoutConstraint:0x1700ad5c0@/Users/AlexSFD/Sn0wfreeze-Dev/Projekte/TouchToWin/App/TouchToWin/SingleLotteryVC.swift#108 UIImageView:0x15d62ad60.bottom == UIView:0x15d646e60.bottom - 0.5>"
)

Will attempt to recover by breaking constraint 
<TouchToWin.LayoutConstraint:0x1700ac420@/Users/AlexSFD/Sn0wfreeze-Dev/Projekte/TouchToWin/App/TouchToWin/SingleLotteryVC.swift#56 UIImageView:0x15d62ad60.bottom == UIView:0x15d646e60.bottom>

Here's a video of my problem. You should take a look at the blurred background. It should grow and get smaller while I scroll through the collectionView. 

https://www.dropbox.com/s/j6yzppg70auxfk7/Snapkit%20Error%20.mov?dl=0

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev what if you use `snp_remakeConstraints` instead? Just trying to see if the problem is with the constraints you're attempting to create, or SnapKit.

**Comment by Sn0wfreezeDev** [comment]
I tried that already and I'm getting the same problem 😔

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev if you get the same problem it's something wrong with the constraints/combo of constraints, it's hard to say but what is `self.view`? Is it a UIView or UICollectionView? also try `left` and `right` instead of `leading` / `trailing`

**Comment by Sn0wfreezeDev** [comment]
@robertjpayne  
I tried left and right, but nothing changes. 
self.view is a normal UIView. 

This problem occurred on another view in my project as well. Did you try to reproduce it?

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev I think I may know what is happening. Is there any chance that:

`updateViewConstraints` is getting called before `viewDidLoad`? Can you try one last thing of making each constraint block a `snp_remakeConstraints`?

I've never experienced an issue like this but I've not attempted to reproduce because this isn't really a full code sample and I'm a busy person!

**Comment by Sn0wfreezeDev** [comment]
@robertjpayne 

Okay I found a fix and it seems that it isn't a problem with the newest version. 
I don't know which Swift 2.0 build I had, but updating to the newest version fixed the problem. 
Constraints are now generated correctly and updated correctly. 

Sorry for the inconvenience, I didn't know that I had an older version.

**Comment by robertjpayne** [comment]
@Sn0wfreezeDev no worries!
