### ISSUE TITLE
Add another action to .travis.yml to also build and test with OS X target.

### ISSUE THREAD

**Issue by TadeasKriz** [SnapKit/SnapKit#158]
This would help to make sure no PR will break the codebase, just because the author did not try building for OS X, which is something anyone can easily forget to do and CI should make sure it does not happen.

**Comment by money150604** [comment]
Legacy Platforms (iOS 7.0, OS X 10.9)  ——> s.ios.deployment_target = '8.0'
不是说支持7.0嘛？。。
