### ISSUE TITLE
Crashing on device iOS 9.0.2, but works on simulator

### ISSUE THREAD

**Issue by vikascg** [SnapKit/SnapKit#160]
Can anyone help us resolving this issue,

Code Snippet:
backgroundImg.snp_makeConstraints { (make) -> Void in
            make.edges.equalTo(self.view).inset(UIEdgeInsetsMake(0, 0, 0, 0))
        }

let closeButton: UIButton = UIButton()
        closeButton.setBackgroundImage(UIImage(named: "closeButtonImage"), forState: .Normal)
        self.view.addSubview(closeButton)

closeButton.snp_makeConstraints { (make) ->Void in
            make.top.equalTo(self).offset(30.0)
            make.leading.equalTo(self).offset(20.0)
            make.height.equalTo(24.0)
            make.width.equalTo(24.0)
        }

Error Description:
0  SnapKit                        0x000000010063a16c ConstraintDescription.init(fromItem : ConstraintItem) -> ConstraintDescription (ConstraintDescription.swift:494)

**Comment by robertjpayne** [comment]
@vikascg can you post the full crash log as well as code sample? It's useful to see what `self` is when you're setting up constraints and sorts as well as what other thread(s) may be doing etc…

**Comment by vikascg** [comment]
Robert, thanks for quick reply.
I fixed this problem. It was occurring due to the way project is setup.
