### ISSUE TITLE
Build error in my swift project

### ISSUE THREAD

**Issue by neil-wu** [SnapKit/SnapKit#164]
xcode 7, swift 2.0, deployment target is iOS 7.0.
Flollowing the step in [this document](http://snapkit.io/legacy-platforms/) to integrate.
There are some building error, like following snapshot:
![snip20151021_1](https://cloud.githubusercontent.com/assets/5682948/10631778/bcde0a0c-7812-11e5-9d36-84df891e2aed.png)

I modify the source code, add ```if  #available(iOS 8.0, *) ```, and then it works well.

**Comment by robertjpayne** [comment]
@neil-wu did you add the `-DSNAPKIT_DEPLOYMENT_LEGACY` flag to your `OTHER_SWIFT_FLAGS`?

**Comment by neil-wu** [comment]
Got it! thx.
