### ISSUE TITLE
Framework Binaries with Github Releases

### ISSUE THREAD

**Issue by carlossless** [SnapKit/SnapKit#167]
Hi, thank you for your amazing work with SnapKit and Masonry, it's been helping me build interfaces on iOS and OSX for some time now.

Since SnapKit supports Carthage, I was wondering if binary releases could also be released with new tags.

**Comment by robertjpayne** [comment]
@carlossless unfortunately I have no intention of releasing binaries alongside the releases. Mostly because every version of Swift will require a release of SnapKit and we're not really keen on managing that. Luckily SnapKit is a small library and compiles pretty quick!

**Comment by carlossless** [comment]
Alright, still, thank you for considering this!
