### ISSUE TITLE
snp_updateConstraints adds a second constraint instead of updating (only changing the offset)

### ISSUE THREAD

**Issue by ThomasCle** [SnapKit/SnapKit#168]
I am trying to update the offset of a top-constraint on `scrollViewDidScroll:`

First I add the constraints I need in `viewDidLoad:`:

    self.myView!.snp_makeConstraints(closure: { (make) -> Void in
         make.width.equalTo(self.tableView)
         make.top.equalTo(self.tableView).offset(0)
         make.height.greaterThanOrEqualTo(self.myView!.headerHeight)
    })

Then I try to update the top-constraint in `scrollViewDidScroll:`:

    self.myView!.snp_updateConstraints(closure: { (make) -> Void in
        make.top.equalTo(self.tableView).offset(-scrollView.contentOffset.y)
    })

When I try to do so, I get the following error:
> Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "SnapKit.LayoutConstraint:0x7fe050ce62c0@/path/to/app/HeaderTableViewController.swift#93 App.CenteringTableHeaderView:0x7fe050fcdd40.top == UITableView:0x7fe05110e400.top + 183.0",
    "SnapKit.LayoutConstraint:0x7fe050cf4410@/path/to/app/HeaderTableViewController.swift#50 App.CenteringTableHeaderView:0x7fe050fcdd40.top == UITableView:0x7fe05110e400.top"
)

> Will attempt to recover by breaking constraint 
SnapKit.LayoutConstraint:0x7fe050ce62c0@/path/to/app/HeaderTableViewController.swift#93 App.CenteringTableHeaderView:0x7fe050fcdd40.top == UITableView:0x7fe05110e400.top + 183.0

> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in UIKit/UIView.h may also be helpful.

As you can see, it looks like the top-constraint gets added with the offset, instead of updating the offset of the existing constraint.

I have had this working with `NSLayoutConstraint` without any problem, but I want to use SnapKit instead:

    self.constraintViewTop = NSLayoutConstraint(item: self.tableView, attribute: .Top, relatedBy: .Equal, toItem: self.myView, attribute: .Top, multiplier: 1.0, constant: 0.0)
    self.tableView.addConstraint(self.constraintViewTop!)

And then changing the offset by:

     self.constraintViewTop?.constant = -scrollView.contentOffset.y;

Am I using the "offset" wrong or how can I achieve this with SnapKit?

**Comment by robertjpayne** [comment]
@ThomasCle it's a bit odd indeed, is `myView` by chance being set as the table header view?

**Comment by ThomasCle** [comment]
Yes it is :)

**Comment by robertjpayne** [comment]
Hm, how are you arranging your subviews and adding the constraints? Also are you using the latest version of SnapKit?

I just setup a new project and this UIViewController class works fine:

```swift
//
//  ViewController.swift
//  SnapKitTest
//
//  Created by Robert Payne on 10/11/15.
//  Copyright © 2015 Zwopple Limited. All rights reserved.
//

import SnapKit
import UIKit

class ViewController: UIViewController, UITableViewDelegate {

    let tableView = UITableView()
    let headerView = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.headerView.backgroundColor = UIColor.redColor()
        
        self.view.addSubview(self.tableView)
        self.tableView.tableHeaderView = self.headerView
        
        self.tableView.snp_makeConstraints { (make) -> Void in
            make.edges.equalTo(self.view)
        }
        
        self.headerView.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(self.tableView)
            make.width.equalTo(self.view)
            make.height.equalTo(44)
            make.centerX.equalTo(self.view)
        }
        
        self.tableView.alwaysBounceVertical = true
        self.tableView.delegate = self
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func scrollViewDidScroll(scrollView: UIScrollView) {
        self.headerView.snp_updateConstraints { (make) -> Void in
            make.top.equalTo(self.tableView).offset(-scrollView.contentOffset.y)
        }
    }


}
```

**Comment by ThomasCle** [comment]
Oops, sorry for the inconvenience. It looks like I accidentally had moved the `snp_makeConstraints` to `viewDidLayoutSubviews` instead of `viewDidLoad:`.

It works perfectly now. Thank you for the example. It helped me to spot the problem.
