### ISSUE TITLE
Some composite constraints broken in develop branch

### ISSUE THREAD

**Issue by efremidze** [SnapKit/SnapKit#169]
The following doesn't seem to work anymore after upgrading from 0.16 to 0.17. Im adding an UIImageView to a UICollectionViewCell.

```
let image = UIImage(named: "image")
let imageView = UIImageView(image: image)
contentView.addSubview(imageView)

imageView.snp_makeConstraints { make in
    make.top.right.equalTo(contentView).inset(7)
    make.size.equalTo(CGSize(width: 15, height: 15))
}
```

Using Xcode 7.1, iOS 9.1, swift 2.1

**Comment by robertjpayne** [comment]
@efremidze are you getting an compiler error, or runtime error? Or is it just not working at all? A bit more info would be very helpful.

**Comment by anlaital** [comment]
0.17 did indeed break CGSize constraints completely. There are no errors and no debug prints, but setting

```
make.size.equalTo(someCGSize)
```

does not work whereas

```
make.width.equalTo(someCGSize.width)
make.height.equalTo(someCGSize.height)
``` 

does still work.

**Comment by efremidze** [comment]
No errors, the constraints are missing.

**Comment by zhixing** [comment]
Same issue here with 0.17.

**Comment by robertjpayne** [comment]
Hey all, I've confirmed this now in 0.17, fix is to use 0.16 until I can get 0.18 out ( later tonight ).

**Comment by robertjpayne** [comment]
I've pushed 0.18.0 to Cocoapods, it simply reverts all of 0.17.0 but that only removes some debugging info so it should work just as good as it did before you all upgraded to 0.17.0.

Going to leave this open because we will need to resolve it in develop.

**Comment by bumaociyuan** [comment]
I have the same issue 
```
make.size.equalTo(CGSizeMake(LOGO_WIDTH, LOGO_WIDTH))
// not working
```

**Comment by robertjpayne** [comment]
This should no longer be an issue. Develop has had these commits removed and is back to normal.
