### ISSUE TITLE
Using operators inside multipliedBy

### ISSUE THREAD

**Issue by jfizz** [SnapKit/SnapKit#170]
For some reason, when I enter:
```
make.width.equalTo(snp_width).multipliedBy(1 / 3)
````
it sets the width to 0. However, when I set it to:
```
make.width.equalTo(snp_width).multipliedBy(0.3)
````
everything works as expected. Any ideas, or am I just missing something?

**Comment by robertjpayne** [comment]
@jfizz most likely Swift's type inference getting you here. 1/3 as an `Int` operation will be zero as it will return an Int.

You need to do something like 1.0 / 3.0 or 1/3.0 or anything that would give the Swift compiler an indication the output should be a Float/Double rather than Int.

**Comment by jfizz** [comment]
*facepalm

**Comment by robertjpayne** [comment]
@jfizz no sweat. It doesn't help we have an overload for `multipliedBy` that accepts every type of primitive.
