### ISSUE TITLE
Spacer Views/Centering?

### ISSUE THREAD

**Issue by mccannmax** [SnapKit/SnapKit#174]
Is it possible to user spacer views with SnapKit? Or is there a simple way to center between two views?

Example:
|View1|-----|CenteredView|-----|View2|

**Comment by wizzardchao** [comment]
I suppose to use 2 spacers(empty UIView) to archive this, like |view1|------|spacer1|------|CenteredView|------|spacer2(=spacer1)|-----|view2|.
Maybe it's more convenient to implement this with VFL?

**Comment by robertjpayne** [comment]
This is more an auto layout issue that is difficult to solve because there isn't much in the way of "invisible spacers" until iOS 9 which we've not built tons of support in for yet.

Are view1 and view2 identical widths?

**Comment by neelamsharma12** [comment]
@wizzardchao  Yes it will be more convenient to implement this with VFL. We can just use 
view1.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(self.arrowImageView).offset(23)
            make.right.equalTo(CenteredView).offset(34) 
}
Like this way we can use left and right constraints with respect to superview and with the CenteredView with each view.

Also ,
We can use spacers b/w the views to provide the spaces

**Comment by robertjpayne** [comment]
Closing this as sort of non-issue. For now use empty UIView's as 'spacers'. Probably by WWDC this year I'll start to work in iOS 9 API's.
