### ISSUE TITLE
Error installing with Carthage?

### ISSUE THREAD

**Issue by danqing** [SnapKit/SnapKit#176]
I'm trying to load SnapKit via Carthage (osx 10.11.2 and xcode 7.2), but I get the following error:

```
*** Building scheme "SnapKit iOS" in SnapKit.xcworkspace
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'
```

This seems to only happen with the iOS target. I've tried both 0.17 and 0.18 and neither seems to work. I saw on StackOverflow that there may be some framework path issues but I don't really see those. Is it just me or is there something wrong with SnapKit setup?

Thanks!

**Comment by robertjpayne** [comment]
@danqing I'll have a look when I can, probably something silly with Xcode.

**Comment by iosengineer** [comment]
Is this still an issue? I've not had the smoothest experience with Carthage to date. Am considering reverting to CocoaPods (because it works).

**Comment by danqing** [comment]
This is still an issue, but oftentimes when I run `carthage update

**Comment by danqing** [comment]
And yeah... CocoaPods is more reliable... I just don't like the extra stuff it put in my project..

**Comment by neelamsharma12** [comment]
@danqing It is easy to implement it by using CocoaPods. I implemented the same using CocoaPods it working smoothly. If you require any help just let me know.

**Comment by robertjpayne** [comment]
Yea so latest Carthage works fine on fresh installs. Maybe try to clean out Carthage and Cartfile.resolved and try again. Other thing to check is what version of SnapKit you are trying to pin.

Re-open if this still causes issues.
