### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by Damonvvong** [SnapKit/SnapKit#177]
```Swift
@IBOutlet weak var snapView: UIView!
    override func viewDidLoad() {
        super.viewDidLoad()


        snapView.translatesAutoresizingMaskIntoConstraints = false

        snapView.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(view)
        }
    }

```

When I run the code I get the following console output:

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<SnapKit.LayoutConstraint:0x7fed03c40080@/Users/damon/Desktop/SnapDemo/SnapDemo/ViewController.swift#21 UIView:0x7fed03c3b900.left == UIView:0x7fed03c3c000.left>",
    "<NSIBPrototypingLayoutConstraint:0x7fed03c3d580 'IB auto generated at build time for view with fixed frame' H:|-(256)-[UIView:0x7fed03c3b900](LTR)   (Names: '|':UIView:0x7fed03c3c000 )>"
)

Will attempt to recover by breaking constraint 
<NSIBPrototypingLayoutConstraint:0x7fed03c3d580 'IB auto generated at build time for view with fixed frame' H:|-(256)-[UIView:0x7fed03c3b900](LTR)   (Names: '|':UIView:0x7fed03c3c000 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

so this is xcode’s bug or snapKit's bug?
if i add a constraint in storyBoard the conflict dismiss。
i finally solve this problem with [this way](http://stackoverflow.com/questions/30534850/prevent-interface-builder-from-auto-creating-constraints)
can i solve it in other way?

**Comment by iosengineer** [comment]
If you're using an outlet, that means you may have constraints defined (even automatically) by your storyboard or XIB file. Remove or disable the constraints in that file (look at all the checkboxes for that UIView or the whole storyboard/XIB).

Better to apply constraints in the `updateConstraints` method of either the view or the view controller (and to use _updateConstraints then, instead of make). Super is called afterwards for this case.

**Comment by robertjpayne** [comment]
Yea @iosengineer is right. Mixing SnapKit and IB constraints can be tricky. I'd recommend only adding the extras you need with SnapKit or setting all of IB's as placeholder when you're using SnapKit with a view or views.

**Comment by Damonvvong** [comment]
@iosengineer thank you!
@robertjpayne thank you too!
