### ISSUE TITLE
How to offset the offset of a constraint?

### ISSUE THREAD

**Issue by soapsign** [SnapKit/SnapKit#178]
If we want to offset the offset of a constraint right now, we need to bookkeeping the original value as there is no ```Constraint.getOffset()```.
Can we have ```Constraint.getOffset()``` or ```Constraint.addOffset()``` ?

**Comment by robertjpayne** [comment]
@soapsign unfortunately this isn't going to be possible the way the API works the `offset` is stored in a way that results in destructiveness.

Do you have a specific use case you always find yourself having to implement this for?

**Comment by soapsign** [comment]
Ok. I think I will work around this.
By the way, I would like to ask can we have a ```Constraint.updateMultipler()```?

**Comment by wizzardchao** [comment]
@soapsign, I remember we can only change the constant variable of NSLayoutConstraint rather than the multiplier. We must remove a constraint and add a new constraint to archive such things.

**Comment by soapsign** [comment]
Thank you for your prompt reply!

**Comment by robertjpayne** [comment]
@soapsign yea @wizzardchao is correct, the multiplier is not able to be modified after the constraint is created, you have to remove it, re-create it and re-add it. Or in SnapKit terms you need to do a `snp_remakeConstraints`

**Comment by soapsign** [comment]
@robertjpayne ```snp_remakeConstraints``` is really handy! Thank you.
