### ISSUE TITLE
make.size.equalTo() was broken.

### ISSUE THREAD

**Issue by havthgem** [SnapKit/SnapKit#182]
Like this example:
``` swift
let button = UIButton(type: .System)
button.setTitle("The Button", forState: .Normal)
view.addSubview(button)
button.snp_makeConstraints(closure: {
	make in
	make.center.equalTo(self.view)
	make.size.equalTo(CGSize(width: 100, height: 50))
})
```

`make.size.equalTo(CGSize(width: 100, height: 50))` is not available.
my view is empty.

**Comment by devxoul** [comment]
It works for me with replacing `button` with `btn`, which error did you see?

**Comment by havthgem** [comment]
> It works for me with replacing button with btn, which error did you see?

No error.

**Comment by robertjpayne** [comment]
@havthgem 'is not available' do you mean you are getting a compiler error or at runtime you see no changes?

In the sample code you are adding constraints to `btn` but your new view is `button`. Also ensure you have an `import SnapKit` at the top of every file in which you wish to use it.

**Comment by havthgem** [comment]
@robertjpayne Sorry, is my typo. but actual code is no wrong.
I can't see button at this example and no error.

I try `make.width.equalTo()` and `make.height.equalTo()`, is available (can see button). But `make.size.equalTo()` no.

**Comment by ganquan** [comment]
I have the same problem.
```swift
    private func initViews() {
        
        testButton = UIButton()
        testButton.backgroundColor = UIColor.redColor()
        self.view.addSubview(testButton)
        
        testButton.snp_makeConstraints {[weak self](make) -> Void in
            
            make.size.equalTo(CGSizeMake(120, 44))
            make.center.equalTo(self!.view)
        }
        
    }
```

the code above did not set the size of testButton, I just got a zero size button.
so I have to use code below:
```Swift
           make.width.equalTo(120)
           make.height.equalTo(44)
```
these works for me.

Using SnapKit (0.19.0)
XCode: Version 7.2 (7C68)

**Comment by xsdlr** [comment]
+1

**Comment by ryanmaxwell** [comment]
Yep all my code with `make.size.equalTo(rect)` is now broken. Workaround with `make.width.equalTo(rect.width`), `make.height.equalTo(rect.height)`

**Comment by robertjpayne** [comment]
To everyone watching this issue. Please point at SnapKit `0.19.1` as it contains a fix for this.
