### ISSUE TITLE
No completion block for all constraints

### ISSUE THREAD

**Issue by teradyl** [SnapKit/SnapKit#187]
There is some blur code I would like to run after all my views are setup with the correct sizes, but without a callback after all of the constraint blocks have finished setting everything up, I am unable to find a place to reliably run the blur code. It seems like this would be an important addition for SnapKit.

**Comment by robertjpayne** [comment]
@teradyl the closures are all run synchronously so you do not need a callback.

You likely want to run blur code in `viewDidLayoutSubviews` in a UIViewController or `layoutSubviews` in a UIView. Take mind of these two methods though as they are called very frequently you will want to cache blur results based on frame sizes.
