### ISSUE TITLE
UILayoutGuide

### ISSUE THREAD

**Issue by monowerker** [SnapKit/SnapKit#195]
I've previously used Masonry and am now looking at SnapKit for a new project, has there been any discussion or thoughts about what support for the new UILayoutGuide class in iOS9 would look like in SnapKit?

**Comment by robertjpayne** [comment]
@monowerker you should be able to use them already via UIViewController.topLayoutGuide.top/bottom or you can pass a UILayoutGuide/UILayoutSupport object directly into the `equalTo` API!

Let me know if you need something else particular.

**Comment by robertjpayne** [comment]
Closing this, if you feel it's not resolved please re-open.

**Comment by Ziewvater** [comment]
It doesn't seem like I'm able to use `UILayoutGuide` in the `equalTo` API as you've mentioned above.

With code like the following I get an error
```swift
let someView = UIView()
let label = UILabel()

someView.addSubView(label)

let layoutGuide = UILayoutGuide()
someView.addLayoutGuide(layoutGuide)

label.snp_makeConstraints { make in
    make.left.equalTo(layoutGuide)
    // ^ Cannot invoke 'equalTo' with an argument list of type '(UILayoutGuide)'
}
```

I'm using SnapKit 0.20.0.

**Comment by robertjpayne** [comment]
@Ziewvater just want to 100% make sure you have `import SnapKit` at the top of your Swift file?

**Comment by Ziewvater** [comment]
I didn't before. Just tried again with it imported at the top and I'm still getting the same error.

Is the fact that SnapKit methods were available without `import SnapKit` something I should be concerned about too? I've been getting confused about pods that seemingly don't need import statements to work.

**Comment by Ziewvater** [comment]
Just tested again in an empty project with just SnapKit added through CocoaPods. Trying to use a `UILayoutGuide` as an argument for `equalTo` brings up the same error I mentioned above.

**Comment by PacificCoaster** [comment]
I have come into this discussion somewhat late.   I have tried several variations on trying to get something to work, and they all fail.

Could somebody provide an example that works.

Alternatively, can somebody provide an example of adding constraints to my View Controller's view such that it takes the Navigation Bar into account?

**Comment by julianwilson** [comment]
I'm trying to use this with the topLayoutGuide bottomAnchor, is this currently possible?

Code to replace:
`scrollView.topAnchor.constraintEqualToAnchor(topLayoutGuide.bottomAnchor).active = true`

Currently trying:
`scrollView.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(self.topLayoutGuide.bottomAnchor)
 }`

But since .bottomAnchor isn't of UILayoutGuide type it won't work.

**Comment by PacificCoaster** [comment]
I eventually gave up on it.    I could not get any variant to work.

I'm currently using a hack to set the top edge to 64.0, as i 'know' that all
of my View Controller Views are managed by a Navigation Controller.

**Comment by robertjpayne** [comment]
@julianwilson what you want to do is do `equalTo(self.snp_topLayoutGuideBottom)` I believe

**Comment by prattcmp** [comment]
Still unable to get this to work after looking through various issues.
