### ISSUE TITLE
Create two labels in the same row

### ISSUE THREAD

**Issue by NVAT** [SnapKit/SnapKit#197]
I am trying to create labels constraint in the same row with offset each other and superview,for example offset with superview equal 20pt but offset each other no fixed.

**Comment by netgfx** [comment]
Is there an example of something like this? Also interested

**Comment by robertjpayne** [comment]
@NVAT @netgfx as per the [Contributing Guidelines](https://github.com/SnapKit/SnapKit/blob/develop/CONTRIBUTING.md) please try to keep the issue tracker for bugs only.

In saying that you'd simply want something like:

```swift
let label1 = UILabel()
let label2 = UILabel()
let labelsView = UIView()

self.view.addSubview(labelsView)
self.labelsView.addSubview(label1)
self.labelsView.addSubview(label2)

self.labelsView.snp_makeConstraints { make in
    make.center.equalTo(self.view)
}
self.label1.snp_makeConstraints { make in
    make.left.top.bottom.equalTo(self.labelsView).inset(20)
    make.right.equalTo(self.labelsView.snp_right).offset(-10)
}
self.label2.snp_makeConstraints { make in
    make.right.top.bottom.equalTo(self.labelsView).inset(20)
    make.left.equalTo(self.labelsView.snp_left).offset(10)
}
```

**Comment by NVAT** [comment]
Thank you for answer,I try your cod but all labels were in center of view.
I use code below,its ok,but when label text length is long the second label has disappeared for view,only after rotating is appear.I cant understand wats wrong      


 let docNumber = UILabel()
        docNumber.text = "234234"
        docNumber.lineBreakMode = .ByTruncatingMiddle
        self.view.addSubview(docNumber)
        
        
        let docTitle = UILabel()
        docTitle.text = "Document number of loan contract"
        docTitle.lineBreakMode = .ByTruncatingMiddle
        self.view.addSubview(docTitle)
        
        
        docTitle.snp_makeConstraints { make in
            make.left.top.equalTo(view).offset(20)            
        }
        
           docNumber.snp_makeConstraints { make in
            make.top.equalTo(docTitle.snp_top)
            make.left.equalTo(docTitle.snp_right).offset(-8)
            make.right.equalTo(view).offset(-20)
            
        }

**Comment by robertjpayne** [comment]
@NVAT it'd be much easier if you could post a screenshot from Photoshop/Sketch etc… of what you're trying to accomplish as I'm not 100% sure.

**Comment by NVAT** [comment]
![simulator screen shot feb 9 2016 10 36 47](https://cloud.githubusercontent.com/assets/16933227/12909312/00fbb9f0-cf11-11e5-9fe4-d99ad8af8bc8.png)
![simulator screen shot feb 9 2016 10 36 23](https://cloud.githubusercontent.com/assets/16933227/12909314/01328c50-cf11-11e5-82ec-8bdea91a4ac5.png)

**Comment by robertjpayne** [comment]
Ahh @NVAT so you want the first label to "compact" but the second label to never compact?

**Comment by NVAT** [comment]
Yes

**Comment by NVAT** [comment]
Hello @robertjpayne Its a problem to make layout,the first label compact and second fixed?

**Comment by JockHai** [comment]
try this:
docNumber.snp.makeConstraints { (make) in
            make.right.equalTo(self.view).offset(-15)
            make.top.equalTo(self.view).offset(15)
        }
        
        docTitle.snp.makeConstraints { make in
            make.top.equalTo(docNumber.snp.top)
            make.left.equalTo(self.view).offset(15)
            make.right.equalTo(docNumber.snp.left).offset(-15)
        }
