### ISSUE TITLE
It doesn't work on my phone

### ISSUE THREAD

**Issue by Winter-Yang** [SnapKit/SnapKit#202]
Hey guys，It doesn't work on my iPhone，but it can work on the simulator。
For Error：
dyld: Library not loaded: @rpath/SnapKit.framework/SnapKit
  Referenced from: /var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/SnapKit Samples
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit'
	/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit'
	/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/7439A09A-5943-4DF9-9F95-BAA8D7587FBC/SnapKit Samples.app/Frameworks/SnapKit.framework/SnapKit'
(lldb) 

How can I solve this problem？
Thanks

**Comment by robertjpayne** [comment]
@Winter-Yang this is an integration problem, most likely the Framework is not being copied into your app bundle and can be solved via Carthage's instructions (if you're using Carthage) or by putting the framework in "Embedded Frameworks"
