### ISSUE TITLE
Error constraining multiple edges to multiple margins

### ISSUE THREAD

**Issue by maxmeyers** [SnapKit/SnapKit#205]
### New Issue Checklist

- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)

##### Platform

* [ ] OS X
* [x] iOS

##### Versions

* Platform version is: `iOS 9.2`
* SnapKit version is: `0.19.1`

##### Integration

- [x] Carthage
- [ ] Cocoapods
- [ ] Manually / Other

### Issue

I have a simple situation -- I'm adding a button to a `UITableViewCell`'s `contentView`.

```swift
contentView.layoutMargins = UIEdgeInsets(top: 20, left: 45, bottom: 20, right: 45)

contentView.addSubview(button)
button.snp_makeConstraints { (make) -> Void in
    make.edges.equalTo(contentView.snp_margins)
}
```

This causes the following exception:
`'Invalid Constraint', reason: 'Cannot constrain to multiple non identical attributes'`

However, doing each edge manually works correctly:

```swift
button.snp_makeConstraints { (make) -> Void in
    make.top.equalTo(contentView.snp_topMargin)
    make.bottom.equalTo(contentView.snp_bottomMargin)
    make.left.equalTo(contentView.snp_leftMargin)
    make.right.equalTo(contentView.snp_rightMargin)
}
```

It seems like the comparison [here](https://github.com/SnapKit/SnapKit/blob/61b40162029939ed99d23affab183ad064ad71cf/Source/ConstraintDescription.swift#L547) is a bit too restrictive. Shouldn't multiple non-identical attributes be allowed in a situation like this one?

**Comment by robertjpayne** [comment]
@maxmeyers yea it's probably best if we open this up so edges works to margins.

**Comment by robertjpayne** [comment]
@maxmeyers I've added this to `feature/0.40.0` branch with Swift 3.0. Unfortunately I wont be able to backport this so until you upgrade to Swift 3.0 you'll be without this feature.

Thanks again for filing the report!
