### ISSUE TITLE
Use of undeclared type 'Constraint'

### ISSUE THREAD

**Issue by peiweichen** [SnapKit/SnapKit#206]
### New Issue Checklist

- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)

**Xcode 7.2.1 
 Swift 2.0 
 pod 'SnapKit', '~> 0.19.1'
iOS 9.2**

**snp_makeConstraints works well all the time** , but today when i comes to type Constraint , compilers omit "Use of undeclared type 'Constraint'" , appreciate your help!
```
    var constraintWidth:Constraint? **_//Use of undeclared type 'Constraint'_**

    var constraintHeight:Constraint?
    var topConstraint: Constraint?
    
    func show(inView view:UIView! ,relativeView:UIView!) {
        view .addSubview(self)
      
        self.snp_makeConstraints { (make) -> Void in
            constraintWidth = make.width.equalTo(10)
            constraintHeight = make.height.equalTo(20)
            make.bottom.equalTo(relativeView.snp_top).offset(-20)
            make.centerX.equalTo(relativeView)
        }
```

**Comment by nakiostudio** [comment]
Hi :wave: excuse me if this is a silly comment but, are you importing SnapKit in that class? Sometimes may result confusing that the UIView category is always available, but to use SnapKit objects like Constraint an import is required.

**Comment by peiweichen** [comment]
@nakiostudio the issue is if I  `import SnapKit` ,Xcode complains no such module "SnapKit"

**Comment by peiweichen** [comment]
> Sometimes may result confusing that the UIView category is always available
That's to the point.

`import SnapKit
`fix the issue . Xcode cannot automatically give a hint when i input `import Sna` which puzzled me
