### ISSUE TITLE
value of type 'UIView' has no member 'snp_makeConstraints'

### ISSUE THREAD

**Issue by AniOSDeveloper** [SnapKit/SnapKit#208]
### New Issue Checklist

- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)

##### Platform

* [ ] OS X
* [x] iOS

##### Versions

* Platform version is: `iOS 7`
* SnapKit version is: `0.19.1 / Master branch`

##### Integration

- [ ] Carthage
- [ ] Cocoapods
- [x] Manually / Other

### Issue
I just want the App to support iOS7. After reading [Legacy Platforms](http://snapkit.io/legacy-platforms/) I followed the guide to integrated the SnapKit source code to the project, but the Xcode said "value of type 'UIView' has no member 'snp_makeConstraints' ". I have uploaded the [sample project](https://github.com/AniOSDeveloper/Example.git).
Could anyone help me fix the issue?

**Comment by robertjpayne** [comment]
@AniOSDeveloper you need to add the `sources` as a 'Group' rather than 'Folder Reference'. It should appear as a yellowish icon in the project navigator rather than blue.

**Comment by AniOSDeveloper** [comment]
It works! Thanks very much!
