### ISSUE TITLE
[FEATURE] Add constraint identifiers as an option during ConstraintMaker finalization.

### ISSUE THREAD

**Issue by rohan-panchal** [SnapKit/SnapKit#210]
### New Issue Checklist

- [X] I have looked at the [Documentation](http://snapkit.io/docs)
- [X] I have read the [F.A.Q.](http://snapkit.io/faq)

##### Platform

* [X] OS X
* [X] iOS

##### Versions

* Platform version is: `iOS 9.0`
* SnapKit version is: `0.19.1`

##### Integration

- [ ] Carthage
- [X] Cocoapods
- [ ] Manually / Other

### Issue

Having identifiers on constraints allows for easier debugging when constraints are broken:

http://useyourloaf.com/blog/using-identifiers-to-debug-autolayout/

I was hoping for a solution to add identifiers to each constraint. as part of the ConstraintMaker syntax.

My thought was to add a method:

    `func identifiedAs(string: String) -> ConstraintDescriptionFinalizable`

to `ConstraintDescriptionFinalizable`

as well as a variable to `ConstraintDescription` leaving it optional, and adding the actual setting of the NSLayoutConstraint property in `installOnView`.

If thats ok with you i can make a pull request as soon as I'm done testing it.

**Comment by robertjpayne** [comment]
:+1: Sounds good to me!
