### ISSUE TITLE
animation Issue

### ISSUE THREAD

**Issue by remirobert** [SnapKit/SnapKit#213]
### New Issue Checklist

- [o] I have looked at the [Documentation](http://snapkit.io/docs)
- [o] I have read the [F.A.Q.](http://snapkit.io/faq)

### Environment / Configuration

Xcode 7.3
iOS 9

##### Platform

* [ ] OS X
* [o] iOS

##### Versions

* Platform version is: `9.3`
* SnapKit version is: `0.19.1`

##### Integration

- [ ] Carthage
- [o] Cocoapods
- [ ] Manually / Other

### Issue

It seems impossible to make an animation, by updating the constraint.
This is an example of my code : 

```swift
    override func viewDidAppear(animated: Bool) {
        self.borderTop.setNeedsUpdateConstraints()
        self.borderBottom.setNeedsUpdateConstraints()

        self.heightTopConstraint?.updateOffset(10)
        self.heightBottomConstraint?.updateOffset(10)

        UIView.animateWithDuration(10) {
            self.borderTop.layoutIfNeeded()
            self.borderBottom.layoutIfNeeded()
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = UIColor.blackColor()
        
        self.view.addSubview(self.borderTop)
        self.borderTop.snp_makeConstraints { (make) in
            make.width.equalTo(self.view)
            self.heightTopConstraint = make.height.equalTo(CGRectGetHeight(UIScreen.mainScreen().bounds) / 2).constraint
            make.top.equalTo(0)
        }
        
        self.view.addSubview(self.borderBottom)
        self.borderBottom.snp_makeConstraints { (make) in
            make.width.equalTo(self.view)
            self.heightTopConstraint = make.height.equalTo(CGRectGetHeight(UIScreen.mainScreen().bounds) / 2).constraint
            make.bottom.equalTo(0)
        }
    }
```
I switched back to **Masonry**, because It supports animation.
What about **SnapKit**, is it a bug ?

Thanks in advance. :+1:

**Comment by robertjpayne** [comment]
@remirobert probably all you need to do is call `self.view.layoutIfNeeded()` inside the animation block rather than the other two views. Because constraints are added on a view's superview you almost always need to do a layoutIfNeeded on the UIViewController's view.

**Comment by robertjpayne** [comment]
If that doesn't resolve it please re-open but I'm like 99.9% positive.

**Comment by remirobert** [comment]
ha !!!!! I knew that. That's my mistake !! Thanks a lot.

You fixed it ! :+1: :fireworks:
