### ISSUE TITLE
Cannot access class "Constraint"

### ISSUE THREAD

**Issue by harit** [SnapKit/SnapKit#219]
### New Issue Checklist

* I have looked at the [Documentation](http://snapkit.io/docs): `INSERT yes/no`
Yes

* I have read the [F.A.Q.](http://snapkit.io/faq): `INSERT yes/no`
Yes

* Platform is: `INSERT iOS/OSX/tvOS`
iOS

* Platform version is: `INSERT PLATFORM VERSION`
9.1

* SnapKit version is: `INSERT SNAPKIT VERSION`
0.19.1

* Integration method is: `INSERT carthage/cocoapods/manually/other`
CocoaPods

### Issue

`INSERT ISSUE DESCRIPTION`
I want to preserve constraint on a var using:
`self.snp_makeConstraints { (make) -> Void in
            self.heightConstraint = make.height.equalTo(100).constraint
        }`

However, for declaration, if I declare as:
`    var heightConstraint:Constraint? = nil
`

It gives error of undeclared type 'Constraint'
The Constraint class is also declared as public.

**Comment by robertjpayne** [comment]
@harit just to double/triple check you do have an `import SnapKit` at the top of your Swift file yes? Sometimes you can access extensions w/o an import but as soon as you reference class types you need the import.

**Comment by harit** [comment]
@robertjpayne Oh right. Good catch. My project is compilable after I declare import SnapKit.
Please discard this issue.

Thanks a ton!
