### ISSUE TITLE
Error "Build Failed" occurred while installing SnapKit via Carthage

### ISSUE THREAD

**Issue by scienartist** [SnapKit/SnapKit#221]
Cartfile: 
`github "SnapKit/SnapKit" >= 0.20.0`

After running `carthage bootstrap`:
`*** Checking out SnapKit at "0.20.0"
*** xcodebuild output can be found in /var/folders/qs/v5kp69v52_g0tkv1zpwnywkh0000gn/T/carthage-xcodebuild.68Ae6J.log
*** Building scheme "SnapKit OSX" in SnapKit.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/Constraint.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/SnapKit.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/Debugging.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/ConstraintRelation.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/ConstraintDescription.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/EdgeInsets.swift
	CompileSwift normal x86_64 ./Carthage/Checkouts/SnapKit/Source/ConstraintMaker.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:131:81: error: use of unresolved identifier 'line'
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:140:71: error: use of unresolved identifier 'line'
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:151:73: error: use of unresolved identifier 'line'
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:160:73: error: use of unresolved identifier 'line'
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:55: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:130:82: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:52: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:139:79: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:150:81: error: expected ',' separator
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:54: error: expected initial value after '='
./Carthage/Checkouts/SnapKit/Source/View+SnapKit.swift:159:81: error: expected ',' separator
A shell task failed with exit code 65:
** BUILD FAILED **`

. is the directory that the project locates in.

**Comment by robertjpayne** [comment]
@scienartist please re-open a new issue and fill out the entire issue template regarding Xcode/System versions.
