### ISSUE TITLE
Specs satisfying the `SnapKit (= 0.15.0)` dependency were found, but they required a higher minimum deployment target. iOS7 how to resolve it

### ISSUE THREAD

**Issue by JZJJZJ** [SnapKit/SnapKit#223]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually

**Comment by robertjpayne** [comment]
@JZJJZJ please fill out the issue template in its entirety before submitting bug reports.

As per iOS 7 support your answer is in the FAQ and Documentation under 'Legacy Platforms'
