### ISSUE TITLE
Build failed occurred while installing SnapKit via Cocoapods

### ISSUE THREAD

**Issue by tiagobarreto** [SnapKit/SnapKit#224]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 9.2
 SnapKit Version         | 0.20.0
 Xcode Version      | 7.3
 Integration Method      | cocoapods

### Issue Description

**POD FILE**
platform :ios, '8.0'

use_frameworks!

target 'spotfoot' do
pod 'SnapKit', '~> 0.15.0'
end

**BUILD FAILED**

The following build commands failed (8 issues):

/Pods/SnapKit/Source/View+SnapKit.swift:130:55: Expected initial value after '='
/Pods/SnapKit/Source/View+SnapKit.swift:130:82: Expected ',' separator
/Pods/SnapKit/Source/View+SnapKit.swift:139:52: Expected initial value after '='
/Pods/SnapKit/Source/View+SnapKit.swift:139:79: Expected ',' separator
/Pods/SnapKit/Source/View+SnapKit.swift:150:54: Expected initial value after '='
/Pods/SnapKit/Source/View+SnapKit.swift:150:81: Expected ',' separator
/Pods/SnapKit/Source/View+SnapKit.swift:159:54: Expected initial value after '='
/Pods/SnapKit/Source/View+SnapKit.swift:159:81: Expected ',' separator

**Comment by robertjpayne** [comment]
@tiagobarreto can you post up your full Podfile and build log? Also what version of Xcode are you using?

**Comment by tiagobarreto** [comment]
@robertjpayne issue updated, missing complete build log.

**Comment by robertjpayne** [comment]
@tiagobarreto can you try and pin SnapKit to `~> '0.20.0'` and see if that resolves it? My guess is Swift incompatibility.

**Comment by tiagobarreto** [comment]
@robertjpayne I've already tried but it is the same problem using pod 'SnapKit' without version.

**Comment by robertjpayne** [comment]
@tiagobarreto all the errors are pointing towards:

`public func snp_prepareConstraints(file: String = #file, line: UInt = #line, @noescape closure: (make: ConstraintMaker) -> Void) -> [Constraint] {`

Swift 2.2 (Xcode 7.3) added these `#file` and `#line` macros so I'm most suspicious about that. I can't really say otherwise without a full working project example.

**Comment by tiagobarreto** [comment]
@robertjpayne So, later I will to add complete build log. Thanks ;)

**Comment by robertjpayne** [comment]
@tiagobarreto ok, feel free to email it to me too robert payne [at] me [dot] com if you'd rather.

**Comment by tiagobarreto** [comment]
@robertjpayne oh, thanks!

**Comment by robertjpayne** [comment]
Closing this, please re-open if you continue to believe that SnapKit has a bug.

**Comment by vroomvsr** [comment]
I had the exact same problem as tiagobarreto. 

Here is my project: https://github.com/vroomvsr/SnapKit-Error

Was the solution ever found?
