### ISSUE TITLE
SnapKit Performance on presented view

### ISSUE THREAD

**Issue by netgfx** [SnapKit/SnapKit#229]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 8.0+
 SnapKit Version         | 0.19.0
 Integration Method      | carthage
 

### Issue Description
I'm creating a new view and have the constrains of all the UI elements on a function that is called on the viewDidLoad function. 
The view is presented via the following code, the time it takes to show the view the fist time is over 5-6 seconds which is quite a lot.

```Swift
let storyboard = UIStoryboard(name: "Main", bundle: nil)
let controller = storyboard.instantiateViewControllerWithIdentifier("newView") as! NewView
self.presentViewController(controller, animated: true, completion: nil)
```

The constrain declarations are approximately over 20 mostly UILabel, UIButton, UIView elements.

Is there a way to speed the first load of the presented view? Or is there a better way or place to declare constrains?

Thanks in advance!

**Comment by robertjpayne** [comment]
@netgfx have you profiled your app at all? I doubt this will be SnapKit and much more likely to be just UIKit and general auto layout performance. Are you also running in release mode?

**Comment by netgfx** [comment]
Basically I have removed all constrain declarations and the view seems to load faster. No I'm not running the app on release mode.

**Comment by robertjpayne** [comment]
@netgfx have you created the constraints with regular UIKit API's? AutoLayout isn't a free thing it does have measurable performance impacts.

Also are you running under release or debug mode? Swift runs significantly slower under Debug than Release builds due to the optimiser.

**Comment by netgfx** [comment]
I'm adding constrains this way:
```
self.loadingView = UIView()
        self.loadingView.hidden = true
        self.loadingView.backgroundColor = Styles.whiteSemiLessTransparentColor
        superview.addSubview(self.loadingView)
        
        self.loadingView.snp_makeConstraints{ (make) -> Void in
            make.width.equalTo(superview.snp_width)
            make.height.equalTo(superview.snp_height)
        }
```

I'm running on debug mode, on release things are a bit faster but not ideal.

**Comment by robertjpayne** [comment]
@netgfx Cool, at this point you still haven't provided any evidence this is SnapKit's fault over UIKit's auto layout engine.

SnapKit is just a helper library to make creating and activating NSLayoutConstraint's easier.

Can you try to use NSLayoutConstraint's API and see if it's drastically faster or use Instruments time profiler and provide a trace?

**Comment by netgfx** [comment]
I see I will try and get some readings here. So if indeed the delay is due to the UIKit autolayout or NSLayoutConstraint's API. Is there some way to decrease this delay? 

Like adding the constrains with some delay asynchronously maybe?

**Comment by robertjpayne** [comment]
@netgfx really depends why it's happening, sometimes the constraint system just lags, it's a bit of a black box.

**Comment by robertjpayne** [comment]
@netgfx closing this as I believe it's resolved, if you have evidence that SnapKit is at fault here please feel free to re-open or open a new issue.

**Comment by netgfx** [comment]
Sure thing I believe it was a debug mode issue as on Release it behaves as expected. Thanks for the help.
