### ISSUE TITLE
Linking against dylib not safe for use in application extensions on iOS

### ISSUE THREAD

**Issue by hectormatos2011** [SnapKit/SnapKit#230]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 8.3
 SnapKit Version         | 0.19.1
 Integration Method      | carthage
 

### Issue Description
After creating a Today Extension in my existing project, I installed SnapKit through Carthage and ran my tests, project, and today extension. This warning pops up.

**Comment by robertjpayne** [comment]
@hectormatos2011 please use the latest version of SnapKit 0.21.0 as this is resolved I believe.

**Comment by hectormatos2011** [comment]
Oh great! Thank you!
