### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Cannot modify constraints for UINavigationBar managed by a controller' #309 

### ISSUE THREAD

**Issue by YHSX88** [SnapKit/SnapKit#233]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        |  8.0
 SnapKit Version         | 0.15.0
 Integration Method      | cocoapods
 

### Issue Description
This issue is similar to  [#309](https://github.com/SnapKit/Masonry/issues/309) from the library wriiten in Obj-C, but this time the same problem is here.

I have one view which is added as subview to navigation bar. 
When I go to the view(initial screen where the nav bar is showing) all good, 
then i'm going to second view(using the navigation controller ) all good, 
but then when I try to go back to the initial view where this code is written:
```
navLabel.snp_makeConstraints{(make) -> Void in
            make.center.equalTo((self.navigationController?.navigationBar)!)
        }
```

I'm getting the error mentioned in the title.
Here is a [link](https://github.com/SnapKit/Masonry/issues/309) to the issue that was mentioned previously but I can't understand how to fix this in swift.

So can someone help with this issue please ?
Thanks in advance !!!

**Comment by robertjpayne** [comment]
@YHSX88 is this `snp_makeConstraints` done on the `viewDidLoad` or `viewWillAppear`? Make sure you're using `snp_remakeConstraints` if you're doing it in `viewWillAppear`

Also does it exhibit the bug on iOS9?

**Comment by YHSX88** [comment]
Hi 

So initially the code was in viewWillAppear then i move it to viewDidLoad and then it was no working.
Then I wrote about this issue here.

Now I tried to move it back to viewWillAppear and i used **snp_remakeConstraints** but still not working i.e. crashing.

Bear in mind that i'm using simulator and iPhone 6S (9.3.2)

![screen shot 2016-05-18 at 20 14 24](https://cloud.githubusercontent.com/assets/16823745/15368255/8d6a988a-1d35-11e6-9414-55148f07a71f.png)

**Comment by robertjpayne** [comment]
@YHSX88 can you upgrade to `0.21.0` and try? There may be some fixes that affect it.

**Comment by YHSX88** [comment]
Hi 

I've upgrated to 0.21.0 and I can confirm it is working now.

for others that may see this issue, I have:
```
navLabel.snp_remakeConstraints{(make) -> Void in
            make.center.equalTo((self.navigationController?.navigationBar)!)
        }
```
where navLabel is a **UIVIew** which is as subview. The code above is currently located in **ViewDidLoad**

Thank You
