### ISSUE TITLE
Referencing constraint constant value

### ISSUE THREAD

**Issue by adampitchie** [SnapKit/SnapKit#235]
I can't find it in the documentation, but is there a way to get a reference to the current size constraint? For instance, I'm using a lazily instantiated object, and I'm unable to reference a constant value for the height or width, as self.frame.size.height doesn't reflect the value.

Any ideas?

**Comment by robertjpayne** [comment]
@adampitchie there isn't currently, The hard part is that our "Constraint" objects may represent more than 1 NSLayoutConstraint so the constant isn't necessarily for a single constraint, also given our inset vs offset it may also not be the same as the input.

Are you trying to use it for say animation?

**Comment by robertjpayne** [comment]
@adampitchie any update on this?

**Comment by adampitchie** [comment]
Sorry for the late reply. Yes it's for animation. The problem is I have a setup chain (addSubview, constraints, etc) that decouples the constraints code out of the viewDidLoad method, so I'm going to just need to keep a global reference somewhere.

**Comment by ChanchalW** [comment]
Hi, I want to get current constant value from constraint. How to achieve this ??
