### ISSUE TITLE
Multiple views layout

### ISSUE THREAD

**Issue by reeichert** [SnapKit/SnapKit#237]
Hi, this is possible in future versions of snapkit??

```swift
[box1, box2, box3].snp_makeConstraints { [make] in
           make[0].left.right.top.equalTo(0)
           make[0].height.equalTo(50)
           make[1].width.height.equalTo(50)
           make[1].top.equalTo(make[0].snp_bottom).offset(16)
......
        }
```

I'll be glad to hear any feedback on this.

**Comment by robertjpayne** [comment]
@reeichert unfortunately at the moment it's not. We'd prefer to wait until Swift allows extensions of Generic types like Array/Dictionary with typing information.

Such as:

```
extension Array where T: UIView {
}
```

It's coming in Swift 3.0. For now you'd need to manually loop them or if you make a generic sequence extension you could do something like `views.each { $0.snp_makeConstraints { } }`

**Comment by chunxige** [comment]
but still not support now,
