### ISSUE TITLE
I can't use it~ 

### ISSUE THREAD

**Issue by Gantios** [SnapKit/SnapKit#238]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

    /**
        Prepares constraints with a `ConstraintMaker` and returns the made constraints but does not install them.

        - parameter closure that will be passed the `ConstraintMaker` to make the constraints with
        
        - returns: the constraints made
    */
    public func snp_prepareConstraints(file: String = #file, line: UInt = #line, @noescape closure: (make: ConstraintMaker) -> Void) -> [Constraint] {
        return ConstraintMaker.prepareConstraints(view: self, file: file, line: line, closure: closure)
    }
    

SnapKit/View+SnapKit.swift:139:52: Expected initial value after '='
SnapKit/View+SnapKit.swift:139:79: Expected ',' separator

![Uploading C27A0478-D558-4353-B932-0FCA8ABFF539.png…]()

**Comment by colinta** [comment]
@Gantios What version of XCode are you using?  That code snippet was written for Swift 2.2, which requires Xcode 7.3.

**Comment by Gantios** [comment]
@colinta  Thanks!

**Comment by robertjpayne** [comment]
@colinta 👍
