### ISSUE TITLE
Building error when having constrain on tableview after installing version  0.30.0.beta1

### ISSUE THREAD

**Issue by NewBieQing** [SnapKit/SnapKit#239]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios / xcode
 Platform Version        | ios:9.2 / xcode 7.3.1
 SnapKit Version         |  0.30.0.beta1
 Integration Method      | cocoapods
 

### Issue Description

**In order to avoid memory leak, i update snapkit to version 0.30.0.beta1，but when i building the project, Xcode remind me some building mistakes as following:**
<pre> Undefined symbols for architecture arm64:
"protocol witness table for SnapKit.ConstraintItem : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
   XXX.UserViewController.(setupUI () -> ()).(closure #4) in UserViewController.o
"SnapKit.ConstraintViewDSL.bottomMargin.getter : SnapKit.ConstraintItem", referenced from:
   XXX.UserViewController.(setupUI () -> ()).(closure #4) in UserViewController.o
<p>"SnapKit.ConstraintViewDSL.makeConstraints (closure : (make : SnapKit.ConstraintMaker) -> ()) -> ()", referenced from:
   XXX.UserViewController.setupUI** () -> () in UserViewController.o</p></pre>
**The related code in UserViewController is:**
<pre>tableview.snp.makeConstraints(closure: {make in
                  make.top.equalTo(headerView.snp.bottomMargin)
                  make.right.equalTo(self.view)
                  make.left.equalTo(self.view)
                  make.bottom.equalTo(self.view)
 })</pre>

**Comment by robertjpayne** [comment]
@NewBieQing can you fill out the checklist table? E.g. what version of iOS/Xcode and how you are integrating?

**Comment by NewBieQing** [comment]
OK! I have filled out the checklist table:

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios 9.2
 Platform Version        | xcode 7.3.1
 SnapKit Version         |  0.30.0.beta1
 Integration Method      | cocoapods

**Comment by robertjpayne** [comment]
@NewBieQing cool, well all looks normal. Just a few things:

1. Are you using `import SnapKit` at the top of the file?
2. Have you cleaned project and/or quit/restarted Xcode?
3. Have you cleared your DerivedData folder?

Generally speaking arch errors like that are due to integration or a bugged cache somewhere, Especially with Swift code we can't really differentiate 32 vs 64 bit platforms.

**Comment by NewBieQing** [comment]
Oh,i have been a long time to clear my DerivedData folder , the problem has been resolved after i clean it up. 
**Thanks for reminding me!**
