### ISSUE TITLE
Getting at `LayoutConstraint`

### ISSUE THREAD

**Issue by startupthekid** [SnapKit/SnapKit#241]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 9.0
 SnapKit Version         | e.g. 0.21.0
 Integration Method      | e.g. cocoapods
 

### Issue Description

Snapkit has a public class, `LayoutConstraint` which inherits from `NSLayoutConstraint` but there's no way to actually get an instance of `LayoutConstraint`. All the methods return `Constraint`. This becomes a problem when using libraries like Facebook's `pop` animation library because animations on constraints are applied directly to the constraint, as `constraint.pop_addAnimation` where constraint is a subclass of `NSLayoutConstraint`.

How can I get at `LayoutConstraint`?

**Comment by robertjpayne** [comment]
@startupthekid this is intentional because SnapKit constraints are rarely a 1:1 relation to a LayoutConstraint.

In these cases I recommend people use the standard iOS API's to create the small subset of constraints needed to use with other frameworks/libraries.

**Comment by colinta** [comment]
Is there any chance this can have more discussion?  You say "rarely a 1:1 relation", but I'm not sure this is true, it seems like SnapKit's DSL encourages the `top/left/right/bottom` constraints, which DO lend themselves to this "native access".  The other cases are center & size (1:2) and edges (1:4), which are easy to spot.

I would ask this: is there ever a time when you *might* get 1 constraint, or *might* get >1 constraints back? e.g. aren't the `make.foo` helpers always deterministic WRT how many constraints are created?

My use case is that I need the `NSLayoutConstraint` object that is created by `make.top.equalTo(view)` (to show/hide the nav bar via slide in/out animation).  Ideally I would accomplish this by:

```
navigationBar.snp_makeConstraints { make in
  make.left.equalTo(view)
  make.right.equalTo(view)
  let c = make.top.equalTo(view)
  self.navigationBarTopConstraint = c.nativeConstraints.first!
```

What you're recommending looks something like this, if I understand correctly:

```
navigationBar.snp_makeConstraints { make in
  make.left.equalTo(view)
  make.right.equalTo(view)
  let c = NSLayoutConstraint(bah,
    this: darn,
    mess: which,
    goes: on,
    forever: true)
  // I don't even remember what to do with it
```

Whaddya say, would you be open to a PR that exposes `installInfo.allObjects`?

**Comment by robertjpayne** [comment]
@colinta your syntax could easily be `make.top.left.right.equalTo(view)` or `make.edges.equalTo(view)` etc…

I'd really rather not expose the constraints to ensure that it's not thought they should be used. Then we have exposure to the SnapKit constraint objects which allow updating and exposure to the raw underlying constraints which really should not be updated.

Is there a reason why you can't use the `let c = make.top.equalTo(view).constraint` and `c.update*` API's already provided to accomplish what you need?

**Comment by colinta** [comment]
There is - I'm passing these constraints to a part of the internal API that uses NSLayoutConstraibt objects, and I don't have access to change it. 

It sounds like you consider a "black box", whereas I think of it as a "thin wrapper", and as a wrapper it only *makes sense* to expose the thing that is being wrapped.

**Comment by robertjpayne** [comment]
@colinta I take into consideration the amount of issues that will be opened if I give people the raw constraints!

> to a part of the internal API that uses NSLayoutConstraint objects

Is this internal to your project's code base or UIKit?

**Comment by colinta** [comment]
Sounds like you're intent on this, it also sounds to me like a case of "playing dad" to programmers who might do the wrong thing; but on the other hand, I see your point about a likelihood of more issues.

I'll maintain the fork for now - I think a note on #242 that explains your stance and closes the PR would be appropriate.

**Comment by colinta** [comment]
(I don't mean to sound judgmental - it's a tough call! D*mned if you do, d*mned if you don't)

**Comment by robertjpayne** [comment]
@colinta I'd say you're the first that has asked for this, and it is sort of a big ask. I do totally understand the desire to get at the constraints.

In your case, would it be adequate if you could use SnapKit to create an "Unmanaged" "Uninstalled" NSLayoutConstraint? I'm much more keen to provide an API that generates underlying ready to use NSLayoutConstraint's than give access to the ones that SnapKit is managing internally.

Something like

`make.top.equalTo(other).unmanaged -> NSLayoutConstraint`

**Comment by colinta** [comment]
I like the `unmanaged` name instead of `nativeConstraints`.  I would think that it should still return an array, so that it can be generic. Looking at PR #242 I think it would be as simple as renaming `nativeConstraints` to `unmanagedConstraints`, but why not install the constraints?  My PR actually *relies* on having them installed (it gets the `LayoutConstraint` objects out of `installInfo`), so I'm not sure what direction to go in if that was going to be avoided.
