### ISSUE TITLE
Completely broken for iOS10

### ISSUE THREAD

**Issue by RichAppz** [SnapKit/SnapKit#244]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually

**Comment by robertjpayne** [comment]
@RichAppz please open an issue with appropriate description and error report. What's broken on iOS 10?
