### ISSUE TITLE
Is SnapKit 0.15.0 doesn't support iOS 7? which version supports iOS 7?

### ISSUE THREAD

**Issue by rajeev2iOS** [SnapKit/SnapKit#246]
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SnapKit (~> 0.15.0)` required by `Podfile`

Specs satisfying the `SnapKit (~> 0.15.0)` dependency were found, but they required a higher minimum deployment target.
```

while installing the pods this is the usual message i get. I tried with lower versions upto 0.10.0, same error I got with all the versions. The Requirements mentioned in snapkit includes iOS 7+.

**Comment by robertjpayne** [comment]
@rajeev2iOS please do not open issues without filling out the issue checklist. If you read the FAQ it has clear instructions on how to integrate with iOS 7.0 explicitly stating it does not work with Cocoapods.
