### ISSUE TITLE
大神你好!! 什么时候会把 Masonry中的全部功能都添加到SnapKit 中呢??

### ISSUE THREAD

**Issue by jeson251** [SnapKit/SnapKit#247]
大神你好!! 什么时候会把 Masonry中的全部功能都添加到SnapKit 中呢??

**Comment by robertjpayne** [comment]
@jeson251 sorry, can you please open another ticket in English? Thanks!

**Comment by kaicodedocument** [comment]
@jeson251 he mean: "When will all features in masonry will be added to SnapKit?"

**Comment by kaicodedocument** [comment]
@robertjpayne as the comment
