### ISSUE TITLE
Hello, may I ask when you will put all the features of Masonry are added to the SnapKit?

### ISSUE THREAD

**Issue by jeson251** [SnapKit/SnapKit#248]
Hello, may I ask when you will put all the features of Masonry are added to the SnapKit?

**Comment by sp-wisebits** [comment]
Can you please elaborate, which features from Masonry do you think are missing in SnapKit?

**Comment by robertjpayne** [comment]
@jeson251 @sp-wisebits SnapKit is the future going forward, we are happy to accept well formed PR's for Masonry but a lot of the work that is going into SnapKit can *only* be done in Swift.

The team is pretty much just me anymore and I don't have enough free time to maintain both on a total feature parity level. Masonry at this point is pretty stable and works pretty well I think.

**Comment by jeson251** [comment]
@robertjpayne Thank you!

**Comment by jeson251** [comment]
@sp-wisebits  like this
 [@[view1, view2, view3] mas_distributeViewsAlongAxis:MASAxisTypeHorizontal withFixedSpacing:25 leadSpacing:16 tailSpacing:16];

 [@[view1, view2, view3] mas_makeConstraints:^(MASConstraintMaker *make) {
    }];
