### ISSUE TITLE
RemakeConstraint is not working as expected in snapkit new version when installed using cocoa pods

### ISSUE THREAD

**Issue by Yalqun** [SnapKit/SnapKit#250]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 9.0
 SnapKit Version         | 0.30.0.beta1
 Integration Method      | cocoapods
 

### Issue Description
remake constraint not working as expected
below is fuction stack:
    public func remakeConstraints(@noescape closure closure: (make: ConstraintMaker) -> Void) {
        ConstraintMaker.remakeConstraints(view: self.view, closure: closure)
    }
    internal static func remakeConstraints(view view: ConstraintView, @noescape closure: (make: ConstraintMaker) -> Void) {
        self.removeConstraints(view: view)
        self.makeConstraints(view: view, closure: closure)
    }
    internal static func removeConstraints(view view: ConstraintView) {
    }

removeConstraints is not doing anything. please check

**Comment by robertjpayne** [comment]
@Yalqun this was a known bug, can you upgrade to 0.30.0.beta2 please?

**Comment by kaicodedocument** [comment]
update the new version everything is fine @Yalqun

**Comment by robertjpayne** [comment]
I just fixed this in `feature/0.40.0` but not yet tagged a version. It was an issue I can confirm
