### ISSUE TITLE
View not reflecting updated constraints when calling layoutIfNeeded

### ISSUE THREAD

**Issue by johnryan** [SnapKit/SnapKit#254]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | e.g. 9.3
 SnapKit Version         | e.g. 0.21.1
 Integration Method      | e.g. cocoapods
 

### Issue Description
I am having trouble updating constraints on a label in a table cell. I have code like this:

```
 titleLabel.snp_makeConstraints(closure: { (make) in
            make.top.equalTo(parent).offset(10)
            make.left.equalTo(0).offset(12)
            make.right.equalTo(parent).offset(-10)
            self.heightConstraint = make.height.lessThanOrEqualTo(100).constraint
        })
```

when the row is selected i want to toggle on/off the height constraint so that the titleLabel expands to its full height:

```
  private var expanded = false {
        didSet {
            if expanded {
                self.heightConstraint?.uninstall()
            } else {
                self.heightConstraint?.install()
            }
            
            self.titleLabel.setNeedsLayout()
            self.titleLabel.layoutIfNeeded()
            
        }
    }
```

However, nothing happens when layout if needed is called. If i scroll the table around so that the cell gets redrawn it pops into its correct height so the constraints are being set correctly, the view just isn't updated correctly. 

I've tried calling setNeedsLayout/layoutIfNeeded on the parent views and on the cell but it seems to have no effect.

**Comment by johnryan** [comment]
Realized the issue for anyone who has this issue in the future, needed to call beginUpdates/endUpdates on the tableview when adjusting the row

**Comment by kaicodedocument** [comment]
@johnryan when you used  `self.heightConstraint?.uninstall()` method before the `self.heightConstraint?.install()` , actively the `self.heightConstraint` status is deactive, even if you call `install()` it will nothing happens, so you need call  `self.heightConstraint?.active()` and use `self.heightConstraint?.updateOffSet()` it will be worked. try it
