### ISSUE TITLE
No such module "Snapkit"

### ISSUE THREAD

**Issue by carly1987** [SnapKit/SnapKit#257]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description
pod install 
[!] The dependency `SnapKit (~> 0.15.0)` is not used in any concrete target.

my podfile:
source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
use_frameworks!
pod 'SnapKit','~> 0.15.0'
pod 'DrawerController', '~> 1.1.0'
pod 'ObjectMapper', '~> 1.1.1'
pod 'AlamofireObjectMapper', '~> 2.1.0'
pod 'YYText', '~> 0.9.18'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

and add  "target 'Piece' do" into Podfile, and then 
[!] Invalid Podfile file: syntax error, unexpected end-of-input, expecting keyword_end.
from /Users/cieldon/swift/piece/Podfile:11
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

**Comment by robertjpayne** [comment]
This looks like an issue with another pod preventing the integration from working properly. Please resolve that first and open a new issue if this persists!

**Comment by swiftcode** [comment]
I am getting the same error and SnapKit is the only pod I have installed.  What's peculiar, is it was working yesterday, when I installed it.  Just started getting the error today.
