### ISSUE TITLE
0.40.0 missing ability to set/update priority

### ISSUE THREAD

**Issue by zhouxl** [SnapKit/SnapKit#258]
How can i set the priority on 0.40 branch

**Comment by robertjpayne** [comment]
Still a wip so I probably just missed this, am on leave for another two weeks but have a little time in a few days to check this out.

**Comment by robertjpayne** [comment]
@zhouxl this is now in tag `0.40.0.beta3` I can't release to Cocoapods due to Cocoapods issues.
