### ISSUE TITLE
Inset and offset seem to behave inconsistently

### ISSUE THREAD

**Issue by einsteinx2** [SnapKit/SnapKit#262]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | os x
 Platform Version        | 10.11
 SnapKit Version         | 0.21.0
 Integration Method      | carthage
 

### Issue Description

I can't seem to figure out how inset and offset are supposed to be used. It seems like depending on the constraint they act differently. Sorry I don't have exact examples right now, but in general I've had issues like:

1. Inset and offset doing the same thing on some constraints, but the opposite on others
2. Sometimes needing to use a negative number to get the expected behavior, sometimes not depending on constraint

My thinking was that inset moved things inside while offset moves things outside. But it seems like for some constraints like top IIRC, I have to use offset to move the view down, rather than inset, and other nonintuitive stuff like that.

Maybe I'm just thinking about them incorrectly? I don't see anything in the docs on how exactly they're meant to be used. Could you elaborate on them, and even better, add the info to the documentation? Thanks!

**Comment by robertjpayne** [comment]
@einsteinx2 It is a bit confusing. To give you a bit of reference here:

* `offset` is set as the constant value regardless of the attribute.
* `inset` is set as the constant value, but sometimes inverted depending on the attribute. For instance right/bottom/width/height will be `-(value)`

If this isn't the case please provide an example with what isn't working this way and I'll get it tidied up.

**Comment by shreyash-sharechat** [comment]
I ran into same problem recently; it seems like `inset()` would automatically negate the constant sign if you are working with a view directly but if you are working constraint anchor then inset will behave same as offset, i.e. it will just add the constant to the equation.

```
childView.snp.makeConstraints { make in
    right.equalTo(parentView).inset(10)        /// this is: childView.right = parentView.right - 10
}

/// BUT

siblingView1.snp.makeConstraints { make in
    right.equalTo(siblingView2.snp.left).inset(10)     /// this is: siblingView1.right = siblingView2.left + 10
}
```
