### ISSUE TITLE
NSHashTable has been renamed HashTable in Swift 3

### ISSUE THREAD

**Issue by phrz** [SnapKit/SnapKit#265]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. iOS
 Platform Version        | e.g. 10 Beta 3
 SnapKit Version         | e.g. 0.40.0
 Integration Method      | manual
 

### Issue Description
I am developing in Swift 3, so I manually integrated the code from the 0.40.0 branch, whose apparent purpose is Swift 3 migration. SnapKit fails to compile in Xcode 8.0 beta 3 with its standard Swift 3 toolchain due to use of `NSHashTable` which has been renamed `HashTable`. A simple renaming of all occurrences of the class name appears to fix this issue.

**Comment by robertjpayne** [comment]
@phrz head branch of 0.40.0 has a fix for this in place, will be releasing in a day or two as a new Cocoapod beta.
