### ISSUE TITLE
Swift 3.0 Support 

### ISSUE THREAD

**Issue by siavashalipour** [SnapKit/SnapKit#266]
Hi Guys, thanks for this amazing pod. Quick question, is anyone working on Swift 3.0 support ? if yes is it going to be available with the Xcode 8 official release ?

**Comment by robertjpayne** [comment]
@siavashalipour this is tracking in the `feature/0.40.0` branch. I was on holiday the last 5 weeks so support slacked a bit, but it'll be back on track by end of this week.

**Comment by siavashalipour** [comment]
Thanks for the prompt answer. @robertjpayne

**Comment by jacobjiangwei** [comment]
@robertjpayne  will this feature 0.40 pushed to cocoapod? How to upgrade to corresponding version for swift 3.0?
