### ISSUE TITLE
Won't build with a clean Carthage environment

### ISSUE THREAD

**Issue by diogot** [SnapKit/SnapKit#268]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 8.0 (Xcode 7.3)
 SnapKit Version         | 0.21.1
 Integration Method      | carthage
 

### Issue Description

Fail to generate .framework with the following error:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't move temporary file: /Users/diogo/Library/Developer/Xcode/DerivedData/SnapKit-gtorhfxghcypbyassjigcnhxmrta/Build/Products/Release-iphonesimulator/SnapKit.framework/SnapKit to file: /Users/diogo/Library/Developer/Xcode/DerivedData/SnapKit-gtorhfxghcypbyassjigcnhxmrta/Build/Products/Release-iphonesimulator/SnapKit.framework/SnapKit.lipo (No such file or directory)
```

Steps to reproduce

- Cartfile with line `github "SnapKit/SnapKit" == 0.21.1`
- rm -rf ~/Library/Developer/Xcode/DerivedData/
- rm -rf Carthage/Checkouts/SnapKit/
- carthage bootstrap --platform iOS --no-use-binaries SnapKit

**Comment by robertjpayne** [comment]
@diogot unfortunately this is a Carthage issue not SnapKit. I've seen this crop up from time to time and I never did have a great set of steps to resolve it. 

In my case I typically cleared out the Carthage cache, Xcode derrived data, Xcode modules and deleted/re-installed Xcode from app store along with a system restart in between.

Your luck may vary.
