### ISSUE TITLE
Release Swift 3.0 version to Cocoapods Trunk

### ISSUE THREAD

**Issue by jacobjiangwei** [SnapKit/SnapKit#270]
## How do I use SnapKit with Swift 3.0 and Cocoapods?

Edit your podfile to:

`pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'feature/0.40.0'`

Cocoapods is currently broken for pushing Swift 3.0 specs to the trunk, until that is fixed you will need to pin it to a git branch/tag.

> This issue has been edited by Robert Payne to allow users to find the answer quicker.

**Comment by coderhaoxin** [comment]
```
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'feature/0.40.0'
```

**Comment by robertjpayne** [comment]
@jacobjiangwei hey, @coderhaoxin is correct you need to modify your podfile. Unfortunately I can't get Cocoapods to properly lint and push the 0.40.0 pod.

**Comment by zhanghongdou** [comment]
I use this method （ self label!. SNP. RemakeConstraints (closure: {(make) in ）, after tests ，found that the set of constraints has not been deleted, lead to constraints to repeat, is this why

**Comment by jacobjiangwei** [comment]
@robertjpayne  when will that happen? After release official xcode 8 ios10 swift 3?

**Comment by robertjpayne** [comment]
@jacobjiangwei I have no idea, Cocoapods right now is broken in a fashion I cannot push a build to it, I'll try again this week but overall it's an issue on their end for Pod maintainers.

**Comment by XHJiang** [comment]
@jacobjiangwei how to do it,Please tell me .... if you are a Chinese,My QQ is 917532427...

**Comment by jacobjiangwei** [comment]
Still not doable in a common way

发自我的 iPhone

**Comment by robertjpayne** [comment]
For anyone following this you need to do it via:

`pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'feature/0.40.0'` for Cocoapods.

**Comment by robertjpayne** [comment]
Hey everyone, you can now install via Cocoapods `>= 1.1.0` by adding `'SnapKit', '~> 3.0.0' to your pod file!
