### ISSUE TITLE
I use this method （ self label!. SNP. RemakeConstraints (closure: {(make) in ）, after tests ，found that the set of constraints has not been deleted, lead to constraints to repeat, is this why

### ISSUE THREAD

**Issue by zhanghongdou** [SnapKit/SnapKit#271]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually

**Comment by zhanghongdou** [comment]
I use this method （ self label!. SNP. RemakeConstraints (closure: {(make) in ）, after tests ，found that the set of constraints has not been deleted, lead to constraints to repeat, is this why

**Comment by robertjpayne** [comment]
@zhanghongdou can you please upgrade to `0.22.0` and see if the problem exists still?

**Comment by zhanghongdou** [comment]
OK now i will  try it,   thank you

**Comment by zhanghongdou** [comment]
After I update into 0.21.0 version, will not appear this problem, but the 0.30.0 version has this problem, the author adjusted, please. Thank you

**Comment by robertjpayne** [comment]
@zhanghongdou you should no longer use 0.30.0 instead use 0.40.x which is working as well! Closing this issue for now.

**Comment by falipate** [comment]
@robertjpayne How do i use 0.40.x instead of 0.30.0?
