### ISSUE TITLE
footer view not position correct

### ISSUE THREAD

**Issue by caotian** [SnapKit/SnapKit#273]
I'm using this lib in tableview, code like this: 
 
![image](https://cloud.githubusercontent.com/assets/3139199/17646759/37976b9e-620a-11e6-8dff-842768671302.png)

the button float to the top of tableview, how can I handle this?
![image](https://cloud.githubusercontent.com/assets/3139199/17646746/c9ebaef2-6209-11e6-91be-fc6aa10b80c5.png)

btw. the similar code working perfect on masonry.

**Comment by robertjpayne** [comment]
@caotian can you please share the "Similar code" that works in Masonry?

**Comment by robertjpayne** [comment]
@caotian actually please open a new issue and fill out the appropriate issue template that starts the issue off.
