### ISSUE TITLE
recurring crash when installOnView() checks existingLayoutConstraint value with ==

### ISSUE THREAD

**Issue by nchodelski** [SnapKit/SnapKit#277]
### New Issue Checklist

* [x] I accept that if I do not fill out this issue template my issue will be immediately closed with no response
* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 9.0
 SnapKit Version         | . 0.22.0
 Integration Method      | cocoapods
 

### Issue Description

A function in my project updates the aspect ratio of a container view with `view.snp_updateConstraints`. Sometimes there is a crash that comes from comparing constrait  values with == within ConcreteConstraight.installOnView().  The section of this function that is crashing is  

calling function - ` internal installOnView() in Constraint.swift` .  Crash occurs on line `                    if existingLayoutConstraint == layoutConstraint {
`.  Xcode shows EXC_BAD_ACCESS error suggests accessing nil value .

```  
     // special logic for updating
        if updateExisting {
            // get existing constraints for this view
            let existingLayoutConstraints = layoutFrom!.snp_installedLayoutConstraints.reverse()
            
            // array that will contain only new layout constraints to keep
            var newLayoutConstraintsToKeep = [LayoutConstraint]()
            
            // begin looping
            for layoutConstraint in newLayoutConstraints {
                // layout constraint that should be updated
                var updateLayoutConstraint: LayoutConstraint? = nil
                
                // loop through existing and check for match
                for existingLayoutConstraint in existingLayoutConstraints {

                    if existingLayoutConstraint == layoutConstraint {
                        updateLayoutConstraint = existingLayoutConstraint
                        break
                    }
                }
                // if we have existing one lets just update the constant
                if updateLayoutConstraint != nil {
                    updateLayoutConstraint!.constant = layoutConstraint.constant
                }
                    // otherwise add this layout constraint to new keep list
                else {
                    newLayoutConstraintsToKeep.append(layoutConstraint)
                }
            }
            
            // set constraints to only new ones
            newLayoutConstraints = newLayoutConstraintsToKeep
        }
```

The actual crash shows up here: (in LayoutConstrait.swift in snapkit).  It occurs on the `    if left.secondItem !== right.secondItem {` line and debugging shows that left.secondItem is not a constraint value - so i think that left.secondItem is perhaps nil hence causing a crash when accessed.   Perhaps these values should be nil checked before comparison. 

```
 internal func ==(left: LayoutConstraint, right: LayoutConstraint) -> Bool {
    if left.firstItem !== right.firstItem {
        return false
    }
    if left.secondItem !== right.secondItem {
        return false
    }
```

Here is a picture of as much relevant info as i could find when the issue occurs. I have tried to print out the contents of the constraint values being compared in the console and open up the relevant variables in the Variables view:

![screen shot 2016-08-19 at 11 11 52 am](https://cloud.githubusercontent.com/assets/10591026/17820123/0d6163b2-6600-11e6-94f1-5400c7a4fbf3.png)

 If it helps at all - this is my calling function that calls `snp_updateConstraings`:

```
    func setAspect(aspect: CGFloat) {        
        guard let view = self.view where view.superview == container else {
            return
        }

        let defaultAspect: CGFloat = 9.0 / 16.0
        var asp = aspect
        self.aspect = aspect
        
        widthConstraint?.uninstall()
        heightConstraint?.uninstall()
        
        view.snp_updateConstraints { (make) -> Void in
            
            var parentAspect = container.bounds.size.width / container.bounds.size.height
            
            if parentAspect.isNaN {
                parentAspect = defaultAspect
            }
            
            if asp.isNaN {
                asp = defaultAspect
                self.aspect = asp
            }
            // Note:  Resize so that we fill the view (extra will be clipped by the parent
            if aspect < parentAspect {
                heightConstraint = make.height.equalTo(container.snp_width).multipliedBy(1.0 / asp).constraint
                widthConstraint = make.width.equalTo(container).constraint
            } else {
                heightConstraint = make.height.equalTo(container).constraint
                widthConstraint = make.width.equalTo(container.snp_height).multipliedBy(asp).constraint
            }
        }
```

**Comment by igorefremov** [comment]
@nchodelski @robertjpayne 

I did some digging into this, and I believe this is an issue with Swift, not SnapKit.

If you look at the type of secondItem referenced by:
```
if left.secondItem !== right.secondItem {
        return false
}

(LayoutConstraint.swift)
```
you'll see that it is defined by:
```
unowned(unsafe) public var secondItem: AnyObject?

(NSLayoutConstraint)
```
**Note the unowned(unsafe)**

Next, if you look at the Swift source for the !== operator, you'll see that it returns !(left === right), with === defined by:
```
switch (lhs, rhs) {
case let (l?, r?):
    return Bool(Builtin.cmp_eq_RawPointer(
        Builtin.bridgeToRawPointer(Builtin.castToNativeObject(l)),
        Builtin.bridgeToRawPointer(Builtin.castToNativeObject(r))
    ))
case (nil, nil):
    return true
default:
    return false
}

(stdlib/public/core/Equatable.swift)
```
**At this point, I also want to point out that I don't think it's a null pointer error since the === operator checks for nil**

I went ahead and followed my way up to castToNativeObject in a C++ file (lib/AST/Builtins.cpp), and all it does is return a type, which makes sense since that is how you cast objects in Swift.


So now, back to **unowned(unsafe)** - what I think is happening is:
1. secondItem is being set to a valid object.
2. The memory that secondItem is pointing to is being overwritten by something else at a lower level.
3. secondItem is never set back to point to nil.
4. When castToNativeObject(secondItem) is called, it attempts to create an object with the memory that secondItem is pointing to, which is now all garbage.
5. You see the crash.

**Comment by nchodelski** [comment]
Hi Igor, thanks very much for your insight.  Glad to hear its not from SnapKit, and interesting that it is coming from Swift To be honest I don't think I could have dug that deep into what's happening at a memory level with my current experience, so your analysis is quite enlightening for me. 

I have worked around the issue in my project by switching to using snp_makeConstraints for my use case each time the aspect ratio is set, which seems to work okay (though possibly a bit less smoothly).   

I'll go ahead and close the issue then.  Thanks again :)
