### ISSUE TITLE
Please tell me .I want to use it by swift3.0,but I don`t know what I do

### ISSUE THREAD

**Issue by XHJiang** [SnapKit/SnapKit#278]
### New Issue Checklist

* [x] I accept that if I do not fill out this issue template my issue will be immediately closed with no response
* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually

**Comment by robertjpayne** [comment]
@XHJiang Please target the 0.40.x branches, for now you'll need to use Carthage or pin it to Git from Podfile.
