### ISSUE TITLE
multipliedBy with centerY/top

### ISSUE THREAD

**Issue by tcurdt** [SnapKit/SnapKit#283]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 9.3
 SnapKit Version         | 0.21.1
 Integration Method      | carthage
 

### Issue Description

Maybe I just have the wrong expectation - but when I do
```
make.centerY.equalTo(contentView.snp_top).multipliedBy(0.5)
```

both view still keep a constant distance to each other. In fact this seems to give the same result:

```
make.centerY.equalTo(contentView.snp_top)
```

Am I using the API right?
Or is this a general thing about autolayout that I am missing?

**Comment by robertjpayne** [comment]
@tcurdt this is an Auto Layout thing, multiplier only works when going to a size constraint. So you could do `make.centerY.equalTo(contentView.snp_height).multipliedBy(0.5)` I believe (Im 99% sure that works but Auto Layout may complain there too)

**Comment by robertjpayne** [comment]
Unfortunately it's also impossible for me to prevent the autocomplete from showing up.

**Comment by tcurdt** [comment]
Bummer. Thanks for the clarification.
