### ISSUE TITLE
when call Constraint.deactive() Constraint.layoutConstraints element will be released

### ISSUE THREAD

**Issue by kimsungwhee** [SnapKit/SnapKit#289]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.0
 SnapKit Version         | feature/0.40.0
 Integration Method      | cocoapods
 

### Issue Description
At legacy version Constraint has install() and uninstall() method,but at feature/0.40.0 above methods was deleted.  
I try to use active() and deactive() to replace them,but when i use deactive() method layoutConstraint elements will be released. active() method not work for me.

```
self.layoutConstraints = NSHashTable<LayoutConstraint>.weakObjects()
```   
↓
  
```
self.layoutConstraints = NSHashTable<LayoutConstraint>()
```

work for me. but it memory leak. Constraint deinit method not called.

**Comment by robertjpayne** [comment]
@kimsungwhee great catch! Can you update to head of `feature/0.40.0` and give it a go? I think I've managed to fix this up.

**Comment by kimsungwhee** [comment]
@robertjpayne it works for me. Thank you very much.
