### ISSUE TITLE
Swift 3.0 with Carthage

### ISSUE THREAD

**Issue by netgfx** [SnapKit/SnapKit#297]
### New Issue Checklist

* [x ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.1
 SnapKit Version         | 0.22.0
 Integration Method      | e.g. carthage
 

### Issue Description

Support Carthage with Swift 3.0
Should I target a specific branch with Carthage for Swift 3.0 integration? If so can you share the exact command to run to achieve this?

Thanks.

**Comment by tcurdt** [comment]
@netgfx `github "SnapKit/SnapKit" "feature/0.40.0"`

...but it surely would be nice to get a swift3 release out.

**Comment by robertjpayne** [comment]
@tcurdt you'll be happy to know it's all good to go! "3.0.0" tag!
