### ISSUE TITLE
xcode 8 release use swift3.0. how can we do about snapKit update?

### ISSUE THREAD

**Issue by chen0807130004** [SnapKit/SnapKit#299]
my project have oc and swift .now I want to update xcode from 7.3.1 to 8. but xcode 8 not support swift2.0.

**Comment by robertjpayne** [comment]
@chen0807130004 you need to use the `feature/0.40.0` branch and pin it directly with Carthage or Cocoapods for now.

**Comment by n13** [comment]
Wait I thought SnapKit 3.0 has been converted to Swift 3.0? Did I get this wrong?
