### ISSUE TITLE
Not support swift 2.x ?

### ISSUE THREAD

**Issue by bolee** [SnapKit/SnapKit#301]
Which branch support xcode 7.2.1 and swift 2.1.1?

**Comment by robertjpayne** [comment]
@bolee use tag `0.22.1`

**Comment by bolee** [comment]
@robertjpayne I had change 0.22.0,but the error is:
<img width="950" alt="xcode-snapkit-error" src="https://cloud.githubusercontent.com/assets/2450909/18589709/86d970d0-7c5e-11e6-8717-0f5c82699c24.png">
