### ISSUE TITLE
Swift 2.3 - Use 0.22.0 release tag.

### ISSUE THREAD

**Issue by yangzhixiao** [SnapKit/SnapKit#302]
### New Issue Checklist

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually

**Comment by robertjpayne** [comment]
@yangzhixiao please see my edit to your issue title

**Comment by robertjpayne** [comment]
@yangzhixiao you need to use the `0.22.0` tagged release for Swift 2.3

**Comment by yangzhixiao** [comment]
pod 'SnapKit', '~> 0.22.0'
right ?

**Comment by robertjpayne** [comment]
@yangzhixiao correct
