### ISSUE TITLE
Swift 2.3 Support

### ISSUE THREAD

**Issue by romk1n** [SnapKit/SnapKit#304]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios/
 Platform Version        | 8.0
 SnapKit Version         | 3.0
 Integration Method      | cocoapods
 

### Issue Description

Is there a support for swift 2.3, the version 3.0.0 doesn't compile

**Comment by robertjpayne** [comment]
@romk1n keep using the v0.22.0 release tag for Swift 2.3!

**Comment by romk1n** [comment]
Great !

**Comment by andrewSvsg** [comment]
Could you please add note about swift 2.3 supporting to the main Readme file?
It very helpfull!
