### ISSUE TITLE
Constraint improperly relates anchors of incompatible types crash  Swift 2.3

### ISSUE THREAD

**Issue by charlesvinette** [SnapKit/SnapKit#305]
### New Issue Checklist

* [*] I have looked at the [Documentation](http://snapkit.io/docs)
* [*] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10
 SnapKit Version         | 0.22.0
 Integration Method      |Cocoapods
 

Hello everyone. Today I updated XCode but I am now having issues with SnapKit. The project is written in 2.3 so I am using Legacy Swift. However, I get this crashing error:

```'NSInvalidLayoutConstraintException', reason: 'Constraint improperly relates anchors of incompatible types: <SnapKit.LayoutConstraint:0x6000002a7aa0@/Users/charlesvinette/Documents/AppAndFlow/uStadium/ustadium/FanFeeds/FeedCell.swift#53 UILabel:0x7fc8c0c7c000.bottom == UIImageView:0x7fc8c0c7bb10.centerX - 2.0>'```

I have found similar issues , #291 and #295, however those seems to be for Swift 3.

Thanks a lot for your time working on SnapKit, I love using it!

Here is the crashing snippet:

```
override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
    super.init(style: style, reuseIdentifier: reuseIdentifier)
    self.selectionStyle = UITableViewCellSelectionStyle.None
    self.backgroundColor = UIColor.whiteColor()

    // Image
    self.contentView.addSubview(feedImageView)
    feedImageView.image = UIImage(named: "twitterU")
    feedImageView.snp_makeConstraints { (make) in
      make.centerY.equalTo(self)
      make.left.equalTo(self).offset(10)
      make.height.equalTo(50)
      make.width.equalTo(50)
    }

    // Feed Name Label
    self.contentView.addSubview(feedNameLabel)
    feedNameLabel.font = Font.subTitle
    feedNameLabel.text = ""
    feedNameLabel.textColor = UIColor.blackColor()  
    feedNameLabel.snp_makeConstraints { (make) in
      make.left.equalTo(feedImageView.snp_right).offset(10)
      make.bottom.equalTo(feedImageView.snp_centerX).offset(-2)
    }
```

**Comment by robertjpayne** [comment]
@charlesvinette exactly as the exception states you have an invalid constraint. You cannot pin the bottom edge to the centerX as they are on different axis.

**Comment by charlesvinette** [comment]
@robertjpayne Okok just made the change. I was wondering why I was having the issue since I didn't in the past. Thanks for your help!
