### ISSUE TITLE
module file was created by an older version of the compiler in xcode 8 and swift 2.3

### ISSUE THREAD

**Issue by WE-St0r** [SnapKit/SnapKit#307]
### New Issue Checklist

* [ +] I have looked at the [Documentation](http://snapkit.io/docs)
* [ +] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.22.0
 Integration Method      | e.g. cocoapods

**Comment by robertjpayne** [comment]
@WE-St0r please ensure you read the contributing guidelines and try to provide a complete issue ticket rather than just a title.
