### ISSUE TITLE
Does it support the latest Swift3.0 ?    public --> open

### ISSUE THREAD

**Issue by gujinku** [SnapKit/SnapKit#308]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

In the latest Swift3.0, "public class" is changed to "open class".  Not sure if all the SnapKit code support the latest Swift3.0

**Comment by robertjpayne** [comment]
@gujinku `open` is a keyword to express the availability of a method to be overridden where as `public` remains the option for public API's that are not to be overridden.

All of SnapKit's APIs are not intended or coded to be safe for overrides. You can still add extensions for helper API's I believe but you should not subclass.

**Comment by gujinku** [comment]
Thank you for prompt reply!
