### ISSUE TITLE
make.edges.equalTo(parent.snp.edges) regression

### ISSUE THREAD

**Issue by davidvartan** [SnapKit/SnapKit#309]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | osx
 Platform Version        | 10.11.6
 SnapKit Version         | 3.0.0
 Integration Method      | carthage

### Issue Description

Assume we have a view A, and X is the superview.

This works: `make.edges.equalTo(X)`

This does not, but previously did: `make.edges.equalTo(X.snp.edges)` and causes the view to shrink. Inspecting the constraints in the debugger, it looks like they're being set erroneously such that A.left, A.top, A.right, A.bottom are all set == X.left.

**Comment by robertjpayne** [comment]
@davidvartan are you sure you are running the 3.0.0 branch? This was a previous bug that I'm pretty sure I had fixed and there is even a passing test related to it.

**Comment by davidvartan** [comment]
Wow, that was quick! Thanks. I do see the `testEdgesToEdges` in my code, but it looks like it's not for OS X where I am.

**Comment by robertjpayne** [comment]
@davidvartan oof yea this fix may have gapped macOS

**Comment by robertjpayne** [comment]
@davidvartan should be fixed now in 3.0.1 release!
