### ISSUE TITLE
Xcode 8 and swift 2.3 - Baseline is unavailable

### ISSUE THREAD

**Issue by mime29** [SnapKit/SnapKit#311]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 8.0
 SnapKit Version         | 0.19.1
 Integration Method      | cocoapods
 

### Issue Description

After migrating to Xcode 8, I get the following error:
"'Baseline' is unavailable in Swift: Use 'lastBaseline' instead"
I cleaned my building folder and I also set the pod target to use legacy swift.

**Comment by robertjpayne** [comment]
@mime29 you must use 0.22.0 for Swift 2.3 support and you've indicated you are on 0.19.1. Upgrade and open a new issue if you have persisting problems.
