### ISSUE TITLE
Swift 3 Compile Error

### ISSUE THREAD

**Issue by sunshineclt** [SnapKit/SnapKit#312]
### Swift 3 Compile Error

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.0
 SnapKit Version         | 0.15.0
 Integration Method      | cocoapods
 

### Issue Description
![image](https://cloud.githubusercontent.com/assets/8625876/18622049/a97338aa-7e5d-11e6-82b6-8ca12534aea7.jpeg)
As you can see, SnapKit comes up compiling error. 
Hope it can be solved quickly :)

**Comment by robertjpayne** [comment]
@sunshineclt you must use 3.0.0 for Swift 3.0 you indicated you are currently on 0.15.0.

**Comment by sunshineclt** [comment]
@robertjpayne Thank you for your assistance! But the document in [http://snapkit.io/docs/](http://snapkit.io/docs/) is out-dated.
