### ISSUE TITLE
swift 2.3 compile error

### ISSUE THREAD

**Issue by shenyufei** [SnapKit/SnapKit#314]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 10.0
 SnapKit Version         | e.g. 3.0.0
 Integration Method      | e.g. cocoapods
 

### Issue Description
The outset, I was a novice, so please be careful answer.
I use swift 2.3, the error shown in JPEG.
Please tell me how to do, try some of the details。
Such as, `pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'`
Or give me some graphic instructions, it would be better
![23c79a20-4f28-4b89-a19b-998507a4093a](https://cloud.githubusercontent.com/assets/13211527/18627948/7778b7ac-7e90-11e6-8097-a0ae986b1511.png)

**Comment by robertjpayne** [comment]
@shenyufei please see the home page of the repo, you need to use the 0.22.0 tagged release for Swift 2.3

**Comment by shenyufei** [comment]
What do you mean, I do not understand。
0.22.0  is  SnapKit Version? @robertjpayne

**Comment by robertjpayne** [comment]
@shenyufei yes see https://github.com/SnapKit/SnapKit/releases/tag/0.22.0 you need to use this tagged version in Cocoapods for Swift 2.3

**Comment by shenyufei** [comment]
I use cocoapods, how should I do, ah, I can not download it?
Your reply really fast, give you a praise @robertjpayne

**Comment by robertjpayne** [comment]
@shenyufei if your podfile `pod 'SnapKit', '~> 0.22.0'`

**Comment by shenyufei** [comment]
thank you~~
