### ISSUE TITLE
3.0.1 - Some types does not conform to ConstraintOffsetTarget

### ISSUE THREAD

**Issue by cjwirth** [SnapKit/SnapKit#322]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | 8.0
 SnapKit Version         | 3.0.1
 Integration Method      | CocoaPods
 

### Issue Description

I used to have some code that did
```Swift
titleLabel.snp.makeConstraints() { make in
    make.top.left.right.equalTo(self).offset(UIEdgeInsets(top: self.padding, left: self.padding, bottom: 0, right: -self.padding))
}
```

But now I am getting an error because `offset` takes `ConstraintOffsetTarget`, which `UIEdgeInsets` and `CGPoint` no longer conform to.

It looks like the `NSLayoutAttribute.snp_constantForValue` function got migrated into `ConstraintConstantTarget.constraintConstantTargetValueFor(layoutAttribute:)`, so I'm guessing it might not be too hard to add in? 

I haven't looked too hard into the implementation, so if I'm missing something, let me know! I just noticed that this was no longer building after upgrading 😅

**Comment by robertjpayne** [comment]
@cjwirth you're probably going to want to use `equalTo(self).inset(UIEdgeInsets)` and you no longer need to invert the `right` or `bottom` values as SnapKit does this by default.

**Comment by cjwirth** [comment]
> you're probably going to want to use equalTo(self).inset(UIEdgeInsets) 

aah, if this is all it was, then it's definitely my fault, sorry about that!

> you no longer need to invert the right or bottom values as SnapKit does this by default.

Aah, so I don't have to do `right: -self.padding`, I can just do `right: self.padding` these days? Cool!

**Comment by robertjpayne** [comment]
@cjwirth CGPoint was removed because it's ambiguous for things like `make.top.bototm.equalTo(CGPoint)` you have to use constants and separate them out now.

**Comment by cjwirth** [comment]
Oh I guess that makes sense. It appears to be working 👍
