### ISSUE TITLE
Swift3 support question

### ISSUE THREAD

**Issue by medisean** [SnapKit/SnapKit#326]
I have a question about whether you have supported swift3?

**Comment by devdebonair** [comment]
![image](https://cloud.githubusercontent.com/assets/3687334/18735806/c0190466-804e-11e6-8e24-fa2a2e5cf2df.png)

**Comment by robertjpayne** [comment]
Closing because issue does not contain completed [Issue Template](https://github.com/SnapKit/SnapKit/blob/develop/ISSUE_TEMPLATE.md).
