### ISSUE TITLE
Build fails for swift 2.3

### ISSUE THREAD

**Issue by stephen-talari** [SnapKit/SnapKit#330]
### Swift 2.3 compilation error

I have 
* updated `use legacy swift language version` to `yes` for SnapKit pod
* Installed SnapKit (0.22.0)

All other pods are compiled successfully, only snapkit fails with the following error

![screen shot 2016-09-22 at 3 17 01 pm](https://cloud.githubusercontent.com/assets/1725945/18743948/311f2138-80d9-11e6-9cbe-774255ca40b4.png)

`Module file was created by an older version of the compiler; rebuild 'SnapKit' and try again: /Users/xxxx/Library/Developer/Xcode/DerivedData/Xxxxx-bmzfyqmmjrttvvgaarcczzxcynsn/Build/Products/Debug-iphonesimulator/SnapKit.framework/Modules/SnapKit.swiftmodule/x86_64.swiftmodule`

Also tried installing snapkit `>= 3.0.0` and `use legacy swift language version` to `No`, even then no luck.

Please help!

**Comment by robertjpayne** [comment]
Closing because issue does not contain completed [Issue Template](https://github.com/SnapKit/SnapKit/blob/develop/ISSUE_TEMPLATE.md).

**Comment by stephen-talari** [comment]
Sorry for not following template style.
Issue is because of cache, quitting xcode and running `rm -rf ~/Library/Developer/Xcode/DerivedData/` resolved my issue.
