### ISSUE TITLE
Changelog missing (Migration guide link broken)

### ISSUE THREAD

**Issue by lluisgerard** [SnapKit/SnapKit#338]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Not needed

### Issue Description

The migration guide:
https://github.com/SnapKit/SnapKit/blob/master/Documentation/SnapKit%203.0%20Migration%20Guide.md
Has a link to a CHANGELOG that is broken:
https://github.com/SnapKit/SnapKit/blob/master/CHANGELOG.md

I see that the file is actually in another branch so you can fix it by linking to this branch or copying the CHANGELOG to develop as well:
https://github.com/SnapKit/SnapKit/blob/feature/0.40.0/CHANGELOG.md

**Comment by robertjpayne** [comment]
@lluisgerard thanks for this! I'm migrating the changelog strictly to GitHub releases hence it's gone missing in master. I'll update the migration guide.
