### ISSUE TITLE
Scheme SnapKit OSX is not currently configured for the clean action.

### ISSUE THREAD

**Issue by aalenliang** [SnapKit/SnapKit#339]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  OS X
 Platform Version        | OS X 10.11.6, Xcode 8.0
 SnapKit Version         | 3.0.0
 Integration Method      | Carthage 0.18
 

### Issue Description

Carthage Update Failed:
Scheme SnapKit OSX is not currently configured for the clean action.

**Comment by robertjpayne** [comment]
@aalenliang can you run carthage with `--verbose` and paste output?

**Comment by robertjpayne** [comment]
Fixed with [3.0.2](https://github.com/SnapKit/SnapKit/releases/tag/3.0.2)
