### ISSUE TITLE
When I pod trunk push, Snapkit had some errors.

### ISSUE THREAD

**Issue by aimobier** [SnapKit/SnapKit#350]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
Issuing being closed due to not filling out issue template.

> `pod trunk push` is reserved for the owners of the Pod and cannot be used by users.

**Comment by aimobier** [comment]
I feel very sorry, I was too anxious, the point is wrong. Cause my description is not enough time to write
Also very pleasantly surprised at your recovery rate 🍻

**Comment by robertjpayne** [comment]
@aimobier looks like you're not using Xcode 8 on command line tools to me.

**Comment by aimobier** [comment]
yes. Can you tell me what is the cause of this problem? Is it because of my mistakes?

**Comment by robertjpayne** [comment]
@aimobier You need to use Xcode 8 probably? `xcode-select` from terminal to see help on how to Switch.

**Comment by aimobier** [comment]
I'm not quite sure what you're saying, but I'm using Xode8 and Swift 3.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. IOS
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 3.0.2
 Integration Method      | e.g. cocoapods

**Comment by robertjpayne** [comment]
@aimobier are you sure from command line? `xcode-select -p`

**Comment by aimobier** [comment]
I'm really sorry. I don't know what you're saying. I haven't been in touch with these things. But when I run the version, print it out.

````
xcode-select -p
/Applications/Xcode.app/Contents/Developer
````
This path is the path of my Xcode8, I only have this one Xcode

![62aab792-71b5-4b20-8a77-afaa26c47425](https://cloud.githubusercontent.com/assets/6121524/19218064/93041c96-8e21-11e6-9e5b-2934c0a701f6.png)

````
xcode-select -v
xcode-select version 2343.
````

**Comment by robertjpayne** [comment]
@aimobier sounds like you're not 100% up to date:

```
xcode-select -v
xcode-select version 2345.1.
```

Try checking for an update?

**Comment by aimobier** [comment]
You mean to upgrade my Xcode version？

OK. I really found an update in store App, I'll try it out. Thank you very much for your reply.
