### ISSUE TITLE
Version 3.0.2 Build Failed

### ISSUE THREAD

**Issue by RMPtc** [SnapKit/SnapKit#353]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS 
 Platform Version        | 10.0
 SnapKit Version         | 3.0.2
 Integration Method      | Carthage
 

### Issue Description

Updated to Xcode 8 and build is failing due to lack of the scheme Example-iOS

*** Fetching SnapKit
*** Checking out SnapKit at "3.0.2"
*** xcodebuild output can be found in /var/folders/bc/lqgb7j8n4jl4qdxd92l650dh0000gp/T/carthage-xcodebuild.BjKkEf.log
A shell task (/usr/bin/xcrun xcodebuild -workspace .../Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme Example-iOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme Example-iOS is not currently configured for the build action.

**Comment by robertjpayne** [comment]
@RMPtc can you post your `cartfile` and/or command line usage? Sounds like you have an old version cached that is bugging the schemes.

**Comment by RMPtc** [comment]
I had updated Carthage to the latest version as well.
### Cartfile
#SnapKit
github "SnapKit/SnapKit" == 3.0.2

### Command line
$carthage update --platform iOS

**Comment by robertjpayne** [comment]
@RMPtc can you try to run:

`rm -fr ~/Library/Caches/org.carthage.CarthageKit/dependencies/SnapKit` and then `carthage update --platform iOS` and see if that resolves it?

**Comment by RMPtc** [comment]
@robertjpayne Even after clearing the cache it still gives the same error.

**Comment by RMPtc** [comment]
@robertjpayne It is finally working, I think was also a problem with cached stuff from the xcode.

**Comment by ChanchalW** [comment]
I am facing the same issue. What to do in this case.
