### ISSUE TITLE
CGPointMake in Docs is no longer valid and needs to be updated

### ISSUE THREAD

**Issue by graham-perks-snap** [SnapKit/SnapKit#354]
- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)
- [x] I have filled out this issue template.
### Issue Info

| Info | Value |
| --- | --- |
| Platform | iOS |
| Platform Version | 10.0 |
| SnapKit Version | 3.0.1 |
| Integration Method | cocoapods |
### Issue Description

The docs (README.md) are outdated. This code:

// make centerX = superview.centerX - 5, centerY = superview.centerY + 10
make.center.equalTo(superview).offset(CGPointMake(-5, 10))

No longer builds. CGPointMake is unavailable in Swift, and CGPoint is no longer allowable by SnapKit as an offset (if I'm reading it right, https://github.com/SnapKit/SnapKit/issues/322 explains this).

The docs need updating with how to center something with an offset.

**Comment by robertjpayne** [comment]
@graham-perks-snap thanks for the report!

**Comment by robertjpayne** [comment]
Fixed! Sorry for the massive delay.
