### ISSUE TITLE
How to fit Swift3.0

### ISSUE THREAD

**Issue by jiaoxinwei** [SnapKit/SnapKit#359]
### New Issue Checklist

Latest version upgrade to 3.0, after a lot of mistakes.

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
Closing as this issue does not conform to the issue template and does not contain enough information.
