### ISSUE TITLE
SnapKit 3.0.0 breaking change to make.center(0)

### ISSUE THREAD

**Issue by n13** [SnapKit/SnapKit#360]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫
- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)
- [x] I have filled out this issue template.
### Issue Info

| Info | Value |
| --- | --- |
| Platform | ios |
| Platform Version | 10.0 |
| SnapKit Version | 3.0.2 |
| Integration Method | cocoapods |
### Issue Description

Issue: The meaning of setting a center constraint to 0 changed from pre- to post SnapKit 3.0.0. This should be in the release notes. 

I had lots of code like this

```
make.center.equalTo(0)
make.centerX.equalTo(0)
make.centerY.equalTo(0)

```

In SnapKit prior to 3.0.0 this was interpreted as _"make the center the same as the superview center"_

In SnapKit post 3.0.0 this is now interpreted as _"make the center equal to the left / top corner of the superview"_

I think this should be in the release notes of SnapKit 3.0.0.

I had over 100 occurrences of this in my code.

I fixed them all by replacing ".equalTo(0)" with ".equalToSuperview()"

I am guessing the latter method was the correct one all along and the former maybe just an implementation side-effect. 

But I think it should be in release notes. 

Cheers, and thanks for making an awesome framework!

**Comment by robertjpayne** [comment]
Sorry this was left out of the documentation, you are correct that setting a constraint directly to a constant now has slightly altered behaviour. This is to try and match how it reads better, `make centerX equalTo fifteen` would imply the centerX == 15.0 not centerX == centerX + 15.0.

I'll track this to update the changelog and migration guide!

**Comment by jonnyleeharris** [comment]
This caught me out too.

**Comment by robertjpayne** [comment]
This is now documented in the migration guide as a 'Quirk' I apologise to those that were affected by this and it's lack of documentation!
