### ISSUE TITLE
fatal error: Updated constraint could not find existing matching constraint to update

### ISSUE THREAD

**Issue by YariZhang** [SnapKit/SnapKit#361]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 9.0
 SnapKit Version         | 3.0.2
 Integration Method      | cocoapods
 

### Issue Description

I've migrated my app to Swift3 .Then it crashed! I saw:
`fatal error: Updated constraint could not find existing matching constraint to update: <SnapKit.LayoutConstraint:0x6180000b5480@LhbStockDetailView.swift#492 Lhb.LhbStockReasonItem:0x7fa772c2f3d0.bottom == UILabel:0x7fa772c31750.bottom>: file /Users/zhangyr/Desktop/develops/company_code/lhb/app_ios_lhb/Lhb/Pods/SnapKit/Source/Constraint.swift, line 261` 

The following is part of the code：

```
let reasonV  = LhbStockReasonItem()
topView.addSubview(reasonV)
reasonV.snp.makeConstraints { (maker) in
    maker.left.equalTo(self.topView)
    if masV == nil {
         maker.top.equalTo(self.topView)
    }else{
         maker.top.equalTo(masV!.snp.bottom).offset(11)
    }
    maker.right.equalTo(self.topView)
    maker.bottom.equalTo(self.topView)
}
reasonV.show(reason)
```

```
class LhbStockReasonItem : BaseView {   
    func show(_ data : LhbListReasonData) {
        let iconImg = UIImageView()
        let scale               = UtilTool.getNetImageScale()
        var width   : CGFloat   = 48 / scale
        var height  : CGFloat   = 48 / scale
        self.addSubview(iconImg)
        
        iconImg.sd_setImage(with: URL(string: data.icon), completed: { (image, error, type, url) in
            if image != nil
            {
                width               = (image?.size.width)! / scale
                height              = (image?.size.height)! / scale
                iconImg.image       = image
                self.addSubview(iconImg)
                iconImg.snp.remakeConstraints({ (maker) in
                    maker.left.equalTo(self)
                    maker.top.equalTo(self)
                    maker.width.equalTo(width)
                    maker.height.equalTo(height)
                })
            }else
            {
                qcgPrint("error url: \(url)")
            }
        })
        
        iconImg.snp.makeConstraints({ (maker) in
            maker.left.equalTo(self)
            maker.top.equalTo(self)
            maker.width.equalTo(width)
            maker.height.equalTo(height)
        })
        
        let text        = UILabel()
        text.font       = UIFont.normalFontOfSize(12)
        text.textColor  = Color("#333")
        text.text       = data.text
        self.addSubview(text)
        text.snp.makeConstraints { (maker) in
            maker.left.equalTo(iconImg.snp.right).offset(5)
            maker.top.equalTo(self).offset(1)
            maker.height.equalTo(12)
        }
        
        weak var masV   : UIView?
        for r in data.reasons {
            
            let point       = UILabel()
            point.textColor = Color("#333")
            point.text      = "●"
            point.font      = UIFont.normalFontOfSize(12)
            self.addSubview(point)
            
            point.snp.makeConstraints({ (maker) in
                if masV == nil {
                    maker.left.equalTo(text.snp.right).offset(15)
                    maker.centerY.equalTo(text)
                }else{
                    maker.left.equalTo(masV!)
                    maker.top.equalTo(masV!.snp.bottom).offset(8)
                }
                maker.height.equalTo(12)
                maker.width.equalTo(8)
            })
            
            let reason          = UILabel()
            reason.textColor    = Color("#333")
            reason.text         = r
            reason.font         = UIFont.normalFontOfSize(12)
            self.addSubview(reason)
            
            reason.snp.makeConstraints({ (maker) in
                maker.left.equalTo(point.snp.right).offset(5)
                maker.centerY.equalTo(point)
                maker.height.equalTo(12)
            })
            masV                = point
        }
        
        if masV != nil {
            self.snp.updateConstraints { (maker) in
                maker.bottom.equalTo(masV!)
            }
        }
    }  
}
```

crash at ：
```
self.snp.updateConstraints { (maker) in
      maker.bottom.equalTo(masV!)
}
```

**Comment by robertjpayne** [comment]
@YariZhang you can no longer use `updateConstraints` to create additional new constraints after one or more constraints have already been created for the source view.

`updateConstraints` now can:

* Create constraints **IF** no other constraints have been created for the source view from another `updateConstraints` OR `makeConstraints` call.
* Update constraints constants **IF** the rest of their signature matches a previously created constraint for the source view.

In your case you probably want to use an additional `snp.makeConstraints` which will allow incremental creation of constraints.

**Comment by YariZhang** [comment]
@robertjpayne thanks for your reply. yea , i know i can't use updateConstraints to create additional new constraints after one or more constraints have already been created for the source view .but in this case ,i'v updated bottom constraint that it has created , i didn't create a new one . i found when i relate source view's bottom to masV.snp.bottom , it crashed . it works when i use another view's.  masV  is a subview of the source view , so,can't source view relate to its subview's constraint in snapKit? it works well in masonry.

**Comment by robertjpayne** [comment]
@YariZhang you've given an incomplete example but from looks:

```
self.snp.updateConstraints { (maker) in
    maker.bottom.equalTo(masV!)
}
```

You can't update the `relation` of a constraint, that would be considered a new constraint. You can *only* update the constant value. Are you positive no where else is whatever `self` is having constraints created via SnapKit?

**Comment by robertjpayne** [comment]
@YariZhang actually sorry looked at your example again:

You are creating constraints here:

```
reasonV.snp.makeConstraints { (maker) in
    maker.left.equalTo(self.topView)
    if masV == nil {
         maker.top.equalTo(self.topView)
    }else{
         maker.top.equalTo(masV!.snp.bottom).offset(11)
    }
    maker.right.equalTo(self.topView)
    maker.bottom.equalTo(self.topView)
}
```

And I presume some time after that you are calling `reasonV.show()` you already have a `make.bottom.equalTo(self.topView)` and you are actually creating a new constraint in `show()` where you have `make.bottom.equalTo(masV!)` and the error is fired then.

**Comment by YariZhang** [comment]
ok,I got it! but I want to relate the source view to the subview,what should I do? remove first then creat?

**Comment by robertjpayne** [comment]
@YariZhang if you want to change the relation you have to use `remakeConstraints` and re-create all of the constraints. Or you can keep references to individual constraints `self.constraint = make.bottom.equalTo(other).constraint` and uninstall them manually and use `makeConstraints` to then add new ones.

**Comment by YariZhang** [comment]
@robertjpayne it works for me. thanks a lot.

**Comment by TadeasKriz** [comment]
@robertjpayne May I ask why was the update logic changed this way? Thanks.

**Comment by robertjpayne** [comment]
@TadeasKriz it was changed because the old behaviour resulted in ambiguous behaviour (e.g. is it adding a constraint I want or duplicating a constraint I thought it was supposed to update?).

SnapKit's goal over Masonry is to be safe by default and explicit, even if in some cases like this mean slightly more pain on the developers end.

I'd argue most people using `updateConstraints` before had to debug the silent duplication of constraints and resolve it using a different approach of some sort.

**Comment by TadeasKriz** [comment]
@robertjpayne Ouch! I had the same problem and didn't know about it! I had a different priority set in `make` and that's why it was crashing in `update`. I misunderstood the new functionality. Thanks for this change, much appreciated!

**Comment by robertjpayne** [comment]
Closing this as I feel it's resolved, re-open if you feel otherwise.

**Comment by 515783034** [comment]
good changes
