### ISSUE TITLE
constraint descriptions need work. what i see: "... constraint for <private>"

### ISSUE THREAD

**Issue by gizmolab10** [SnapKit/SnapKit#362]
### New Issue Checklist
- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)
- [x] I have filled out this issue template.
### Issue Info

| Info | Value |
| --- | --- |
| Platform | osx |
| Platform Version | 10.12 |
| SnapKit Version | 3.0 |
| Integration Method | carthage |
### Issue Description

although i like very much the ideas which inspired SnapKit, some of its runtime debugging output (in the console log) is frustratingly absent information identifying the constraint or ui object causing an issue, nearly always referring to "<private>," which i think is provided by snap kit:

> [Layout] Unable to simultaneously satisfy constraints:
> <private>
> 
> Will attempt to recover by breaking constraint 
> <private>
> 
> Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.

i tried adding a call to .labeled("specific name") for each constraint, but still see <private>. i tried setting the symbolic breakpoint as above. not much value there. the "Debug View Hierarchy" feature of Xcode shows all constraints, and careful study and thought reveals the answer after a fair amount of time invested. this effort would be reduced (often significantly?) with adequately improved constraint descriptions.

perhaps i am doing something wrong? if so, please enlighten me. thanks in advance.

**Comment by robertjpayne** [comment]
@gizmolab10 can you provide a bit more console output or a screenshot? I'm not sure I understand 100% what piece of the debugging you'd like improved.

**Comment by gizmolab10** [comment]
the piece i would like improved is "\<private\>" expanded to clearly (to the programmer) identify "the constraint which can't be satisfied and which is being broken in the attempt to recover"

**Comment by robertjpayne** [comment]
@gizmolab10 a screenshot would be helpful still, I've not experienced that behaviour and it sounds more like a LLDB bug that can't resolve the symbols than a SnapKit issue. We never would emit "private" itself.

**Comment by gizmolab10** [comment]
sounds reasonable. however, can you suggest to me how to add / modify the constraint such that LLDB can resolve it symbolically to something other than \<private\>?

**Comment by gizmolab10** [comment]
i certainly understand why you'd request a screenshot, but i can't come up with one that conveys any more information than i've given you. my apologies. and yet, i'm still a newbie with snap kit, and hope that debugging it is ultimately not the ordeal it currently is. assuming that what i describe is not an LLDB bug and instead is something i can improve by oh say configuring symbols (of either the constraints i create with snap kit or the ui objects they refer to), do you have any suggestions?

**Comment by robertjpayne** [comment]
@gizmolab10 any further updates on this? Again I'd really love to help but as far as I can tell in the console if iOS attempts to `NSLog` one of SnapKit's constraints it should have full debugging information attached.

**Comment by gizmolab10** [comment]
thanks for keeping your eye on this. i did finally manage to read the tea leaves (apple’s unhelpful log of address references to views) and fix it. so, you can consider mine a newbie question and close it.

**Comment by robertjpayne** [comment]
@gizmolab10 👍
