### ISSUE TITLE
all layout is down in iOS 10 ,i am using 0.22

### ISSUE THREAD

**Issue by stevenkitter** [SnapKit/SnapKit#364]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫
- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)
- [x] I have filled out this issue template.
### Issue Info

| Info | Value |
| --- | --- |
| Platform | e.g. ios/osx/tvos |
| Platform Version | e.g. 8.0 |
| SnapKit Version | e.g. 0.22.0 |
| Integration Method | e.g. carthage/cocoapods/manually |
### Issue Description

all layout is down in iOS 10 ,i am using 0.22

**Comment by robertjpayne** [comment]
@stevenkitter not sure I understand?

**Comment by stevenkitter** [comment]
SnapKit 0.22，do not work in iOS10，i'm using dynamic tableViewCell Height，the subViews using SnapKit to layout @robertjpayne

**Comment by stevenkitter** [comment]
Integration Method is manually

**Comment by robertjpayne** [comment]
@stevenkitter I don't think this will be related to SnapKit, some things change between iOS releases and likely just an incompatibility. If you used Apple's Auto Layout constraint's API you'd likely experience the same issue.

**Comment by robertjpayne** [comment]
Best I can recommend is to try and use NSLayoutConstraint API's directly and see if you can make it work, if you can and feel like SnapKit is actually the cause of the bug open an issue demonstrating the differences and expected behavior.

**Comment by stevenkitter** [comment]
lazy var tableView: UITableView = {
        let tabv = UITableView(frame: CGRectZero, style: .Plain)
        tabv.delegate = self
        tabv.dataSource = self
        tabv.estimatedRowHeight = 60
        tabv.rowHeight = UITableViewAutomaticDimension
        tabv.tableFooterView = UIView()
        return tabv
    }()
Cell: 
  override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        setupUI()
        setupLayout()
    }

 func setupUI(){
        contentView.addSubview(self.xNameLabel)
        contentView.addSubview(self.xPersonNum)
        contentView.addSubview(self.xHeadView)
        contentView.addSubview(self.xTeamsLabel)
    }
    
    func setupLayout(){
        xHeadView.snp_makeConstraints { (make) in
            make.centerY.equalTo(contentView)
            make.size.equalTo(CGSizeMake(OrgMembersVcCellImageViewW, OrgMembersVcCellImageViewW))
            make.left.equalTo(contentView).offset(margin)
        }
        xNameLabel.snp_makeConstraints { (make) in
            make.bottom.equalTo(xHeadView.snp_centerY).offset(-5)
            make.left.equalTo(xHeadView.snp_right).offset(margin)
        }
        
        xPersonNum.snp_makeConstraints { (make) in
            make.left.equalTo(xNameLabel.snp_right).offset(margin)
            make.bottom.equalTo(xNameLabel)
            
        }
        xTeamsLabel.snp_makeConstraints { (make) in
            make.left.equalTo(xNameLabel)
            make.top.equalTo(xHeadView.snp_centerY).offset(5)
        }
        
        contentView.snp_makeConstraints { (make) in
            make.left.right.top.equalTo(self)
            make.bottom.greaterThanOrEqualTo(xHeadView).offset(2*margin)
        }
    }

**Comment by stevenkitter** [comment]
![a85dd733-41fe-4020-ac3e-1abfafbbe872](https://cloud.githubusercontent.com/assets/12658782/19794743/652a355e-9d07-11e6-9a39-e9629a4a3f9d.png)
subViews below contentView why? swift2.3 iOS10

**Comment by stevenkitter** [comment]
var cell = tableView.dequeueReusableCellWithIdentifier("OrgMembersVcFirstCell") as? OrgMembersVcFirstCell
            if cell == nil {
                cell = OrgMembersVcFirstCell(style: .Default, reuseIdentifier: "OrgMembersVcFirstCell")
            }
            cell?.xHeadView.image = UIImage(named: "OrgMembersVc_Approval")
            cell?.xNameLabel.text = exModel.titleStr
            cell?.xPersonNum.text = exModel.valueStr
            cell?.accessoryType = .DisclosureIndicator
            cell?.setNeedsLayout()
            cell?.layoutIfNeeded()
            return cell!

**Comment by stevenkitter** [comment]
it's ok in iOS9 and below,in iOS 10 it's like that i mentioned above

**Comment by stevenkitter** [comment]
@robertjpayne please help me, thank you too much

**Comment by stevenkitter** [comment]
if #available(iOS 10, *) {
            contentView.snp_makeConstraints { (make) in
                make.edges.equalTo(self)
            }
        }
finished，thanks ，it's none of snapkit  business

**Comment by robertjpayne** [comment]
@stevenkitter is this resolved then?
