### ISSUE TITLE
Cannot set backgroundColor of subViews of UIScrollView

### ISSUE THREAD

**Issue by SongleBao** [SnapKit/SnapKit#365]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 10.1
 SnapKit Version         | 3.0.2
 Integration Method      | cocoapods
 

### Issue Description

I try to use SnapKit to add some UIView object as subView of a UIScrollView. It turns out that I cannot set the backgroundColor of UIView object because they are covered by the UIScrollView's backgroundColor. But if I use `frame` to do the same thing, the backgroundColor is correct. 

Here's code with SnapKit:
```
let scrollView = UIScrollView.init()
scrollView.isPagingEnabled = true
self.view.addSubview(scrollView)
scrollView.snp.makeConstraints { (make) in
    make.left.right.top.bottom.equalTo(self.view)
}

var lastView: UIView? = nil
for i in 0 ..< 5 {
    let colorView = UIView.init()
    let red = CGFloat(arc4random() % 256) / 255.0
    let blue = CGFloat(arc4random() % 256) / 255.0
    let green = CGFloat(arc4random() % 256) / 255.0
    colorView.backgroundColor = UIColor.init(red: red, green: green, blue: blue, alpha: 1.0)
    scrollView.addSubview(colorView)

    colorView.snp.makeConstraints({ (make) in
        make.top.bottom.equalTo(scrollView)
        make.width.equalTo(scrollView)

        if i == 0 {
            make.left.equalTo(scrollView)
        }
        else {
            make.left.equalTo((lastView?.snp.right)!)
        }

        if i == 4 {
            make.right.equalTo(scrollView)
        }
    })
    lastView = colorView
}
```

Here's code with `frame`:
```
let scrollView = UIScrollView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height))
scrollView.isPagingEnabled = true
scrollView.contentSize = CGSize.init(width: self.view.bounds.size.width * 5, height:self.view.bounds.size.height)
self.view.addSubview(scrollView)

for i in 0 ..< 5 {
    let colorView = UIView.init(frame: CGRect.init(x: CGFloat(i) * scrollView.bounds.width, y: 0, width: scrollView.bounds.width, height: scrollView.bounds.height))
    let red = CGFloat(arc4random() % 256) / 255.0
    let blue = CGFloat(arc4random() % 256) / 255.0
    let green = CGFloat(arc4random() % 256) / 255.0
    colorView.backgroundColor = UIColor.init(red: red, green: green, blue: blue, alpha: 1.0)
    scrollView.addSubview(colorView)
}
```

**Comment by robertjpayne** [comment]
`make.top.bottom.equalTo(scrollView)` is probably invalid, you need to use a `height` constraint rather than `bottom` as `right` and `bottom` attributes in scroll views are for getting scroll bounds to work.

You should also constraint the scroll view to `left.top.width.height` of the view just to be safe.

**Comment by SongleBao** [comment]
@robertjpayne The problem is solved. Thanks a lot.
