### ISSUE TITLE
Can not update constraints by xib created

### ISSUE THREAD

**Issue by mrkey0310** [SnapKit/SnapKit#370]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 9.0+
 SnapKit Version         | e.g. 3.0.2
 Integration Method      | e.g. cocoapods
 

### Issue Description
I had use a XIB to create a custom uiview ,and try snp.makeConstraints and snp.updateConstraints  to update or add new constraints(like make some simple animation),  but it doesn't work. It work well with swift2.2 version

**Comment by robertjpayne** [comment]
@mrkey0310 that is correct, SnapKit will *never* touch a constraint that was not made by SnapKit this is by design because SnapKit relies on complete ownership from creation for all of it's features.

You will need to set them as "placeholders" or not use SnapKit to conflict with them.
