### ISSUE TITLE
Suggestion: Assignment Operators

### ISSUE THREAD

**Issue by fjcaetano** [SnapKit/SnapKit#371]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ x ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ x ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ x ] I have filled out this issue template.
 

### Issue Description

Wouldn't be interesting to use operators manipulate the constraints? Functions such as `equalTo`, `offset`, `multipliedBy` can be easily transformed to standard operators like `=`, `+`, `*`, etc, and I believe it would improve readability

If you think this interesting I can work on a fork to implement this and we need to define all operators.

I'd like to stick to the basics, but we would have to improvise with assignments like `priority`, which  I believe would require a custom operator (maybe `|` or `>>`)

**Comment by robertjpayne** [comment]
@fjcaetano we explored this option early on and avoided it due for several reasons:

- Ambiguity `make.left = otherView.snp.right + 20 * 20`, is it right.constant = 20 and right.multiplier 20 or is it right.constant = 400?
- Custom operators have to be used for things like priority or insets
- Makes layout code *vastly* harder to read and understand

SnapKit tries to enforce a single way of doing things, the DSL narrows as you use it and ensures that similar constraints read similarly in code to help reduce the mental burden of learning Auto Layout.

SnapKit uses several protocols to implement the different stages of making constraints, there's absolutely nothing preventing you from creating your own operators, if you need a constructor made public to allow for this functionality open a separate issue for consideration 👍
