### ISSUE TITLE
 If i use 'snp.update' to update a constraint, but I haven't create the constraint. This method works well in swift 2.2, but doesn't work in swift3.0. I  must create the constraint in 'makeconstraint' method, but i don't  need to do it in swift 2.2.

### ISSUE THREAD

**Issue by DCYGitHub** [SnapKit/SnapKit#373]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
Issue template unfilled
