### ISSUE TITLE
Module compiled with swift 3.0 cannot be imported in Swift 3.0.1. 

### ISSUE THREAD

**Issue by zhangdc** [SnapKit/SnapKit#375]
### New Issue Checklist

* [✔️] I have looked at the [Documentation](http://snapkit.io/docs)
* [✔️] I have read the [F.A.Q.](http://snapkit.io/faq)
* [✔️] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | Xcode8.1
 SnapKit Version         | cartfile: github "SnapKit/SnapKit"
 Integration Method      | carthage
 

### Issue Description

I am Xcode8.1 development tools, and use the Carthage to import SnapKit, my project has been an error as a result, the great spirit guide, thank you!

The input terminal：xcrun swift -version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)

The input terminal：carthage version
0.18.1

![tmp317fa0e6](https://cloud.githubusercontent.com/assets/22906858/20625621/7ace97a2-b34f-11e6-8bec-2441c2e38cc9.png)

Thank you for your help!

**Comment by robertjpayne** [comment]
You need to update your command line tools version in Xcode preferences as well as possibly clear DerivedData / Carthage cache.

**Comment by zhangdc** [comment]
I listened to your advice, delete the cache of Xcode, but there is no change.(my project is cocos2d - x created project, nested Swift language) I'm sorry didn't say understand.
/(ㄒoㄒ)/~~My project used on Xcode8.0 SnapKit is normal, but used on Xcode8.1 error will occur
