### ISSUE TITLE
Module compiled with swift 3.0 cannot be imported in Swift 3.0.1.

### ISSUE THREAD

**Issue by zhangdc** [SnapKit/SnapKit#378]
### New Issue Checklist

* [✔️] I have looked at the [Documentation](http://snapkit.io/docs)
* [✔️] I have read the [F.A.Q.](http://snapkit.io/faq)
* [✔️] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | Xcode8.1
 SnapKit Version         | cartfile: github "SnapKit/SnapKit"
 Integration Method      | carthage
 

### Issue Description

I am Xcode8.1 development tools, and use the Carthage to import SnapKit, my project has been an error as a result, the great spirit guide, thank you!
(my project is cocos2d - x created project, nested Swift language) 
(My project used on Xcode8.0 SnapKit is normal, but used on Xcode8.1 error will occur)

The input terminal：xcrun swift -version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)

The input terminal：carthage version
0.18.1

![tmp317fa0e6](https://cloud.githubusercontent.com/assets/22906858/20625621/7ace97a2-b34f-11e6-8bec-2441c2e38cc9.png)

Thank you for your help!

**Comment by zhangdc** [comment]
@robertjpayne I listened to your advice, delete the cache of Xcode, but there is no change.(my project is cocos2d - x created project, nested Swift language) I'm sorry didn't say understand.
/(ㄒoㄒ)/~~ My project used on Xcode8.0 SnapKit is normal, but in Xcode8.1 error will occur

**Comment by robertjpayne** [comment]
@zhangdc you probably need to clear your Carthage cache too, otherwise I'm really unsure it's an issue with your specific project as it works fine locally and the project compiles fine with Xcode 8.1 as well.

**Comment by mzgnr** [comment]
@zhangdc can you try `carthage update --platform iOS --no-use-binaries` ?

**Comment by zhangdc** [comment]
@raylillywhite Actually I want to ask you now have Xcode8.1 development?And the use of Carthage.
I have seen in https://github.com/Carthage/Carthage said:
From the source: If you 'd like to run the latest development version (which may be highly unstable or incompatible), simple clone the master branch of the repository, then run make install. The Requires Xcode 8.0 or later (Swift 2.3, but not currently 3 x).

**Comment by zhangdc** [comment]
@mzgnr Yes, I've tried, but still complains, but thank you for your answer!

**Comment by zhangdc** [comment]
@robertjpayne @mzgnr I have already solved the problem, my Mac has two Xcode, a version 8.0, another is 8.1, I deleted the version 8.0 Xcode, uninstall and reinstall Carthage, then according to the document to import again, there is no problem...Thank you two help me to answer this question

**Comment by robertjpayne** [comment]
@zhangdc great! Closing this now as it's resolved.
