### ISSUE TITLE
[网络]	Memory leak

### ISSUE THREAD

**Issue by Eiltea** [SnapKit/SnapKit#379]
只要设置约束就有内存泄露，请问一下，什么原因，贴上一条代码。
 override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.red
        view.addSubview(temp)
        temp.snp.makeConstraints { (make) in
            make.edges.equalTo(view)
        }
    }
    private lazy var temp : UILabel = {
        let label = UILabel()
        return label
    }()

**Comment by Eiltea** [comment]
3.0的问题，不知道是不是已经更新了

**Comment by robertjpayne** [comment]
Closing as it does not follow issue template. Also probably dupe of #363

**Comment by Tbwas** [comment]
3.0依旧有问题

**Comment by YDemo** [comment]
问题解决了吗？ 现在一般用什么进行手动布局呢。
