### ISSUE TITLE
Enhancement - cherry pick traits https://github.com/Finb/SnapKit-TraitVariations

### ISSUE THREAD

**Issue by johndpope** [SnapKit/SnapKit#380]
### New Issue Checklist

* [1 ] I have looked at the [Documentation](http://snapkit.io/docs)
yes - I searched for trait. 
* [ 1] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ 1] I have filled out this issue template.

### Issue Info
na

### Issue Description
snapkit doesn't have support for traits. 
People are going for interface builder so they can use traits
https://medium.com/@craiggrummitt/size-classes-in-interface-builder-in-xcode-8-74f20a541195#.jubjk3sm9
This must be stopped. 

https://github.com/Finb/SnapKit-TraitVariations

**Comment by robertjpayne** [comment]
Thanks for the issue, I think there's a few problems with traits and SnapKit though:

- Traits from IB auto-update if you auto-rotate and a trait kicks in or kicks off
- The API on this repo is quite messy, it'd need quite a bit of work to integrate

I personally advise people to use constants with widths/ratios and mimic traits in their own code. It makes for more flexible constraints. If we could fix the auto rotation thing I may be open to a PR though.

**Comment by robertjpayne** [comment]
Closing this, I believe size classes are valuable but they really are an Interface Builder domain thing. While SnapKit can be used with Interface builder it has absolutely no intention of being compatible with everything Interface Builder does.

I would still be open to a PR that:

1. Integrates directly to this repo, I unfortunately do not have time to cherry pick and merge code from foreign repos and make it an official API.
2. Cleans up the public API so it's more understandable what is going on
3. Ensures all of this iOS specific API is tucked away under `#if os(iOS)` style defines, it should not be exposed to macOS
