### ISSUE TITLE
Invalid library version

### ISSUE THREAD

**Issue by zetasq** [SnapKit/SnapKit#383]
In the latest release (3.1.2) the project has no **Current Library Version** (which defaults to 0.0.0). I checked with this command: `otool -L Carthage/Build/iOS/SnapKit.framework/SnapKit `

P.S. from 3.0.2 in SnapKit's build settings the `current library version` is missing

**Comment by robertjpayne** [comment]
Closing because this issue does not follow the [Issue Template](https://github.com/SnapKit/SnapKit/blob/develop/ISSUE_TEMPLATE.md). If you feel this issue is important enough re-open and fill out the complete issue template that is preloaded.
