### ISSUE TITLE
invalid Current Library Version build setting

### ISSUE THREAD

**Issue by zetasq** [SnapKit/SnapKit#384]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.0
 SnapKit Version         | 3.0.2 and above
 Integration Method      | carthage
 

### Issue Description

In the latest release (3.1.2) the project has no Current Library Version (which defaults to 0.0.0). I checked with this command: otool -L Carthage/Build/iOS/SnapKit.framework/SnapKit

P.S. from 3.0.2 in SnapKit's build settings the current library version is missing

**Comment by robertjpayne** [comment]
@zetasq thanks for the issue, Xcode recommends leaving frameworks configured like this hence it is. Is there an actual build/integration issue you're experiencing because of it?

**Comment by zetasq** [comment]
@robertjpayne When I create a new Xcode project the default `Current Library Version` is set to 1. I have looked at other popular frameworks (like Alamofire, SwiftDate) they all have `Current Library Version` set to 1. My app crashes because of invalid library version the latest SnapKit release has (which is 0.0.0 now).

**Comment by robertjpayne** [comment]
@zetasq what version of Xcode are you using?

**Comment by zetasq** [comment]
@robertjpayne Xcode 8.2.1 (the latest version).

**Comment by zetasq** [comment]
@robertjpayne After I cleaned the DerivedData folder, my app can run : ). Seems it's the cache bug. But I still hope  the `Current Library Version` could be set to 1, so that other developers won't suffer my problem. Thank you for your patience.

**Comment by robertjpayne** [comment]
@zetasq I really have no idea why it broke, I'm 99% positive Xcode asked me to change that in 8.1 or 8.2! Closing this for now.
