### ISSUE TITLE
SnapKit taking automatic constaints which I did not given

### ISSUE THREAD

**Issue by hitendradeveloper** [SnapKit/SnapKit#385]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        |  10.0
 SnapKit Version         |  3.1.2
 Integration Method      |  cocoapods
 

### Issue Description

import UIKit

```
class LeftRightDetailsTableViewCell: UITableViewCell {

    enum ColorStyle {
        case normal
        case highlighted
        
        func valueBackgroundColor() -> UIColor {
            switch self {
            case .normal:
                return Theme.supportiveThemeColor
            case .highlighted:
                return Theme.mainThemeColor
            }
        }
        
        func valueLeftLable() -> UIColor {
            switch self {
            case .normal:
                return UIColor.black
            case .highlighted:
                return UIColor.white
            }
        }
        
        func valueRightLable() -> UIColor {
            switch self {
            case .normal:
                return UIColor.green
            case .highlighted:
                return UIColor.white
            }
        }
    }
    
    //MARK:- iVars -
    var colorStyle  : ColorStyle = ColorStyle.normal {
        didSet{
            self.backgroundColor = UIColor.yellow
            self.containerView.backgroundColor = colorStyle.valueBackgroundColor()
            self.containerView.backgroundColor = UIColor.lightGray
            self.leftLable.textColor = colorStyle.valueLeftLable()
            self.rightLable.textColor = colorStyle.valueRightLable()
        }
    }
    
    //MARK:- IBOutlet -
    
    //1
    lazy var containerView : UIView = {
        let view = UIView(frame: CGRect.zero)
        view.layer.cornerRadius = 4.0;
        view.layer.masksToBounds = true;
        return view;
    }()
    
    //2
    lazy var leftLable : UILabel = {
        let view = UILabel(frame: CGRect.zero)
        view.textColor = self.colorStyle.valueLeftLable();
        view.numberOfLines = 0;
        view.text = "init(coder:)\n has not\n been";
        
        return view
    }()
    
    //3
    lazy var rightLable : UILabel = {
        let view = UILabel(frame: CGRect.zero)
        view.textColor = self.colorStyle.valueRightLable();
        view.text = "test2";
        return view
    }()
    
    //MARK:- INIT
    
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: UITableViewCellStyle.default, reuseIdentifier: reuseIdentifier);
        self.addSubView()
        self.makeConstraints()
        self.commonInit()
    }
    
    
    init(ColorStyle: ColorStyle, reuseIdentifier: String?) {
        super.init(style: UITableViewCellStyle.default, reuseIdentifier: reuseIdentifier);
        self.addSubView()
        self.makeConstraints()
        self.commonInit()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func commonInit(){
        self.backgroundColor = UIColor.yellow
        self.containerView.backgroundColor = colorStyle.valueBackgroundColor()
        self.containerView.backgroundColor = UIColor.gray
        self.contentView.backgroundColor = UIColor.red
        self.leftLable.textColor = colorStyle.valueLeftLable()
        self.rightLable.textColor = colorStyle.valueRightLable()
    }
    
    
    
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

        // Configure the view for the selected state
    }
}

extension LeftRightDetailsTableViewCell : PSAutolayoutProgrammable {
    //MARK:- makeConstaints
    func addSubView() {
        
        self.contentView.addSubview(self.containerView)
        
        [self.leftLable,
         self.rightLable
            ].forEach { (view) in
                self.containerView.addSubview(view);
        }
    }
    
    func makeConstraints() {
        
        self.leftLable.snp.makeConstraints { (make) in
            make.top.equalTo(15);
            make.left.equalTo(20);
            make.right.equalTo(self.rightLable.snp.left).offset(-20)
        }
        
        self.rightLable.snp.makeConstraints { (make) in
            make.left.equalTo(self.leftLable.snp.right).offset(20)
            make.right.equalTo(self.contentView).offset(-20);
            make.centerY.equalTo(self.leftLable);
        }

        self.containerView.snp.updateConstraints { (make) in
            make.top.equalTo(self.contentView).offset(15)
            make.left.equalTo(self.contentView).offset(25)
            make.right.equalTo(self.contentView).offset(-25).priority(1000)
            make.bottom.equalTo(self.leftLable.snp.bottom).offset(15)
        }
        
        self.contentView.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.containerView).offset(15)
        }
        
        self.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.contentView)

        }
        
        
        
       
    }
}
```

Above is my custom cell code, i am using this to create left/right lable to show info.
![screen shot 2017-01-02 at 3 08 03 pm](https://cloud.githubusercontent.com/assets/9197369/21587010/4b0ee03c-d0fd-11e6-99a6-0e5599c05fec.png)

I am getting result show in above image.

view with red color is the default contentView of UITableViewcell.
view with yellow color is the background view of UITableViewCell.
gray view is my custom view create in this class LeftRightDetailsTableViewCell

I want red view with same width as yellow view so my gray view will also get proper width.
I want to stick left lable at left side and right lable at right side. but it is automatically setting size of gray lable as per the text of inner lables.

 as I am giving right constaint of leftLable, it messing the UI. This was working perfectly when I was using X-Code7 before one year.

Now again I am started working using snap kit but could not get expected result.
Kindly help me.

**Comment by robertjpayne** [comment]
@hitendradeveloper looks like you are using interface builder, do you have all the constraints in IB set as `Placeholder Only`?

Also what is `PSAutolayoutProgrammable`?

**Comment by robertjpayne** [comment]
Sorry also just to clarify do you mean SnapKit is adding unknown constraints or removing automatic ones?

**Comment by hitendradeveloper** [comment]
my custom protocol

```
protocol PSAutolayoutProgrammable {
    func addSubView()
    func makeConstraints()
}
```
> Also what is PSAutolayoutProgrammable?

**I didn't used InterfaceBuilder**
> looks like you are using interface builder, do you have all the constraints in IB set as Placeholder Only?


As per my constaints my right label should stick to right of gray view, but it is not.
So I think Snapkit removes some constraint or adding more constraint, I am not sure actually.
> Sorry also just to clarify do you mean SnapKit is adding unknown constraints or removing automatic ones?

**Comment by robertjpayne** [comment]
@hitendradeveloper the only thing SnapKit does is set `translatesAutoresizingMaskIntoConstraints = false` my guess is you're missing a width constraint on the containerView or the contentView sorry I can't help more than that.

**Comment by hitendradeveloper** [comment]
@robertjpayne I have tried by adding fixed width i.e. width `equalTo() `main screen's width, 
also tried to give width equal to cell's width, but didn't work for me,

I think width is not required because I have given `left` and `right` to the `containerView`
```
 self.containerView.snp.updateConstraints { (make) in
            make.top.equalTo(self.contentView).offset(15)
            make.left.equalTo(self.contentView).offset(25)
            make.right.equalTo(self.contentView).offset(-25).priority(1000)
            make.bottom.equalTo(self.leftLable.snp.bottom).offset(15)
        }
```

I just want to stick label to left and right label to right side

**Comment by ZeranLatte** [comment]
@hitendradeveloper I think I found your problem: ```
self.rightLable.snp.makeConstraints { (make) in
            make.left.equalTo(self.leftLable.snp.right).offset(20)
            **make.right.equalTo(self.contentView).offset(-20)**; // this line
            make.centerY.equalTo(self.leftLable);
        }
```
You set rightLabel's right edge with contentView, the code does exact what it is expected to do.
I think you mean containerView is the above line I marked
`make.right.equalTo(self.containerView).offset(-20)`

**Comment by hitendradeveloper** [comment]
@ZeranLatte  I also tried with the `make.right.equalTo(self.containerView).offset(-20)`
but no more improvements,
 I need the red with the same size of yellow view 
i.e. containerView with full size of cell, but because of some unwanted constraints it make the containerView smaller.

Thanks for your suggestion
Any help is appreciated.

**Comment by hitendradeveloper** [comment]
@robertjpayne Any updates on this ?

**Comment by ZeranLatte** [comment]
@hitendradeveloper If you don't add any constraints to the contentView(red) it should be same size as the cell. Usually we don't change contentView's constraint to its superView; you are free to add container view as contentView's subview to layout. You are not doing it correctly, please read carefully on how to use. These calls are not necessary to me.
```
self.contentView.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.containerView).offset(15)
        }
        
        self.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.contentView)
}
```

**Comment by hitendradeveloper** [comment]
@ZeranLatte These calls are necessary for me because
I am using self-sizing cells using table view automatic dimensions.
To make the cell with automatic height based on the content(text of left label) I have to update the bottom of the content view and cell both
```
self.contentView.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.containerView).offset(15)
        }
        
        self.snp.updateConstraints { (make) in
            make.bottom.equalTo(self.contentView)
}
```

I did the same before year ago with snap kit and it was working perfectly.

**Comment by robertjpayne** [comment]
@hitendradeveloper sorry this isn't really a SnapKit issue rather it's an auto-layout issue. iOS 10 made some changes to how constraints work with layout constraints. You may find some useful information here https://github.com/SnapKit/Masonry/issues/382 but generally speaking I don't have enough time to attend to Auto Layout specific questions.

Again I must reiterate here there is no *unwanted* constraints being generated by SnapKit (otherwise heaps of other users would have reported this and it'd be a massive issue) it's just your specific combination of constraints isn't accomplishing what you think it should and that is Auto Layout specific (you could make the constraints with the NSLayout* API's and it'd still be broken)

**Comment by robertjpayne** [comment]
Closing as I believe this is not a SnapKit issue and is inactive

**Comment by hitendradeveloper** [comment]
Can this help us ?

```
## Sending layoutIfNeeded to a view is not expected to move the view, but in earlier releases, if the view had translatesAutoresizingMaskIntoConstraints set to NO, and if it was being positioned by constraints, layoutIfNeeded would move the view to match the layout engine before sending layout to the subtree.
These changes correct this behavior, and the receiver’s position and usually its size won’t be affected by layoutIfNeeded.

Some existing code may be relying on this incorrect behavior that is now corrected. There is no behavior change for binaries linked before iOS 10, but when building on iOS 10 you may need to correct some situations by sending -layoutIfNeeded to a superview of the translatesAutoresizingMaskIntoConstraints view that was the previous receiver, or else positioning and sizing it before (or after, depending on your desired behavior) layoutIfNeeded.

Third party apps with custom UIView subclasses using Auto Layout that override layoutSubviews and dirty layout on self before calling super are at risk of triggering a layout feedback loop when they rebuild on iOS 10. When they are correctly sent subsequent layoutSubviews calls they must be sure to stop dirtying layout on self at some point (note that this call was skipped in release prior to iOS 10).
```

**Comment by ZeranLatte** [comment]
@hitendradeveloper is your code behave differently on iOS10 device and other versions below? If so then it's a iOS autoLayout intrinsic mechanism (maybe only affect tableview cells) not Snapkit. Please try it out first and figure out if the issue is dependent on the iOS version. So I think @robertjpayne points to the right direction, your problem is similar to SnapKit/Masonry#382 and [FDTemplateLayoutCell/issue242](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/issues/242). May need to set up contentView's edge first.
