### ISSUE TITLE
Cannot load underlying module

### ISSUE THREAD

**Issue by aeves313** [SnapKit/SnapKit#388]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ x] I have looked at the [Documentation](http://snapkit.io/docs)
* [ x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 8.2
 SnapKit Version         | 3.1.2
 Integration Method      | e.g. cocoapods
 

### Issue Description

I can get the pods into the project without having a dialogue box for Swift conversion; however, when I try to create an import statement (import SnapKit), I get a red error stating "Cannot load underlying module for 'SnapKit'". As mentioned earlier, I'm using iOS and Xcode 8.2, so this may not have been reached yet.

**Comment by robertjpayne** [comment]
@aeves313 have you:

1. Cleared your DerrivedData folder ~/Library/Developer/Xcode/DerrivedData
2. Ensured you are running latest version of Cocoapods
3. Cleared your Pods cache and re-installed SnapKit?
4. Cleaned and re-built your Xcode project?

Normally these integration issues is one of the above. If SnapKit is compiling fine into a .framework or .module on your system it's something to do with Xcode's build system or your integration method.

**Comment by aeves313** [comment]
I have done 2-4 many times, but the Derived Data approach was something I gave a try. Xcode still complains the same.

**Comment by robertjpayne** [comment]
@aeves313 hm I'm not really sure what to do, I've not heard of anyone else having issues it's likely just something specific to your machine / Xcode etc…

**Comment by robertjpayne** [comment]
Closing because I don't believe this is a SnapKit issue but rather an integration issue that is specific to dev machine/configuration.
