### ISSUE TITLE
I can't find the property of 'snp_topLayoutGuideTop'

### ISSUE THREAD

**Issue by JxbSir** [SnapKit/SnapKit#390]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 10.0
 SnapKit Version         | e.g. 3.1.2
 Integration Method      | e.g.cocoapods
 

### Issue Description

I can't find the property of 'snp_topLayoutGuideTop', where is it?

How can I use it in Snap_Kit 3.1.2

**Comment by robertjpayne** [comment]
@JxbSir see the Swift 3.0 migration guide https://github.com/SnapKit/SnapKit/blob/master/Documentation/SnapKit%203.0%20Migration%20Guide.md it has info about how the API's changed since older versions SnapKit running on Swift 2.3
