### ISSUE TITLE
can't update default existing constraint

### ISSUE THREAD

**Issue by zypsusu** [SnapKit/SnapKit#392]
I set up a label constraint:
 titleLabel.snp.makeConstraints { (make) in
            make.left.equalTo(self).offset(20)
            make.top.equalTo(self).offset(15)
            make.height.equalTo(14)
        }
when I get data to update UI, I write: 
titleLab?.snp.updateConstraints({ (make) in
                    make.width.lessThanOrEqualTo(220)
                })
now, running error:fatalError("Updated constraint could not find existing matching constraint to update: \(layoutConstraint)")  
I must write like this: 
 titleLabel.snp.makeConstraints { (make) in
            make.left.equalTo(self).offset(20)
            make.top.equalTo(self).offset(15)
            make.height.equalTo(14)
            make.width.lessThanOrEqualTo(180)
        }
The label's width constriant is default exisit,  Can you optimize this?  The  Masonry have no issue

**Comment by robertjpayne** [comment]
Closing because issue does not follow issue template.
