### ISSUE TITLE
The issues when dynamic change view constraints!!!

### ISSUE THREAD

**Issue by niepan131420** [SnapKit/SnapKit#394]
`###` New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

 [Layout] Unable to simultaneously satisfy constraints:
<private>

Will attempt to recover by breaking constraint 
<private>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2017-01-20 15:00:18.549606 ChengZhangBaoMac[12058:2297806] [Layout] Unable to simultaneously satisfy constraints:
<private>

Will attempt to recover by breaking constraint 
<private>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2017-01-20 15:00:18.550285 ChengZhangBaoMac[12058:2297806] [Layout] Unable to simultaneously satisfy constraints:
<private>

Will attempt to recover by breaking constraint 
<private>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.
2017-01-20 15:00:18.550841 ChengZhangBaoMac[12058:2297806] [Layout] Unable to simultaneously satisfy constraints:
<private>

Will attempt to recover by breaking constraint 
<private>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, set a symbolic breakpoint on LAYOUT_CONSTRAINTS_NOT_SATISFIABLE to catch this in the debugger.

**Comment by niepan131420** [comment]
above error code is the code win i just add one subview to superview:
userVideoView.snp.makeConstraints { (make) in
            make.edges.equalTo(backgroundImageView.snp.edges)
        }

this also have above error.
i use storyboard to create view and use snapkit to set constraints

**Comment by robertjpayne** [comment]
@niepan131420 do you have all your layout constraints in your storyboard set to "Placeholder Only"? Otherwise they will be added at runtime and conflict with SnapKit's.

**Comment by niepan131420** [comment]
@robertjpayne  no , i just add the view to storyboard and oulet them to the viewcontroller use snapkit to layout them

**Comment by robertjpayne** [comment]
@niepan131420 thats probably your issue then, you need to ensure you set Interface Builders constraints to placeholders.

**Comment by niepan131420** [comment]
ok i will try it, thank you

**Comment by robertjpayne** [comment]
Closing this as I believe this issue is not SnapKit related
