### ISSUE TITLE
make.center does not center view

### ISSUE THREAD

**Issue by ubest1** [SnapKit/SnapKit#395]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ *] I have looked at the [Documentation](http://snapkit.io/docs)
* [ *] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ *] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                                   ios
 Platform Version                     8.0
 SnapKit Version                      3.0.2
 Integration Method                cocoapods
 

### Issue Description

⚠️ in the swift 3.0 update area, you mentioned a current quirk where make.center.equalTo(otherView) places the view at (0,0) and that we should use make.center.equalToSuperview(). make.center.equalToSuperview() does the samething as well (places the view at (0,0).   ⚠️

**Comment by robertjpayne** [comment]
@ubest1 does your superview have a width/height > 0?
