### ISSUE TITLE
Updated constraint could not find existing matching constraint to update?

### ISSUE THREAD

**Issue by dylanshine** [SnapKit/SnapKit#398]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info
 Platform                | iOS
 Platform Version        | 10.0
 SnapKit Version         | 3.1.2
 Integration Method      | cocoapods
 

### Issue Description

I am trying to update a width constraint before doing a UIView animation. To my understanding, first you create your constraints:

```
statusBar.snp.makeConstraints { make in
    make.height.equalTo(5)
    make.top.equalTo(view.snp.bottom)
    make.leading.equalTo(view.snp.leading)
    make.width.equalTo(0)
}
```
Then in an animation function, I update the constraints and animate:

```
snp.updateConstraints {
    $0.width.equalToSuperview().multipliedBy(0.9)
}
updateConstraints()

UIView.animate(withDuration: 0.5) {
    self.layoutIfNeeded()
}
```
I have tried multiple configurations of setting up these constraints and am running into the same issue. Thank your help :)

**Comment by dylanshine** [comment]
Note my superview is valid with a width greater than 0.

**Comment by robertjpayne** [comment]
@dylanshine as per documentation the only part of a constraint you can modify in an `updateConstraints` block is the `constant`. Multipliers unfortunately are not part of the constant ( they are not mutable on NSLayoutConstraint )

In saying that this may be a possibility to support, the main reason is the matching of old constraint to be removed to the new constraint to be added isn't that difficult if *only* the multiplier/constants differ. It becomes impossible when you modify relations.

**Comment by dylanshine** [comment]
That makes sense, thank you!
