### ISSUE TITLE
Request: Make SnapKit compatible with Swift Package Manager

### ISSUE THREAD

**Issue by phrz** [SnapKit/SnapKit#399]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.2
 SnapKit Version         | 3.1.2
 Integration Method      | _Swift Package Manager_
 

### Issue Description

Some developers now want to move past Cocoapods and Carthage as the Swift Package Manager becomes a bigger player in dependency management.

SnapKit features a Package.swift file, but its file structure is incompatible with the Swift Package Manager. After adding the GitHub .git URL as a dependency to my Package.swift file, and running `swift build`, I receive the following error:

```
Cloning https://github.com/SnapKit/SnapKit.git
HEAD is now at ad35ec4 Prepare release
Resolved version: 3.1.2
error: the package has an unsupported layout, unexpected source file(s) found: ~/Repos/Calculator/Packages/SnapKit-3.1.2/Tests/Tests.swift
fix: move the file(s) inside a module
```

As I understand, making SnapKit compatible with SPM would require only superficial changes to the source to make it meet these file structure requirements — with no significant refactoring.

It would make my workflow that much simpler if I could add a line to my Package.swift and run `swift build` rather than relying on a third party package manager or manual installation.

**Comment by robertjpayne** [comment]
I'll try and get around to fixing it, just as a heads up I don't believe SPM supports iOS projects yet? How are you integrating it into your project?

**Comment by phrz** [comment]
I think SPM can be used for any Swift module, i.e. unit of code, regardless of platform. It is not integrated with Xcode yet, but all that means is you have to call `swift build` manually from the command line.

**Comment by robertjpayne** [comment]
@phrz that's correct but it always builds against the macOS SDK (if building on macOS) or against the Linux toolchain on Linux platforms.

There is no official way to build a module that can be loaded into an iOS app

**Comment by phrz** [comment]
You're very right! I hadn't seen this detail until I pored over every bit of the SPM documentation to see what you were saying. Sorry for the (currently) impossible request.

**Comment by LinusU** [comment]
It's actually possible now 🎉 with a bit of hacking 🔧 

ref:
- http://www.ralfebert.de/ios-examples/xcode/ios-dependency-management-with-swift-package-manager/
- https://github.com/j-channings/swift-package-manager-ios

Also, this library supports macOS as well, so that should be able to work with SPM

**Comment by LinusU** [comment]
PR is up 🎉 

#501
