### ISSUE TITLE
Compile issue.

### ISSUE THREAD

**Issue by cooldev727** [SnapKit/SnapKit#401]
I can't use SnapKit at Xcode 8.2.1
I added project as by using CocoaPod.

I am  getting following issue.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

pod 'SnapKit', '~> 3.1.2'

Please help me.
Thanks.

**Comment by robertjpayne** [comment]
Closing because issue does not follow issue template.
