### ISSUE TITLE
Updated constraint could not find existing matching constraint to update

### ISSUE THREAD

**Issue by DonYang** [SnapKit/SnapKit#402]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.2.1
 SnapKit Version         | 3.1.2
 Integration Method      | carthage
 

### Issue Description

Updated constraint could not find existing matching constraint to update
I make view like this

titleLbl.snp.makeConstraints { (make) in
  make.left.equalTo(tagLbl1).offset(5)
  make.top.equalTo(17)
  make.right.equalTo(-18)
}

update titleLbl like this
if isRight {
  titleLbl.snp.updateConstraints{ (make) in
    make.left.equalTo(tagLbl2)
  }  
} else {
  titleLbl.snp.updateConstraints{ (make) in
    make.left.equalTo(tagLbl1)
  } 
}

this is general requirement

**Comment by robertjpayne** [comment]
@DonYang I get what you're asking here but this isn't supported in SnapKit because the constraints are ambiguous.

You will need to use `remake` instead.
