### ISSUE TITLE
This is just a question, NOT BUG. About automatic import

### ISSUE THREAD

**Issue by madordie** [SnapKit/SnapKit#405]
When I used POD to introduce this library, I found that I only need to be introduced in a file once, you can use it in the whole project. So I am very curious how to achieve this effect. Can you guide how to configure it, please?

**Comment by robertjpayne** [comment]
Closing because this does not follow the issue template. Even for questions this is useful because of integration methods etc…

**Comment by madordie** [comment]
😭😭😭

**Comment by madordie** [comment]
😭😭😭
