### ISSUE TITLE
ios xcodebuild no such module 'SnapKit'

### ISSUE THREAD

**Issue by haoju-ios** [SnapKit/SnapKit#406]
platform: macOS 10.12.3  ios 10.2.1, Xcode 8.2.1
i drag the SnapKit.xcodeproj to my project and add the snapkit.framework to "embedded Binaries"
and then, simulator is good, iPhone is good, using xcode to archive is good。
but when i use script to archive a application
<img width="395" alt="2017-02-16 at 15 19" src="https://cloud.githubusercontent.com/assets/21197252/23012104/7f843652-f45f-11e6-992e-6378f557028e.png">

the script:
xcodebuild archive -project ${PROJECT_NAME}.xcodeproj -scheme "XXX" -configuration $configuration -archivePath "XXX.xcarchive"
xcodebuild -exportArchive -exportOptionsPlist ${EXPORT_OPTION} -archivePath “XX.xcarchive" -exportPath “XX" clean
 
after that i I tried some methods to solve the problem，but it did not work.

i tried to set iOS platform to SnapKit, then archive success

can you change a way that to support iOS，MacOS，tvOS?

Xcodebuild may not know what you want to support in one scheme.

Thanks!

**Comment by robertjpayne** [comment]
@haoju-ios I'm not really sure why it would do that -- the platform should be inherited from the primary xcodeproj target. Is it possibly you had a cached version in Derived Data or similar?

**Comment by haoju-ios** [comment]
@robertjpayne 
i clean my project and then delete the following Directories 
~/Library/Developer/Xcode/iOS\ DeviceSupport
~/Library/Developer/Xcode/DerivedData/ModuleCache
~/Library/Developer/Xcode/DerivedData
The problem is still not solved.
Apple's support for script package has always been very backward. Xcode8‘s Fault tolerance is very good, Script may find some mistakes in project。
i tried remove the snapkit from my project, set snapkit to ios platform, add snapkit and then archive success
if i don't change the project setting, just reset my changes to snapkit through git，
![image](https://cloud.githubusercontent.com/assets/21197252/23050576/2a704b70-f4fe-11e6-885e-3d78f43b8fd7.png)

archive failed！ 

if i don't add ios platform to snapkit, when i add snapkit to "embedded Binaries". Xcode shows i add a macos framework
![image](https://cloud.githubusercontent.com/assets/21197252/23050715/fca572aa-f4fe-11e6-9bee-b79c83e39ad4.png)

**Comment by robertjpayne** [comment]
@haoju-ios is it also added as a dependency of your project? The framework has been setup as a universal binary and should inherit these settings.

Sounds like a bug with `xcodebuild` to be honest as it works fine in Xcode...

**Comment by haoju-ios** [comment]
@robertjpayne 
![image](https://cloud.githubusercontent.com/assets/21197252/23051752/7de9b25c-f506-11e6-9fd5-a98102f34a9a.png)
![image](https://cloud.githubusercontent.com/assets/21197252/23051773/aa018040-f506-11e6-9182-5e0d09688e63.png)
![image](https://cloud.githubusercontent.com/assets/21197252/23051812/e2b7fbb2-f506-11e6-865e-a0ec589c04cf.png)
![image](https://cloud.githubusercontent.com/assets/21197252/23051847/29070ebe-f507-11e6-9c46-0a555e0f574b.png)
This is almost all my Settings.
Also I think it is a bug of xcodebuild. but i can't require Apple to fix it.

**Comment by robertjpayne** [comment]
@haoju-ios I'm not really sure what to do for you, it's specific to xcodebuild and I don't really want to split the project back into two targets as it was causing a mess of development issues.

Carthage seems to work fine,have you tried maybe using Carthage to build/integrate your 3rd party frameworks?

**Comment by haoju-ios** [comment]
@robertjpayne 
ok! thanks for your help!
I will try it！
