### ISSUE TITLE
Unable to install SnapKit 3.2.0 using CocoaPods

### ISSUE THREAD

**Issue by klfrank** [SnapKit/SnapKit#407]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |ios
 Platform Version        | e.g. 9.0
 SnapKit Version         | e.g. 3.2.0
 Integration Method      | cocoapods
 

### Issue Description

I'm unable to install SnapKit version 3.2.0 using Cocoapods

```
Unable to satisfy the following requirements:

- `SnapKit (~> 3.2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SnapKit (~> 3.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I've already updated the repo. If I use only `pod 'SnapKit'` , it installs me the 3.1.2 version. I'm using cocoapods version 1.1.1

**Comment by robertjpayne** [comment]
@klfrank thanks for this, I forgot to push it to trunk should be good now after a `pod repo update` 👍
