### ISSUE TITLE
updateConstraints multipliedBy crash  Updated constraint could not find existing matching constraint to update

### ISSUE THREAD

**Issue by SANZOGENJO** [SnapKit/SnapKit#408]
let bgView = UIView()
        bgView.backgroundColor = UIColor.red
        self.view.addSubview(bgView)
        bgView.snp.makeConstraints { (make) in
            make.width.equalTo(self.view)
            make.height.equalTo(50)
            make.center.equalTo(self.view)
        }

after 
 bgView.snp.updateConstraints { (make) in
            make.width.equalTo(self.view).multipliedBy(0.5)
        }
it will crash with log
fatal error: Updated constraint could not find existing matching constraint to update: <SnapKit.LayoutConstraint:0x6080000bd100@ViewController.swift#38 UIView:0x7f9383d05c30.width == UIView:0x7f9383c0a9e0.width * 0.5>: file /Users/sss/Desktop/dddd/Pods/SnapKit/Source/Constraint.swift, line 265

**Comment by robertjpayne** [comment]
Closing because issue does not follow issue template.
