### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1170197998** [SnapKit/SnapKit#410]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 3.2.0
 Integration Method      | e.g. cocoapods
 

### Issue Description

once add snapkit to project,
project will error,info:叉子会报错Could not build module 'ASIHTTPRequest'
delete snapkit then OK
why?

**Comment by robertjpayne** [comment]
As per contributing guidelines closing due to issue template not being filled out.

**Comment by 1170197998** [comment]
use framework!  cause
