### ISSUE TITLE
UITableViewCellHeight Difference

### ISSUE THREAD

**Issue by TouchLiang** [SnapKit/SnapKit#411]
### New Issue Checklist

* [√] I have looked at the [Documentation](http://snapkit.io/docs)
* [√] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 3.1.2
 Integration Method      | e.g. cocoapods
 

###### my code
        titleLabel.snp.makeConstraints { (make) in
            make.top.bottom.equalTo(self)
            make.right.left.equalTo(self)
            make.height.equalTo(55.8)
        }

###### output messages
```
2017-03-08 14:34:16.448632 test_snpkit[29431:1077881] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<SnapKit.LayoutConstraint:0x6000002a1c20@ViewController.swift#70 UILabel:0x7ff73d610a20.top == test_snpkit.TestCell:0x7ff73e81ba00.top>",
    "<SnapKit.LayoutConstraint:0x6000002a1ce0@ViewController.swift#70 UILabel:0x7ff73d610a20.bottom == test_snpkit.TestCell:0x7ff73e81ba00.bottom>",
    "<SnapKit.LayoutConstraint:0x6000002a1e00@ViewController.swift#72 UILabel:0x7ff73d610a20.height == 55.8>",
    "<NSLayoutConstraint:0x600000289e70 'UIView-Encapsulated-Layout-Height' test_snpkit.TestCell:0x7ff73e81ba00'testCell'.height == 55.6667   (active)>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x6000002a1e00@ViewController.swift#72 UILabel:0x7ff73d610a20.height == **55.8**>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

> why are two numbers difference? (55.8 & 55.667)

**Comment by robertjpayne** [comment]
@TouchLiang this `UIView-Encapsulated-Layout-Height` is causing your bug, I believe this was something new that happened with iOS 10 but I'd recommend not using any of the built in views from UITableViewCell and ensuring you add/bind stuff to the `contentView` not the cell itself!

**Comment by ZeranLatte** [comment]
@TouchLiang He is using iOS 8 ?. @TouchLiang But yes, you should use contentView

**Comment by robertjpayne** [comment]
Closing this because I don't believe this is an issue with SnapKit rather just an iOS 10 change. Re-open with additional information if you believe it is a SnapKit issue.
