### ISSUE TITLE
Leaks on Xcode 8.3

### ISSUE THREAD

**Issue by memoriesofsnows** [SnapKit/SnapKit#413]
I use Instruments to check leaks.
It is OK on Xcode 8.2.1，but it will leaks on Xcode8.3.
My English is poor，hope you understand.
![snp](https://cloud.githubusercontent.com/assets/17523689/24740005/8c28513e-1ad1-11e7-89aa-ea911f24b27a.png)

**Comment by robertjpayne** [comment]
Related to #363 note that this is an instruments bug but if you watch your app's memory over a long period of time it will never grow.

**Comment by robertjpayne** [comment]
Closing this as I don't believe this is an issue and it's misleading to anyone looking at the issue tracker!

**Comment by memoriesofsnows** [comment]
Thanks for your answer!
