### ISSUE TITLE
How to use SnapKit 3.2.0 in my project with Xcode8.3 and Swift3.1?

### ISSUE THREAD

**Issue by cly6226700** [SnapKit/SnapKit#414]
### New Issue Checklist

* [√] I have looked at the [Documentation](http://snapkit.io/docs)
* [√] I have read the [F.A.Q.](http://snapkit.io/faq)
* [√] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.3
 SnapKit Version         | 3.2.0
 Integration Method      | carthage
 

### Issue Description
How to use SnapKit 3.2.0 in my project with Xcode8.3 and Swift3.1?
I update Xcode and convert project , and get the Error "Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1"

**Comment by robertjpayne** [comment]
@cly6226700 you probably need to re-build your Carthage frameworks?

**Comment by cly6226700** [comment]
@robertjpayne Thanks for your answer, I have dealt with this Error.Thanks again!
