### ISSUE TITLE
updateConstraints lead to crash

### ISSUE THREAD

**Issue by victor2109** [SnapKit/SnapKit#415]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

If I do this, it will lead to crash 

==> my code
returnButton.snp.updateConstraints { (make) in
            make.centerX.equalTo(closeBtn.snp.centerX).offset(-margin)
 }

===>>> snapkit error

for layoutConstraint in layoutConstraints {
                let existingLayoutConstraint = existingLayoutConstraints.first { $0 == layoutConstraint }
                guard let updateLayoutConstraint = existingLayoutConstraint else {
                    fatalError("Updated constraint could not find existing matching constraint to update: \(layoutConstraint)")
                }

                let updateLayoutAttribute = (updateLayoutConstraint.secondAttribute == .notAnAttribute) ? updateLayoutConstraint.firstAttribute : updateLayoutConstraint.secondAttribute
                updateLayoutConstraint.constant = self.constant.constraintConstantTargetValueFor(layoutAttribute: updateLayoutAttribute)
            }

**Comment by robertjpayne** [comment]
See the error message `fatalError("Updated constraint could not find existing matching constraint to update: (layoutConstraint)")` you are attempting to update a constraint that does not match an existing constraint.

If you have already used `makeConstraints` more than once you cannot use `updateConstraints` on the same view to create new constraints (only to update existing ones).

**Comment by sosoyososo** [comment]
Here is my test code , this will crash on call ``` func ==(lhs: LayoutConstraint, rhs: LayoutConstraint) -> Bool ```

Xcode 8.2.1
macOS 10.12
iOS 10.2
SnapKit 3.2.0

```
class ViewController: UIViewController {

    var testView = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let button = UIButton()
        button.backgroundColor = UIColor.gray
        view.addSubview(button)
        button.snp.makeConstraints { (make) in
            make.centerX.equalToSuperview()
            make.size.equalTo(CGSize(width: 100, height: 100))
            make.bottom.equalTo(-20)
        }
        button.addTarget(self, action: #selector(ViewController.update), for: UIControlEvents.touchUpInside)
    }
    
    func update() {
        if testView.superview == nil {
            let container = UIView()
            container.backgroundColor = UIColor.init(white: 0, alpha: 0.45)
            view.addSubview(container)
            container.snp.makeConstraints({ (make) in
                make.edges.equalTo(UIEdgeInsetsMake(0, 0, 200, 0))
            })
            testView.backgroundColor = UIColor.red
            container.addSubview(testView)
            testView.snp.makeConstraints { (make) in
                make.left.right.equalTo(0)
                make.height.equalTo(100)
                make.top.equalTo(-100)
            }
            self.view.layoutIfNeeded()
            
            testView.snp.updateConstraints { (make) in
                make.top.equalTo(0)
            }
            UIView.animate(withDuration: 0.25) {
                self.view.layoutIfNeeded()
            }
        } else {
            testView.snp.updateConstraints { (make) in
                make.top.equalTo(-100)
            }
            UIView.animate(withDuration: 0.25, animations: {
                self.view.layoutIfNeeded()
            }, completion: { (_) in
                self.testView.superview?.removeFromSuperview()
                self.testView.removeFromSuperview()
            })
        }
    }
}
```

**Comment by sosoyososo** [comment]
I found when i use ``` testView.snp.remakeConstraints ``` replace ``` testView.snp.makeConstraints ``` will go around this crash which behavior is different from the previous version 2.x and not mentioned in http://snapkit.io/docs/ .  Hope it will make some help.
