### ISSUE TITLE
Feature request: add aspect ratio "helper" method

### ISSUE THREAD

**Issue by fcy** [SnapKit/SnapKit#417]
I've seen some old issues with questions about aspect ratio and if I understood correctly the reason there no SnapKit method for it is because there is no equivalent API on AutoLayout. My question is are you against adding a method like the following (naming TBD)?

```
profileImageView.snp.makeConstraint { make in 
    make.aspectRatio(1, by: 1) // square. or aspectRatio(16, by: 9)
}
```

that would internally be the same as:

```
profileImageView.snp.makeConstraint { make in 
    make.width.equalTo(profileImageView.snp.height).multipliedBy(1 / 1)
}
```

The benefit is that it makes the intent of the constrain very clear.

If this is something you'd add to the project I can create a PR.

**Comment by robertjpayne** [comment]
@fcy It's an interesting idea, I'm sort of against bloating SnapKit's API's with too much convenience, while useful I don't think there are that many instances where one needs to do aspect ratio pinning to warrant a top level API.

Instead it's easy to add extensions to protocols/classes that DSL works from and keep it application specific.

It may be a case where I need to add a `Contrib` folder with additional API's and helpers that are not part of the core package.

**Comment by robertjpayne** [comment]
@fcy my take on it is that I want SnapKit to closely mirror Auto Layout. Because if one comes into a new project that uses SnapKit and the original author is gone if there are tons of helpers it's even more confusing than just starting with the basics.

Most of SnapKit's API's read well with their intention `make left equal to right offset 100` etc… and this is a core goal because layout code is verbose and becomes lengthy and hard to understand visually when reading.

**Comment by fcy** [comment]
That makes sense and I had a feeling this was the way the project wanted to go, that is why I started by asking about it. I ended up adding an extension to `ConstraintMaker`:

```
extension ConstraintMaker {
    public func aspectRatio(_ x: Int, by y: Int, self instance: ConstraintView) {
        self.width.equalTo(instance.snp.height).multipliedBy(x / y)
    }
}
```

```
        profileImageView.snp.makeConstraints { make in
            make.aspectRatio(1, by: 1, self: profileImageView)
        }
```

The only thing that bothers me is that I have to pass a reference to the view itself, I couldn't find a way to reference the view from the maker.

Any tips on how this could be done better?

**Comment by dev4dev** [comment]
@fcy maybe something like this?

``` swift
extension ConstraintMaker {
	public func aspectRatio(_ x: Int, by y: Int) {
		if let view = item as? ConstraintView {
			self.width.equalTo(view.snp.height).multipliedBy(x / y)
		} else {
			print("You can't use this on non UIView(\(item)) item")
		}
	}
}
```

**Comment by gsempe** [comment]
@dev4dev unfortunately item is private. Do you think of any other way to workaround this?

**Comment by saxahan** [comment]
> 
public func aspectRatio(_ x: Int, by y: Int, self instance: ConstraintView) {
        self.width.equalTo(instance.snp.height).multipliedBy(x / y)
    }
>

**Comment by richschonthal** [comment]
It seems to me you should also try to mirror what Interface Builder provides since you are providing an easy, more high-level method of coding constraints and since IB provides an "aspect ratio" constraint, you should provide one as well.

**Comment by joeljfischer** [comment]
I would also like to see this. This is often used, for example, making the width of an image in a tableview cell match the height after setting the height constraints.

**Comment by ShivaHuang** [comment]
I prefer the following style

```swift
profileImageView.snp.makeConstraint { make in 
    make.aspectRatio.equalTo(CGSize(width:1, height: 1)) // square. or CGSize(width:16, height: 9)
}
```

But this may cause some exceptions that should be forbidden, such as

```swift
profileImageView.snp.makeConstraint { make in 
    make.aspectRatio.equalTo(CGSize(width:1, height: 1)).offset(10) // offset makes no sense for aspect ratio
    make.aspectRatio.equalTo(CGSize(width:1, height: 1)).multipliedBy(2) // multipliedBy and dividedBy make no sense for aspect ratio
}
```

I've started reading the code base, any comments are welcome.

**Comment by JuniperPhoton** [comment]
> That makes sense and I had a feeling this was the way the project wanted to go, that is why I started by asking about it. I ended up adding an extension to `ConstraintMaker`:
> 
> ```
> extension ConstraintMaker {
>     public func aspectRatio(_ x: Int, by y: Int, self instance: ConstraintView) {
>         self.width.equalTo(instance.snp.height).multipliedBy(x / y)
>     }
> }
> ```
> 
> ```
>         profileImageView.snp.makeConstraints { make in
>             make.aspectRatio(1, by: 1, self: profileImageView)
>         }
> ```
> 
> The only thing that bothers me is that I have to pass a reference to the view itself, I couldn't find a way to reference the view from the maker.
> 
> Any tips on how this could be done better?

Should x & y be Double or CGFloat?

**Comment by alexanderkhitev** [comment]
Hey! Do we have any updates? Thanks!

**Comment by robertjpayne** [comment]
Will be possible in next release via your own extensions due to #693
