### ISSUE TITLE
Xcode Autocomplete not working consistently <<error type>>

### ISSUE THREAD

**Issue by kevinmann** [SnapKit/SnapKit#421]
* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.0
 SnapKit Version         | 3.2.0
 Xcode Version         | 8.3.2
 Integration Method      | carthage
 

### Issue Description

Since updating Xcode and Snapkit I am have trouble with the Autocomplete just with Snapkit. It works within a function as this image shows:

![screen shot 2017-04-30 at 14 09 26](https://cloud.githubusercontent.com/assets/1014663/25584741/2761aa8a-2e8f-11e7-8dd8-5228e2636021.jpg)

However when I am trying to use it within a declaration block it no longer works and I get an error which looks like this:

![screen shot 2017-04-30 at 14 10 20](https://cloud.githubusercontent.com/assets/1014663/25584846/965969b4-2e8f-11e7-88e5-9b6a31072c0a.jpg)
 
I get the error type issue in different places. Sorry I can't be overly specific but it happens in random places often.  I have tried updating again, and downgrading Xcode to 8.2 but I still get the issues. I have also removed and re-added the frameworks.

**Comment by robertjpayne** [comment]
@kevinmann unfortunately this is an Xcode and indexer issue, I suggest clearing derived data and restarting Xcode. There's nothing I can do to really help out with this.

**Comment by robertjpayne** [comment]
Closing this as I don't believe this is a SnapKit issue per-se, just an Xcode indexer issue.

**Comment by inrtgdje** [comment]
I also  get the error type issue  in Xcode 10  SnapKit 4.0.1, deployment  iOS 10.0

**Comment by Donny1995** [comment]
same there
