### ISSUE TITLE
memory leaks 3.2.0

### ISSUE THREAD

**Issue by haoju-ios** [SnapKit/SnapKit#422]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.3.1
 SnapKit Version         | 3.2.0
 Integration Method      | carthage
 

### Issue Description
```swift
import UIKit
import SnapKit

class ViewController: UIViewController {
    var testImageView: TestView = TestView()
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

class TestView: UIView {
    var imageView: UIImageView
    
    override init(frame: CGRect) {
        imageView = UIImageView()
        super.init(frame: frame)
        self.addSubview(imageView)
        imageView.snp.makeConstraints { (make) in
            make.top.equalTo(20)
            make.left.equalTo(20)
            make.width.equalTo(50)
            make.height.equalTo(50)
        }
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```
Create a "Single View Application" and add that code will cause memory leaks.
i want to fix this in my project,(give a frame when testImageView init)
but in the tableViewCell, i can not do it.
![image](https://cloud.githubusercontent.com/assets/21197252/25650530/2279f090-3010-11e7-8529-72eab5122cd1.png)
![image](https://cloud.githubusercontent.com/assets/21197252/25650549/4d9c3e68-3010-11e7-95e8-318e1a632656.png)

**Comment by robertjpayne** [comment]
See #310 this isn't really a SnapKit issue it's a Swift issue but mostly it's just instruments if you watch your app's allocations these don't persist.
