### ISSUE TITLE
How to use UICollectionViewCell？

### ISSUE THREAD

**Issue by workwing** [SnapKit/SnapKit#423]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
This issue doesn't follow the issue template, there is no description and questions are best suited for StackOverflow as you'll have a wider audience that can assist.
