### ISSUE TITLE
it's not work

### ISSUE THREAD

**Issue by linger997** [SnapKit/SnapKit#428]
private var backMainView :UIView?
    func createRedBadge() {
        backMainView = UIView()
        self.view.addSubview(backMainView!)
        backMainView?.snp.makeConstraints({ (make) in
            make.left.right.equalTo(self.view)
            make.height.equalTo(49)
            make.bottom.equalTo(self.view)
        })
        let count = self.viewControllers?.count
        let multiplie = 1.0/Double(count!)
        var tmpV :UIView?
        for i in 0..<count! {
            let placeView = UIView()
            placeView.backgroundColor = UIColor.orange
            backMainView?.addSubview(placeView)
            placeView.snp.makeConstraints({ (make) in
                make.top.equalTo(0)
                make.height.equalTo(backMainView!)
                make.width.equalTo(backMainView!).multipliedBy(multiplie)
                if tmpV != nil {
                    make.left.equalTo((tmpV?.snp.right)!)
                }
            })
            let redBadge = UIView()
            redBadge.layer.masksToBounds = true
            redBadge.layer.cornerRadius  =  5
            redBadge.tag = 10 + i
            redBadge.backgroundColor = UIColor.blue
            placeView.addSubview(redBadge)
            redBadge.snp.makeConstraints({ (make) in
                make.width.height.equalTo(10)
                make.centerX.centerY.equalTo(0)
            })
            tmpV = placeView
        }
    }

**Comment by robertjpayne** [comment]
Closing as per the contributing guidelines this issue does not follow the issue template.
