### ISSUE TITLE
Snapkit scroll view doesn't work

### ISSUE THREAD

**Issue by sozman** [SnapKit/SnapKit#429]
* [*] I have looked at the [Documentation](http://snapkit.io/docs)
* [*] I have read the [F.A.Q.](http://snapkit.io/faq)
* [*] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### My scroll view doesn't work

It'my code

    var counter = 0
    var timer = Timer()

    let scrollView = UIScrollView()
    let contentView = UIView()
    let section1 = UIView()
    let bgImage = UIImageView()
    let s1yazi = UILabel()
    let section2 = UIView()
    let s2Baslik = UILabel()
    let s2yazi = UILabel()
    let s2Image = UIImageView()
    let section3 = UIView()
    let s3Baslik = UILabel()
    let s3View1 = UIView()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        view.addSubview(scrollView)
        scrollView.snp_makeConstraints { (make) in
            make.edges.equalTo(view).inset(UIEdgeInsetsMake(25, 0, 0, 0))

        }

        scrollView.addSubview(contentView)
        contentView.snp_makeConstraints { (make) in

            make.top.bottom.equalTo(scrollView)

            make.left.right.equalTo(view)

            // => IMPORTANT: this makes the width of the contentview static (= size of the screen), while the contentview will stretch vertically
        }

        contentView.addSubview(section1)
        section1.snp_makeConstraints { (make) in
            make.left.right.equalTo(contentView)
            make.height.equalTo(240)
        }

        section1.addSubview(bgImage)
        bgImage.image = UIImage(named: "bg.png")
        bgImage.snp_makeConstraints { (make) in
            make.left.right.equalTo(section1)
            make.top.equalTo(contentView) 
            make.height.equalTo(185)
        }

        section1.addSubview(s1yazi)
        s1yazi.textColor = UIColor.white
        s1yazi.text = "Dinliyoruz"
        s1yazi.font = s1yazi.font.withSize(40)
        s1yazi.textAlignment = .center
        s1yazi.snp_makeConstraints { (make) in
            make.leftMargin.equalTo(20)
            make.topMargin.equalTo(85)
        }

        contentView.addSubview(section2)
        section2.snp_makeConstraints{(make) in
            make.left.right.equalTo(contentView)
            make.height.equalTo(360)
            make.top.equalTo(section1.snp_bottom)
        }

        s2Baslik.textColor = UIColor.black
        s2Baslik.text = "İş Siteleri Yaratmanın En İyi Yolu  Çekici Siteler"
        s2Baslik.font = s2Baslik.font.withSize(20)
        s2Baslik.font = s2Baslik.font.bold()
        s2Baslik.numberOfLines = 2
        s2Baslik.textAlignment = .center
        section2.addSubview(s2Baslik)
        s2Baslik.snp_makeConstraints{(make) in
            make.left.right.equalTo(section2)
            make.top.equalTo(section2)
            make.height.equalTo(100)

        }

        s2yazi.textColor = UIColor.black
        s2yazi.text = "Discover elegant solution for your online business fast, reliable, affordable."
        s2yazi.font = s2yazi.font.withSize(10)
        s2yazi.numberOfLines = 2
        s2yazi.textAlignment = .center
        section2.addSubview(s2yazi)
        s2yazi.snp_makeConstraints{(make) in
            make.left.right.equalTo(section2)
            make.top.equalTo(s2Baslik.snp_bottom)
            make.height.equalTo(65)

        }

        section2.addSubview(s2Image)
        s2Image.image = UIImage(named: "bizPic.png")
        s2Image.snp_makeConstraints { (make) in
            make.left.right.equalTo(section2) 
            make.top.equalTo(s2yazi.snp_bottom)
            make.height.equalTo(185)
        }

        section3.backgroundColor = UIColor.black
        contentView.addSubview(section3)
        section3.snp_makeConstraints{(make) in
            make.left.right.equalTo(contentView)
            make.top.equalTo(section2.snp_bottom)
        }

        s3Baslik.textColor = UIColor.black
        s3Baslik.text = "Mutlu Müşteriler"
        s3Baslik.font = s3Baslik.font.withSize(20)
        s3Baslik.font = s3Baslik.font.bold()
        s3Baslik.numberOfLines = 2
        s3Baslik.textAlignment = .center
        section3.addSubview(s3Baslik)
        s3Baslik.snp_makeConstraints{(make) in
            make.left.right.equalTo(section3)
            make.top.equalTo(section3)
            make.height.equalTo(100)

        }

        s3View1.backgroundColor = UIColor.black
        section3.addSubview(s3View1)
        s3View1.snp_makeConstraints{(make) in
            make.left.right.equalTo(section3)
            make.top.equalTo(s3Baslik.snp_bottom)
            make.height.equalTo(90)
        }

**Comment by robertjpayne** [comment]
@sozman the issue tracker isn't the best place for questions like this (Stackoverflow with SnapKit tag is better), from a quick glance it's because you don't have any view that is pinned to the bottom of `contentView` so your content view has no height.
