### ISSUE TITLE
Crashing when updateConstraints

### ISSUE THREAD

**Issue by cs-joao-souza** [SnapKit/SnapKit#431]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 10.3
 SnapKit Version         | e.g. 3.2.0
 Integration Method      | e.g. cocoapods
 

### Issue Description

I can not update the constraint.
I've create the constraints like this

```
self.valueView.snp.makeConstraints { (make) in
      make.top.equalToSuperview()
      make.leading.equalToSuperview()
      make.bottom.equalToSuperview()
      make.width.equalTo(self.snp.width).multipliedBy(0)
    }
```

And updating the width constraint with this

```
self.valueView.snp.updateConstraints { (make) in
      make.width.equalTo(self.snp.width).multipliedBy(percentage)
    }
```

And it gives me the error
`
     fatalError("Updated constraint could not find existing matching constraint to update: \(layoutConstraint)")`

**Comment by robertjpayne** [comment]
@cs-joao-souza you cannot change the multiplier on a constraint, only the constant (This is an auto layout limitation).

You'll need to use remake instead and re-add all of the constraints.

**Comment by cs-joao-souza** [comment]
@robertjpayne i solved it using remakeConstraints. Thank you very much.

I'm going to close it.

**Comment by iPermanent** [comment]
another issue, when I use 
make.width.equalTo(self).multipliedBy(progress ?? 0)
it crashes, however when I use the code below:
make.width.equalTo(self.snp.width).multipliedBy(progress ?? 0)
it works fine, I always use remake
