### ISSUE TITLE
Can I submit PR for adding topLayoutGuide Constraint using SnapKit?

### ISSUE THREAD

**Issue by anmolmalhotra** [SnapKit/SnapKit#435]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. iOS
 Platform Version        | e.g. 10.0
 SnapKit Version         | e.g. 3.2.0
 Integration Method      | e.g. cocoapods
 

### Issue Description

This is not an issue, just a enhancement for documentation. I have started using SnapKit from tomorrow only and I didn't find anywhere in documentation or FAQs about how to align to bottom of topLayoutGuide.
I used this:
```
make.top.equalTo(topLayoutGuide.snp.bottom)
```

Just wanted to ask can I submit PR for this on documentation?

**Comment by robertjpayne** [comment]
@anmolmalhotra I would happily merge a PR to documentation anytime!

**Comment by anmolmalhotra** [comment]
Thank you! Submitting it now. It'll be my first PR ever. 💯

**Comment by robertjpayne** [comment]
@anmolmalhotra no worries! Thanks for submitting it!
