### ISSUE TITLE
How to use snapkit 3 in iOS 8

### ISSUE THREAD

**Issue by shyh5** [SnapKit/SnapKit#443]
Will snapkit 3 crash under iOS 8 ？？？？

**Comment by robertjpayne** [comment]
@shyh5 Probably won't work, I believe I dropped support for iOS 8 early this year. It shouldn't be impossible to re-factor it though if your really need to go back to iOS 8?

**Comment by shyh5** [comment]
Yeah，Our company's project is the least supported version of iOS 8.2，In China, many companies supported iOS 8 !!! thank you

**Comment by nunojfg** [comment]
Recently the company app Im developing dropped support for iOS8, but until now even SnapKit 4.0.0 worked on iOS8.
