### ISSUE TITLE
Feature request: constraint equal/lessThanOrEqual/greaterThanOrEqual/ToSuperviewMargin

### ISSUE THREAD

**Issue by bernikovich** [SnapKit/SnapKit#444]
Hello guys.
Looks like it's very common way to write following code (or unwrap superview):

```
button.snp.remakeConstraints {
      $0.centerX.equalTo(view.snp.trailing)
      $0.centerY.equalTo(view.snp.top)
      $0.width.height.equalTo(40.0)
    }
```

It will be cool if you can implement something like this to prevent manual pointing to target's superview.

```
button.snp.remakeConstraints {
      $0.centerX.equalToSuperview(trailing)
      $0.centerY.equalToSuperview(top)
      $0.width.height.equalTo(40.0)
    }
```
According to current implementation this ConstraintAttributes should be public or we should create another OptionSet abstraction.

**Comment by robertjpayne** [comment]
@bernikowich currently you should be able to do this pretty easily with extensions right? I'm against expanding the API too much just for convenience that may confuse some users (I like to keep it as simple as possible and try to keep convenience accessors down).

**Comment by bernikowich-cedoni** [comment]
@robertjpayne looks like it's impossible to do this with extensions. :(

**Comment by vrujbr** [comment]
Why would you say that?
```
public extension ConstraintMakerRelatable {
    @discardableResult
    public func equalToSuperview(_ attribute: SnpAttribute, file: String = #file, _ line: UInt = #line) -> ConstraintMakerEditable {
        guard let superview = self.description.item.superview else {
            fatalError("Expected superview but found nil when attempting make constraint `equalToSuperview`.")
        }
        let otherConstraint = ConstraintItem(target: superview, attributes: ConstraintAttributes(rawValue: attribute))
        return self.relatedTo(otherConstraint, relation: .equal, file: file, line: line)
    }
}

//Public and nonenum ConstraintAttributes
public typealias SnpAttribute = UInt
public let leading: SnpAttribute = ConstraintAttributes.leading.rawValue
public let trailing: SnpAttribute = ConstraintAttributes.trailing.rawValue
...
```
And you use it like you wanted to `make.centerX.equalToSuperview(leading)` only its ugly as hell.

If you didn't mind using it with dot `make.centerX.equalToSuperview(.leading)` and somebody (@robertjpayne) made `ConstraintAttributes` public, it would be a different story ;-)

**Comment by matt-holden** [comment]
@vrujbr in the example you made above:  `self.description` is not `public`, so that code does not compile...  

I ran into the same issue, I was hoping to make allow `make.edges.equalToSuperviewMargins()`, but that does not appear possible
