### ISSUE TITLE
remakeConstraints possibly leaving constraints behind

### ISSUE THREAD

**Issue by tcurdt** [SnapKit/SnapKit#447]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.3.1
 SnapKit Version         | 3.2.0
 Integration Method      | cocoapods
 

### Issue Description

I am animating a big layout change as follows. I am basically recreating all constraints.

    override func willTransition(to newCollection: UITraitCollection, with coordinator: UIViewControllerTransitionCoordinator) {
        super.willTransition(to: newCollection, with: coordinator)

        coordinator.animate(alongsideTransition: { _ in
            self.updateConstraintsForTraitCollection(newCollection)
            self.view.setNeedsLayout()
        }, completion: nil)
    }

    func updateConstraintsForTraitCollection(_ collection: UITraitCollection) {

        let wide = size.width >= size.height
        if wide {
            layoutHorizotal()
        } else {
            layoutVertical()
        }
    }

    override func layoutVertical() {
        let superview = view!
        imageView.snp.remakeConstraints { make in
            make.top.equalTo(superview).offset(20)
            make.centerX.equalTo(headingLabel)
            make.width.equalTo(headingLabel).multipliedBy(0.3)
            make.height.equalTo(imageView.snp.width).multipliedBy( 200.0 / 200.0 )
        }
        headingLabel.snp.remakeConstraints { make in
            make.top.equalTo(imageView.snp.bottom).offset(20)
            make.left.equalTo(superview).offset(20)
            make.right.equalTo(superview).offset(-20)
        }
        textLabel.snp.remakeConstraints { make in
            make.top.equalTo(headingLabel.snp.bottom).offset(20)
            make.left.right.equalTo(headingLabel)
        }
        tableView.snp.remakeConstraints { make in
            make.top.equalTo(textLabel.snp.bottom).offset(20)
            make.left.right.equalTo(headingLabel)
            make.bottom.equalTo(superview).offset(-20)
        }
    }

    override func layoutHorizotal() {
        let superview = view!
        imageView.snp.remakeConstraints { make in
            make.top.equalTo(superview).offset(20)
            make.centerX.equalTo(headingLabel)
            make.width.equalTo(headingLabel).multipliedBy(0.3)
            make.height.equalTo(imageView.snp.width).multipliedBy( 200.0 / 200.0 )
        }
        headingLabel.snp.remakeConstraints { make in
            make.top.equalTo(imageView.snp.bottom).offset(20)
            make.left.equalTo(superview).offset(20)
            make.right.equalTo(tableView.snp.left).offset(-20)
        }
        textLabel.snp.remakeConstraints { make in
            make.top.equalTo(headingLabel.snp.bottom).offset(20)
            make.left.right.equalTo(headingLabel)
        }
        tableView.snp.remakeConstraints { make in
            make.top.equalTo(superview).offset(20)
            make.right.bottom.equalTo(superview).offset(-20)
            make.left.equalTo(superview.snp.right).offset(-300)
        }
    }

Now while the layouts show no problem individually, when I switch from horizontal to vertical (and only in that direction) autolayout complaints about having to break constraints that should not exists after a recreate in the first place.

What am I missing? Is this a bug or am I using the API the wrong way?

**Comment by tcurdt** [comment]
After labeling I do see the mixed constraints from both horizontal and vertical:
```
...
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<SnapKit.LayoutConstraint:h3@ScannerViewController.swift#117 UIImageView:0x7f855fe04290.width == UILabel:0x7f855fe04480.width * 0.300000011920929>",
    "<SnapKit.LayoutConstraint:h7@ScannerViewController.swift#123 UILabel:0x7f855fe04480.right == UITableView:0x7f8561009200.left - 20.0>",
    "<SnapKit.LayoutConstraint:v11@ScannerViewController.swift#107 UITableView:0x7f8561009200.left == UILabel:0x7f855fe04480.left>"
)
...
```
`v11` from vertical and `h3` and `h7`from horizontal - that should not happen.

**Comment by robertjpayne** [comment]
@tcurdt just to be certain -- is your layout code re-entrant? e.g. are any of the remakeConstraints blocks making the `layoutVertical()` or `layoutHorizontal()` run inside of itself?

**Comment by tcurdt** [comment]
@robertjpayne sorry, I for the delay but I was offline for a bit.

That's a good question - but I am not entirely sure I can answer it. The `updateConstraintsForTraitCollection` is only called from the animation block inside `willTransition`. And I guess it depends on Apple's implementation details whether it's re-entrant or not. The approach itself is from a WWDC session - but they are creating and switching constraints directly (without SnapKit).

```
override func willTransition(to newCollection: UITraitCollection, with coordinator: UIViewControllerTransitionCoordinator) {
    super.willTransition(to: newCollection, with: coordinator)

    coordinator.animate(alongsideTransition: { _ in
        self.updateConstraintsForTraitCollection(newCollection)
        self.view.setNeedsLayout()
    }, completion: nil)
}


func updateConstraintsForTraitCollection(_ collection: UITraitCollection) {

    let wide = size.width >= size.height
    if wide {
        layoutHorizotal()
    } else {
        layoutVertical()
    }
}
```

**Comment by robertjpayne** [comment]
@tcurdt it doesn't hurt to create or remove constraints, but if you're inside a constraint block and run a remake you could get a partial reset.

Can you use a log statement or breakpoint and determine if you're possibly running into re-entrant code?

**Comment by tcurdt** [comment]
@robertjpayne The project schedule didn't allow to debug this further. (Also for other reasons) I ended up switching to supporting portrait only :-/

I cannot make any promises when I can provide a testcase. But it should be pretty straightforward to setup. The relevant WWDC session were:

https://developer.apple.com/videos/play/wwdc2016/222/
https://developer.apple.com/videos/play/wwdc2016/233/

The async operation of `coordinator.animate` makes things a little more complicated of course. For the code to be re-entrant it would need to go on the same and serial queue I guess.

**Comment by robertjpayne** [comment]
Closing this as I believe it's an re-entrant issue and not SnapKit
