### ISSUE TITLE
XCode9 + Swift4

### ISSUE THREAD

**Issue by wang542413041** [SnapKit/SnapKit#449]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Only many value need use '.rawValue' , Other is ok . Good job bro⚠️

**Comment by robertjpayne** [comment]
Releasing it soon but is a dupe issue.
