### ISSUE TITLE
XCode 9 Compatibility 

### ISSUE THREAD

**Issue by electic** [SnapKit/SnapKit#453]
Platform                | ios
 Platform Version        | 11
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods

Seems to not compile under XCode 9.

<img width="272" alt="screen shot 2017-09-19 at 1 52 38 pm" src="https://user-images.githubusercontent.com/43028/30614935-fd7a1320-9d41-11e7-945c-b210227cf48e.png">

**Comment by electic** [comment]
Seems like there are dupes. Ignore this.

**Comment by jeremypiednoel** [comment]
Hey how did you fix that ?
