### ISSUE TITLE
[NOTICE] Xcode 9 Compatibility with CocoaPods

### ISSUE THREAD

**Issue by robertjpayne** [SnapKit/SnapKit#454]
Currently Cocoapods is not able to correctly mix Swift 3.2 and Swift 4.0 pods. `SnapKit 4.0.0` is only compatible with Swift 4.0.0, if you have integration issues use `SnapKit 3.2.0` as there is no functional difference between the two.

In a future release of `SnapKit 4.x.0` we may bring compatibility with Swift 3.2.0 if Cocoapods continues to have issues.

**Comment by EpicKim** [comment]
What exactly do you mean? Give error message and how to reproduce.

**Comment by EpicKim** [comment]
u can try in your podfile like this
```
if target.name == 'SnapKit'
        if target.name == 'KWTrendChart'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
```
