### ISSUE TITLE
we have an error in xcode9.0

### ISSUE THREAD

**Issue by delayhsiao** [SnapKit/SnapKit#457]
version:
xcode: 9.0
swift: 4.0

error:
```
Module compiled with Swift 3.1 cannot be imported in Swift 4.0
```
code:
```
import SnapKit
```

**Comment by robertjpayne** [comment]
This isn't a SnapKit error, you cannot import Swift 3.1 modules into Swift 4.0 targets. You probably need to clean and re-build or update SnapKit to 3.2.0 or 4.0 depending on which version you are targeting.

**Comment by delayhsiao** [comment]
thanks
