### ISSUE TITLE
Swift 4.0 Issues

### ISSUE THREAD

**Issue by lsonlee** [SnapKit/SnapKit#458]
After update my Xcode in 9.0 and I update SnapKit in 4.0.0 ,when I compile my project , it throw a error “Value of type 'UILayoutPriority(aka 'Float') has no member 'rawValue'”

**Comment by electic** [comment]
Did you read this? https://github.com/SnapKit/SnapKit/issues/454

**Comment by robertjpayne** [comment]
Issues without issue templates are not acceptable. Please respect GitHub maintainers by filling the issue templates out.
