### ISSUE TITLE
makeExtendableWithAttributes for public usage

### ISSUE THREAD

**Issue by danshevluk** [SnapKit/SnapKit#460]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.3
 SnapKit Version         | 3.2.0
 Integration Method      | cocoapods
 

### Issue Description

This is more like feature request

Is there is a way to use something similar to `makeExtendableWithAttributes` inside of `makeConstraints` block in my application? 

It would be nice to be able to create a variable with constraint attribute to use it inside `makeConstraints`. Example: I have a view that can be filled from fight to left of from left to right. In current implementation constraints creation looks like that:
```swift
... 
switch fillMode {
case .leftToRight:
  myView.snp.makeConstraints { make in 
    make.left.equalToSuperview()
    ...
  }
case .rightToLeft:
  myView.snp.makeConstraints { make in 
    make.right.equalToSuperview()
    ...             
  }
}   
```

Code duplication is bad so it would be much nicer like that:
```swift
... 
let attribute: ConstraintAttributes
switch fillMode {
case .leftToRight:
  attribute = .left
case .rightToLeft:
  attribute = .right
}    

myView.snp.makeConstraints { make in 
  // This is just an example
  make.with(attribute).equalToSuperview()
   ...
}
```

**Comment by robertjpayne** [comment]
Hm this is a pretty good suggestion, however, at the same time I find the new concise code ambiguous. The reader of this code now has to go find out what "attribute" is and what value it stores. 


Most code it is valuable to strictly DRY it up but with auto layout I find it sometimes better to be a bit more verbose so readability is maintained years later.

**Comment by danshevluk** [comment]
@robertjpayne I agree that developers should not mess with auto layout code. 
My example is a rare use case so maybe it's not worth it to support that.

The other solution to this problem is to decompose repeated make-code to another method with `make` as a parameter. This is not that bad 🤷‍♂️ 

Thank you for quick answer!

**Comment by robertjpayne** [comment]
I need to find a few ways to allow users to hook SnapKit and provide extensions for the API. Specifically a lot of users may want their own shortcuts but I'm unwilling to support them directly as I like to keep the API as true and "one way to do something" as possible.
