### ISSUE TITLE
Xcode version 9.1 beta and Swift 4.0.1

### ISSUE THREAD

**Issue by JeromeCHA** [SnapKit/SnapKit#464]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.1
 SnapKit Version         | 4.0.0
 Integration Method      | carthage
 

### Issue Description

I try to build my app with the latest Xcode beta version 9.1 and the iOS beta version 11.1 and I got the following error.

<img width="471" alt="screen shot 2017-10-11 at 3 43 51 pm" src="https://user-images.githubusercontent.com/11457628/31425701-4a5eed36-ae9b-11e7-803c-c62670c6173b.png">

**Comment by sammygutierrez** [comment]
Try running `carthage update SnapKit --platform iOS --no-use-binaries`.

**Comment by JeromeCHA** [comment]
@sammygutierrez Thank you for your answer. I tried with your command line and I still got the error.
I forgot to say that my carthage version is 0.26.0.

Just in case, here is the result the command line :

```
$ carthage update SnapKit --platform iOS --no-use-binaries
*** Fetching SnapKit
*** Checking out SnapKit at "c0f66e42be339f27e727da022518af362cca409b"
*** xcodebuild output can be found in /var/folders/2l/t87hgh4d5170_wt7ysl24jh00000gn/T/carthage-xcodebuild.ijyKAt.log
*** Building scheme "SnapKit" in SnapKit.xcworkspace
```

**Comment by sammygutierrez** [comment]
@JeromeCHA Run `sudo xcode-select -s /Applications/Xcode-beta.app/` and then try the carthage command again.

**Comment by JeromeCHA** [comment]
@sammygutierrez Thank you! it works! :)
