### ISSUE TITLE
Feature request: directionalLayoutMargins over layoutMargins

### ISSUE THREAD

**Issue by swordray** [SnapKit/SnapKit#465]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [Y] I have looked at the [Documentation](http://snapkit.io/docs)
* [Y] I have read the [F.A.Q.](http://snapkit.io/faq)
* [Y] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.0
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods
 

### Issue Description

From iOS 11 ducomentation https://developer.apple.com/documentation/uikit/uiview/1622566-layoutmargins

> In iOS 11 and later, use the directionalLayoutMargins property to specify layout margins instead of this property.

Should we support `directionalLayoutMargins`?

**Comment by robertjpayne** [comment]
@swordray I believe these are just a replacement for `layoutMargins` not actually a new constraint target?

**Comment by swordray** [comment]
@robertjpayne Yes, `directionalLayoutMargins` is the same constraint target but just a different API. My mistake.

There is just one trivial thing might mislead me.
```swift
make.margins.equalTo(view.layoutMargins)
// works

make.margins.equalTo(view.directionalLayoutMargins)
// Argument type 'NSDirectionalEdgeInsets' does not conform to expected type 'ConstraintRelatableTarget'
```
