### ISSUE TITLE
updateOrMakeConstraint (feature request)

### ISSUE THREAD

**Issue by benpackard** [SnapKit/SnapKit#469]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [/ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ /] I have read the [F.A.Q.](http://snapkit.io/faq)
* [/ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform: |iOS
 Platform Version:| all
 SnapKit Version: |all
 Integration Method: |all
 

### Issue Description

On occasion, it would be useful to update a constraint if it exists, and create one if not. For example, sometimes a frequently changing property is expected to resize a view's height. Every time the value changes, `updateConstraints` can be used to change the constant on existing height constraint. However, this requires a pre-existing constraint has already been added via `makeConstraint` with some arbitrary value for the constant. This is unnecessary and decreases code comprehension since the layout is spread over two separate places, with one relying on the other being set first to avoid crashing (attempting to update a constraint that doesn't exist). 

Relying on `remakeConstraints` isn't useful since this removes all other, unrelated constraints.

The proposal is to add a new option, `udpateOrMakeConstraints`, which uses `makeConstraints` when no existing constraint exists (i.e. the first time is called), and uses`updateConstraints` otherwise.

An alternative option would be an option to `makeConstraintsIfNeeded` which does nothing if a matching constraint is already in place. The caller could place this directly before `updateConstraints`.

**Comment by robertjpayne** [comment]
@benpackard I believe `updateConstraints` should already do this, if there are no constraints associated with the source already it will create new ones w/o checking that you're updating existing.

**Comment by aehlke** [comment]
@robertjpayne this behavior changed in a recent release, and it now crashes the app if you try to update one that did not exist.

**Comment by benpackard** [comment]
Thanks @robertjpayne. What if there *are* some constraints associated, but nothing suitable for the specific update? For example, a view that can be positioned early on, but the size won't be known until later.

I.e.:

```
label.snp.makeConstraints { make in
	make.center.equalToSuperview()
}
...
label.snp.updateConstraints { make in
	make.height.equalTo(someValueNotKnownUntilNow)
}
```

This crashes with `Updated constraint could not find existing matching constraint to update`. So I instead use:

```
label.snp.makeConstraints { make in
	make.center.equalToSuperview()
	make.height.equalTo(0)
}
...
label.snp.updateConstraints { make in
	make.height.equalTo(someValueNotKnownUntilNow)
}
```

Given the current behavior as you described it, my preference would no longer be for a new `updateOrMakeConstraints` option, but for `updateConstraints` to make a more granular determination about when to add new constraints instead of only checking if *any* constraints exist for the view. However, this might be a non-trivial task with other undesirable side effects for an edge case like mine with an obvious workaround.

**Comment by robertjpayne** [comment]
@aehlke this change was intentional, the idea is that anything ever declared inside `updateConstraints` is "immutable", the first time it's called it will make the constraints and then you can only update those same constraints.

@benpackard unfortunately this is the behaviour that the change was explicitly designed to prevent because it's error prone. With Masonry (the ancestor and ObjC version of SnapKit) too many people with Masonry assumed you could use `updateConstraints` to do things that it cannot and then filed bug reports about an "extra" constraint or it not working properly.

The problem is it's impossible to make a granular decision about what constraints to keep, which to update and which to discard. For instance:

```
label.snp.makeConstraints { make in
	make.top.eqaulTo(buttonA).offset(5)
}
...
label.snp.updateConstraints { make in
	make.top.eqaulTo(buttonB).offset(5)
}
```

Should this code replace an existing constraint? Or add it in addition to the existing one? It's really impossible to know without really understanding your layout needs.

**Comment by benpackard** [comment]
Thanks both, I understand.
