### ISSUE TITLE
When do you plan to release the next version

### ISSUE THREAD

**Issue by dsk0701** [SnapKit/SnapKit#470]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Question
Hello,
Thank you for your great lib :)

I have a question.
When do you plan to release the next version?
Because our team would like to use [#466](https://github.com/SnapKit/SnapKit/pull/466/files).

**Comment by robertjpayne** [comment]
@dsk0701 probably with Xcode 9.1. You should be able to target the commit in your Cocoapods/Carthage file directly in the meantime?

**Comment by dsk0701** [comment]
@robertjpayne Thanks for your reply.
I understand about your plan. I will do so.
