### ISSUE TITLE
Is there any way to get the value of a constraint?

### ISSUE THREAD

**Issue by patchthecode** [SnapKit/SnapKit#471]
### New Issue Checklist

* [/ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [/] I have read the [F.A.Q.](http://snapkit.io/faq)
* [/] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.0
 SnapKit Version         | 4.0
 Integration Method      | cocoapods
 

### Issue Description

Referring to this issue -> https://github.com/SnapKit/SnapKit/issues/235

I need to constant value of the constraint to do animation.
Is there any work around to this?

**Comment by robertjpayne** [comment]
@patchthecode as stated in #235 at the moment there is not, because a single `Constraint` can represent more than 1 `NSLayoutConstraint` I cannot easily infer what constant value you want.
