### ISSUE TITLE
Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by stealdre** [SnapKit/SnapKit#472]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                 |  ios
 Platform Version       | 11.1
 SnapKit Version       | 4
 Integration Method     | cocoapods
 

### Issue Description

Hi, I have a `UILabel` infoLabel. I add constraints to this label like this: 

```
 infoLabel.snp.makeConstraints {(make) -> Void in
            make.width.equalTo(view.snp.width).multipliedBy(0.9)
            make.height.equalTo(30)
            make.centerX.equalTo(view.snp.centerX)
            make.centerY.equalTo(view.snp.centerY).offset(-100)
        }
```

Then, I want to update the Y constraints. So I do it like this: 

```
 self.infoLabel.snp.updateConstraints {(make) -> Void in
                        make.centerY.equalTo(self.view.snp.centerY).offset(-100).offset(-self.view.frame.height * 0.12)
                    }
```

The constraint update works but I get this in logs: 

```
Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want.
(
    "<SnapKit.LayoutConstraint:0x1c02a8e20@PlayNowViewController.swift#201 UILabel:0x10421f290.centerY == UIView:0x10423f670.centerY - 80.04>",
    "<SnapKit.LayoutConstraint:0x1c02a9840@PlayNowViewController.swift#201 UILabel:0x10421f290.centerY == UIView:0x10423f670.centerY - 100.0>"
)
```

Any idea? Thanks in advance.

**Comment by ZeranLatte** [comment]
Seems like you only want to update the offset value of the constraint. So no need to specify the offset(-100) you added in the first place
Just try this: `make.centerY.equalTo(self.view.snp.centerY).offset(-self.view.frame.height * 0.12)`
Please refer to http://snapkit.io/docs/ in the updateConstraint section for more info.

**Comment by stealdre** [comment]
This doesn't work. Moreover, I don't want to overwrite the offset but a subtract its value by self.view.frame.height * 0.12. I tried this: 

`make.centerY.equalTo(self.view.snp.centerY).offset(-150 - self.view.frame.height * 0.12)`

But still doesn't work... Thanks for the help anyway.

**Comment by ZeranLatte** [comment]
You need to store a variable to reference your constraint, when you add this constraint. It's explained in the documentation. Check out **Hold on for dear life**, - 1.Reference

**Comment by robertjpayne** [comment]
@stealdre the issue here is that `self.view.frame.height` isn't constant and can change at any time. I suggest just using manual layout here in `layoutSubviews` or if you're in the view controller using `viewWillLayoutSubviews`. 

It'll be much more performant and ensure you always catch changes to the view size.

**Comment by vincentlh** [comment]
In my case, just use .priority(.low) in both makeConstraints & updateConstraints, like:
_appTitle.do {
            $0.font = UIFont.systemFont(ofSize: 16).meui_bold
            $0.textAlignment = .left
            contentView.addSubview($0)
            $0.snp.makeConstraints { make in
                make.leading.equalTo(_avatarImageView.snp.trailing).offset(10)
                make.centerY.equalToSuperview().priority(.low)
                make.height.equalTo(22)
                make.trailing.equalTo(_subStateBtn.snp.leading).offset(-8)
            }
        }

_appTitle.snp.updateConstraints { make in
                make.trailing.equalTo(_subStateBtn.snp.leading).offset(-24).priority(.low)
            }
and the constraints warnings gone away.
