### ISSUE TITLE
Replace ConstraintMultiplierTarget with CGFloat

### ISSUE THREAD

**Issue by adamkuipers** [SnapKit/SnapKit#475]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | N/A
 Platform Version        | N/A
 SnapKit Version         | 3.2.0
 Integration Method      | cocoa pods
 

### Issue Description

It often improves readability to write out the factor one is multiplying a constraint as a rational, since it explicitly shows the ratio. Because `multipliedBy(_:)` takes a type conforming to `ConstraintMultiplierTarget` and how Swift's literal conversion works, whole numbers will be evaluated as type Int (e.g. `.multipliedBy(3 / 5)` gets evaluated as `.multipliedBy(0)`). This is very confusing and can lead to hard to debug issues with one's constraints (see #170).

This issue proposes removing `ConstraintMultiplierTarget` and only using `CGFloat`, which matches `NSLayoutDimension`.

**Comment by robertjpayne** [comment]
@adamkuipers interesting, I'll investigate this further but may be a bit of time until I get to it. Would be really happy with a PR though if you have any time.
