### ISSUE TITLE
Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x60c000464d00 "UIView:0x7fc31b5080f0.centerX"> and <NSLayoutXAxisAnchor:0x60c000464d80 "UIView:0x7fc31b405bd0.centerX"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal

### ISSUE THREAD

**Issue by jeromexiong** [SnapKit/SnapKit#478]
### New Issue Checklist

when I using :
        let box = UIView()
        box.snp.makeConstraints { (make) -> Void in
            make.width.equalTo(100)
            make.height.equalTo(100)
            make.center.equalTo(self.view)
        }

### Issue Info
Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x60c000464d00 "UIView:0x7fc31b5080f0.centerX"> and <NSLayoutXAxisAnchor:0x60c000464d80 "UIView:0x7fc31b405bd0.centerX"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal
 

### Issue Description

it cause this problen, I need your help

**Comment by jeromexiong** [comment]
The development environment is Xcode9， Swift 4， SnapKit 4.0.0

**Comment by JackLChen** [comment]
hi, you hadn't added the view `box` to a `superView` first, I think. You have to add a subview to superview before making constraints. Try to do it like this: 
```
let box = UIView()
view.addSubview(box)
box.snp.makeConstraints { (make) -> Void in
     make.width.equalTo(100)
     make.height.equalTo(100)
     make.center.equalTo(self.view)
}

```
I hope it can do you a favor.

**Comment by robertjpayne** [comment]
@jeromexiong @JackLChen is correct, you need to add it as a subview first.
