### ISSUE TITLE
what's the difference between greaterThanOrEqualTo() and equalTo() ?

### ISSUE THREAD

**Issue by JackLChen** [SnapKit/SnapKit#479]
* [ yes] I have looked at the [Documentation](http://snapkit.io/docs)
* [ yes] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ yes ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.0
 SnapKit Version         | 4.0
 Integration Method      | cocoapods
 

### Issue Description

Sorry, a problem still has confused me for a long time that what's the difference between **greaterThanOrEqualTo()** and **equalTo()** ?

Codes as follows：

```
make.width.greaterThanOrEqualTo(50)
make.height.greaterThanOrEqualTo(50)
make.center.equalToSuperview()
```

it seems to be the same as follows:

```
make.width.equalTo(50)
make.height.equalTo(50)
make.center.equalToSuperview()
```

Both are the same effect above.

Besides, and `lessThanOrEqualTo` VS `equalTo()`?  

Thank you very much for your help in advance.

**Comment by robertjpayne** [comment]
@JackLChen this is managed by Auto Layout from Apple, `equalTo` will always force a constraint to be exactly equal to. `greaterThanOrEqualTo` will allow the constraint to be at least that value or higher, this can happen when you have competing constraints that would otherwise conflict.

**Comment by wes-swinson-tackmobile** [comment]
No, there is no difference. There is definitely a bug. 

greaterThanOrEqualTo should only "grow" the view until it hits the border of the constraint. 

However, every time I use this constraint type, it acts like an equalTo and ALWAYS expands the view to the border. I've tested this multiple times in multiple ways.
