### ISSUE TITLE
When the cocpods are integrated, there is some error with swift4.0 xcode 9.2

### ISSUE THREAD

**Issue by turkeyaa** [SnapKit/SnapKit#481]
![snap_error](https://user-images.githubusercontent.com/7940089/33974818-835a26a8-e0c5-11e7-8836-12e5de448adb.png)

**Comment by AlanMoMo** [comment]
I also have the same problem.

**Comment by ZanderDev** [comment]
I also have the same problem，too

**Comment by DavidStenstroem** [comment]
I too have this problem. Any resolutions?

**Comment by turkeyaa** [comment]
@DavidStenstroem Upgrade SnapKit to the latest version(4.0.0) for normal use

**Comment by zwind007** [comment]
The version is 4.0.0,but also have the same problem.

**Comment by turkeyaa** [comment]
@zwind007 Here is no problem in Xcode9.2 and SnapKit 4.0.0

**Comment by robertjpayne** [comment]
Closing this as it does not follow issue template.
