### ISSUE TITLE
pod 'SnapKit', '~> 4.0.0'          Error

### ISSUE THREAD

**Issue by HMWDavid** [SnapKit/SnapKit#482]
<img width="562" alt="2017-12-15 5 29 31" src="https://user-images.githubusercontent.com/22783742/34035718-f20c6be4-e1bd-11e7-9346-b6cd59acac90.png">
<img width="565" alt="2017-12-15 5 32 19" src="https://user-images.githubusercontent.com/22783742/34035723-f758b256-e1bd-11e7-9ae1-c6684c23cd6f.png">

**Comment by HMWDavid** [comment]
Xcode 9.1

**Comment by jinthreek89** [comment]
Did you try `pod repo update` before `pod install` ?

**Comment by robertjpayne** [comment]
Closing this as it does not follow issue template.

**Comment by HMWDavid** [comment]
thanks!
