### ISSUE TITLE
Prebuild binary for Carthage

### ISSUE THREAD

**Issue by olejnjak** [SnapKit/SnapKit#483]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | any
 Platform Version        | any
 SnapKit Version         | 4.0.0
 Integration Method      | carthage
 

### Issue Description

Hi, I'd like to ask if it would be possible to include prebuild binary framework with releases to allow carthage to download it instead of building it? Thanks

**Comment by robertjpayne** [comment]
Hi @olejnjak unfortunately I don't do this, as I personally feel it's a security risk to not compile the sources yourself. While I do understand it can speed up initial compile times Carthage does have several nice caching mechanisms to avoid this.

Cheers!
