### ISSUE TITLE
Can't set contentCompressionResistanceHorizontalPriority

### ISSUE THREAD

**Issue by Rendel27** [SnapKit/SnapKit#484]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | iOS 11 (but I think this happens on any version)
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods
 

### Issue Description

I can't set contentCompressionResistanceHorizontalPriority on a view.

`self.lblTitle.snp.contentCompressionResistanceHorizontalPriority = UILayoutPriority.defaultLow.rawValue`

it says: "Cannot assign to property: 'snp' is a get-only property"
I understand that I can't set it directly but there is no compression property inside the makeConstraints block.

shouldn't it be something like this:
```
self.lblTitle.snp.makeConstraints { make in
    make.contentCompressionResistanceHorizontalPriority.equalTo(UILayoutPriority.defaultLow)
}
```

Thanks
Giorgi

**Comment by rnystrom** [comment]
Just set the priority on the view itself using vanilla UIKit

```swift
lblTitle.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
```

**Comment by robertjpayne** [comment]
@Rendel27 @rnystrom is correct here, I chose not to re-implement the vanilla functions here. SnapKit also does not have any additional shortcuts for setting layout margins or safe area margins.
