### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by tiagomartinho** [SnapKit/SnapKit#489]
In the SnapKit documentation (http://snapkit.io/docs/) it should be "view.safeAreaLayoutGuide.snp.top" instead of "self.safeAreaLayoutGuide.snp.top" under the "Snap view to safe layout guide" section

**Comment by beltex** [comment]
Hello @tiagomartinho!

Fixed in https://github.com/SnapKit/SnapKit/pull/473.

**Comment by tiagomartinho** [comment]
Hello @beltex ! But the current [documentation](http://snapkit.io/docs/) website is not updated. In the section "Snap view to safe layout guide" you can still read:
```
import SnapKit

class MyViewController: UIVewController {
    
    lazy var tableView = UITableView()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        self.view.addSubview(tableView)
        tableView.snp.makeConstraints { (make) -> Void in
->           make.top.equalTo(self.safeAreaLayoutGuide.snp.top)
        }
    }

}
```

**Comment by beltex** [comment]
#473 has now been merged!

**Comment by tiagomartinho** [comment]
Thanks!
