### ISSUE TITLE
Update Constant for constraint

### ISSUE THREAD

**Issue by rehannali** [SnapKit/SnapKit#490]
Platform                | iOS
 Platform Version        | 11.0
 SnapKit Version         | 4.0
 Integration Method      | cocoapods
 

### Issue Description

messageBubbleView.snp.makeConstraints { (make) in
            make.top.equalTo(self)
            rightConstraint = make.right.equalTo(self).offset(-8).constraint
            rightConstraint?.activate()
            leftConstraint = make.left.equalTo(self).offset(8).constraint
            leftConstraint?.deactivate()
            make.bottom.equalTo(self)
            make.width.equalTo(250)
        }
i want to update width constraint constant. I can't figure out how can i acheive it?

**Comment by colinta** [comment]
```swift
rightConstraint?.update(offset: 0)
```

Also, please use github's source markup - triple backticks and the language will add source code highlighting, e.g.
` ```swift `
`# ...code...`
` ``` `

**Comment by rehannali** [comment]
```swift
# make.right.equalTo(20)
```
If i right code like this then how can i update constraint?

**Comment by colinta** [comment]
I think this question is best answered by reading the docs and examples - but basically the two ways are:

1. Store the constraint and update its offset value
2. Store multiple constraints and activate/deactivate the appropriate constraint

**Comment by rehannali** [comment]
@colinta Thanks for help. I read all docs related to my problem and i found exactly these ways. I wonder if there is any way if we write code that way so i can update constant.

**Comment by colinta** [comment]
Yes you can update the constraint constant:

    constraint.update(offset: newValue)
