### ISSUE TITLE
I can't build my project in Xcode 9.1 with Snapkit 4.0

### ISSUE THREAD

**Issue by caohrong** [SnapKit/SnapKit#491]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | xcode
 Platform Version        |  Version 9.1 (9B55)
 SnapKit Version         |  4.0.0
 
### Issue Description

I upgraded the Kit in CocoaPods, When I try to rebuild my project. It‘s show me so many errors in the Snapkit. I was wondering if anyone could  help me about that? thanks.

File: Constraint.Swift
【Code】
// set priority 
layoutConstraint.priority = LayoutPriority(rawValue: self.priority.constraintPriorityTargetValue)
【Error info】 
Argument labels '(rawValue:)' do not match any available overloads

【Code】
if (layoutConstraint.priority.rawValue < requiredPriority), (self.priority.constraintPriorityTargetValue != requiredPriority) {
                layoutConstraint.priority = LayoutPriority(rawValue: self.priority.constraintPriorityTargetValue)
            }

【Error info】
Value of type 'UILayoutPriority' (aka 'Float') has no member 'rawValue'

**Comment by zhandongwang** [comment]
I meet the same problem, have you resolved it ?

**Comment by caohrong** [comment]
Don' use 4.0 add this to your project pod 'SnapKit', '~> 3.2.0'

**Comment by truextcfans** [comment]
run
echo 4.0 > .swift-version
change your default Swift Version to 4.0

**Comment by Ryohu** [comment]
same

**Comment by Vario** [comment]
Is there any update yet? I still cannot compile with Swift 4.1 and SnapKit 4.0.0 which seems to be the latest build

**Comment by letanthang** [comment]
same issue

**Comment by jkiley129** [comment]
I get this issue all the time. Prevents us from using our CI pretty often. 

The only workaround I have found is to comment out SnapKit from the pod file, run a pod install to remove SnapKit, uncomment SnapKit from the Podfile and then reinstall the pods. Very annoying when it happens. I really hope this gets resolved soon since it has been an open issue for nearly 6 months.

**Comment by JAManfredi** [comment]
Not entirely sure why this is happening, but I just had the same issue. 

Its because the installed Pod doesn't contain the Typealiases.swift file, which is causing the compiler error. 

Here are the steps I used to resolve this:

1. I had to uninstall the pod by commenting it out and running `Pod Install`
2. Now clear the pod cache by running `pod cache clean --all`
3. Uncomment SnapKit and `pod install`

To be sure this fixed it, check the pod source directory for the previously missing .swift file.

**Comment by Vario** [comment]
I tried to comment it out,pod install, clean cache, uncomment and pod install, but the error still exists.
Project clean does not help aswell :-/

**Comment by Vario** [comment]
Okay i encountered a few more errors and had to fix it manually 

I modified these files
ConstraintViewDSL.swift  
Line 54
`   public var contentHuggingHorizontalPriority: Float {
        get {
            return self.view.contentHuggingPriority(for: .horizontal)
        }
        set {
            self.view.setContentHuggingPriority(LayoutPriority(floatLiteral: newValue), for: .horizontal)
            //self.view.setContentHuggingPriority(LayoutPriority(rawValue: newValue), for: .horizontal)
        }
    }
    
    public var contentHuggingVerticalPriority: Float {
        get {
            return self.view.contentHuggingPriority(for: .vertical)
        }
        set {
            self.view.setContentHuggingPriority(LayoutPriority(floatLiteral: newValue), for: .vertical)
            //self.view.setContentHuggingPriority(LayoutPriority(rawValue: newValue), for: .vertical)
        }
    }
    
    public var contentCompressionResistanceHorizontalPriority: Float {
        get {
            return self.view.contentCompressionResistancePriority(for: .horizontal)
        }
        set {
            self.view.setContentCompressionResistancePriority(LayoutPriority(floatLiteral: newValue), for: .horizontal)
           // self.view.setContentCompressionResistancePriority(LayoutPriority(rawValue: newValue), for: .horizontal)
        }
    }
    
    public var contentCompressionResistanceVerticalPriority: Float {
        get {
            return self.view.contentCompressionResistancePriority(for: .vertical)
        }
        set {
            self.view.setContentCompressionResistancePriority(LayoutPriority(floatLiteral: newValue), for: .vertical)
           // self.view.setContentCompressionResistancePriority(LayoutPriority(rawValue: newValue), for: .vertical)
        }
    }`

in Constraint.swift 
Line 166
`
            // set priority
            layoutConstraint.priority = LayoutPriority(floatLiteral: self.priority.constraintPriorityTargetValue)
            //layoutConstraint.priority = LayoutPriority(rawValue: self.priority.constraintPriorityTargetValue)
`
Line 247
`//if (layoutConstraint.priority.rawValue < requiredPriority), (self.priority.constraintPriorityTargetValue !=
            if (layoutConstraint.priority < requiredPriority), (self.priority.constraintPriorityTargetValue != requiredPriority) {
                layoutConstraint.priority = LayoutPriority(floatLiteral: self.priority.constraintPriorityTargetValue)
            }`

Debugging.swift
 Line 69
` //if self.priority.rawValue != 1000.0 {
        if self.priority != 1000.0 {
                description += " ^\(self.priority)"
        }`
