### ISSUE TITLE
Error: Cannot assign value of type 'ConstraintMakerEditable' to type 'Constraint?' when following docs

### ISSUE THREAD

**Issue by kakubei** [SnapKit/SnapKit#495]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform               |  iOS
 Platform Version    |    11
 SnapKit Version      |   4.0.0
 Integration Method  |    cocoapods
 

### Issue Description

Following the docs to create a reusable (updatable and uninstallable) constraint. I get the following error: 

`Cannot assign value of type 'ConstraintMakerEditable' to type 'Constraint?'`

This this bit of code: 

```
var destinationAddressViewBottom: Constraint? = nil
 destinationAddressViewBottom = make.bottom
                    .equalTo(titleBackgroundView.snp.bottom)
                    .offset(-16)
```

**Comment by Vektrat** [comment]
Hello, I think you are forgetting the tail of the expression to get the Constraint object out of it, such as:

`var destinationAddressViewBottom: Constraint? = nil
 destinationAddressViewBottom = make.bottom
                    .equalTo(titleBackgroundView.snp.bottom)
                    .offset(-16).constraint
`

**Comment by warpling** [comment]
Wow that is easy to miss!!

**Comment by akhrameev-picsart** [comment]
[Raywenderlich's tutorial](https://www.raywenderlich.com/3225401-snapkit-for-ios-constraints-in-a-snap) also misses this part
