### ISSUE TITLE
centerX, centerY offset/inset are the same

### ISSUE THREAD

**Issue by sh3244** [SnapKit/SnapKit#498]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ X] I have looked at the [Documentation](http://snapkit.io/docs)
* [ X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.0
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods
 

### Issue Description

It appears that centerY.offset(value) does the same thing that centerY.inset(value) does.
In order to circumvent, one must provide a negative value.

**Comment by AlexanderBollbach** [comment]
yes it does seem that way.  `offset` and `inset` are the same.   this is very confusing and unhelpful

**Comment by Cyberbeni** [comment]
Fixed by #569
