### ISSUE TITLE
About ConstraintMaker implementation

### ISSUE THREAD

**Issue by iostalks** [SnapKit/SnapKit#503]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 8.0
 SnapKit Version         | 4.0.0
 Integration Method      | 
 

### Issue Description

Hi, I have a question with `ConstraintMaker` class `makeConstraints(item:)` method implementation.

```swift
        var constraints: [Constraint] = [] 
        for description in maker.descriptions {
            guard let constraint = description.constraint else {
                continue
            }
            constraints.append(constraint)
        }
        for constraint in constraints {
            constraint.activateIfNeeded(updatingExisting: false)
        }
```
Why use a temporary array hold constraint? 

``` swift
        for description in maker.descriptions {
            guard let constraint = description.constraint else {
                continue
            }
            constraint.activateIfNeeded(updatingExisting: false)
        }
```
I think it is more clearly. Whether above handling have some purpose?

I'm sorry to have your time. Thanks.

**Comment by robertjpayne** [comment]
@iostalks the reason being here is so that as the constraints are generated any errors thrown in there are not mixed with errors thrown from activation.

It's just a minor optimisation to help debugging.
