### ISSUE TITLE
Is there a plan to support swift static library?

### ISSUE THREAD

**Issue by nspangbo** [SnapKit/SnapKit#504]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

Is there a plan to support swift static library?
http://blog.cocoapods.org/CocoaPods-1.4.0/

**Comment by robertjpayne** [comment]
Yep it sure can be done pretty easy just a small change, would love if you want to make a PR!

**Comment by 0xwangbo** [comment]
http://blog.cocoapods.org/CocoaPods-1.5.0/

A better way.
