### ISSUE TITLE
UIViewController in TabBarViewController hidden tabbar  item.snp.bottom.equalToSuperview() invalid 

### ISSUE THREAD

**Issue by ljs19850321** [SnapKit/SnapKit#505]
### Bottom
        let logoView = OWSeriesLogoView()
        view.addSubview(logoView)
        logoView.snp.makeConstraints { (maker) in
            maker.top.equalTo(menuView.snp.bottom)
            maker.left.right.equalToSuperview()
            maker.bottom.equalToSuperview()
        }
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 9.0
 SnapKit Version         | e.g. 4.0.0
 

### Issue Description
UIViewController in TabBarViewController hidden tabbar  item.snp.bottom.equalToSuperview()  invalid
There are 44 blanks from the bottom

**Comment by robertjpayne** [comment]
Not really sure I can help here your sample code is rather incomplete and the description lacking some details.

Are you trying to create auto layout pinned to items in the tab bar? I'm not sure if that is legal in auto layout.
