### ISSUE TITLE
Pinning `centerY` to `firstBaseline` does not behave correctly

### ISSUE THREAD

**Issue by anlaital** [SnapKit/SnapKit#507]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.0
 SnapKit Version         | 4.0.0
 Integration Method      | CocoaPods
 
### Issue Description

Given the following definition (where `view` is an UIView with `intrinsicContentSize` defined and `label` is a regular single or multi-line `UILabel`):

```
        view.snp.makeConstraints {
            $0.centerY.equalTo(label.snp.firstBaseline)
            $0.left.equalToSuperview()
        }
```

One would assume this pins the `view` vertically centered to the first line of the label. However, this does not happen. However, this definition works as assumed:

```
        view.snp.makeConstraints {
            $0.bottom.equalTo(label.snp.firstBaseline)
            $0.left.equalToSuperview()
        }
```

Note that pinning `top` doesn't work either, only `bottom`, which is very strange. Pinning `centerY` used to work but it's gotten broken at some point.

**Comment by robertjpayne** [comment]
@anlaital I'm not really sure here, does it work if you use vanilla auto layout constraints?
