### ISSUE TITLE
Ambiguous use of 'snp' (Swift4.1)

### ISSUE THREAD

**Issue by Wanlima** [SnapKit/SnapKit#509]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | git submodule add
 

### Issue Description

```
let redView:UIView = UIView()
        redView.backgroundColor = .red
        view.addSubview(redView)
        
        redView.snp.makeConstraints { (make) in

            make.center.equalTo(view)
            make.width.height.equalTo(100.0)
        }
```
Xcode prompts Ambiguous use of 'SNP' error.

**Comment by jegnux** [comment]
@Wanlima on last line you have `make.width.height.equalTo` -> `width.height`. This is not valid and the compiler gets confused.
