### ISSUE TITLE
Compare constraints

### ISSUE THREAD

**Issue by sedwo** [SnapKit/SnapKit#510]
I have the following code:

```
sectionView?.snp.updateConstraints { make -> Void in
    make.width.equalToSuperview()
    make.height.equalTo(SECTION.kHeaderHeight)

    if sectionHeader.scrollPositionOffset != sectionHeader.headerPositionOffset {
        make.top.equalTo(safeAreaInsetsTop + sectionHeader.scrollPositionOffset)
    } else {
        make.top.equalTo(safeAreaInsetsTop + sectionHeader.headerPositionOffset)
    }
}

```
which gets repeatedly called in `updateViewConstraints()`.

To optimize it, I'd like to compare if the `width` and `height` constraints are _already correctly set_ so that I don't have to call _`make`_ on them again, and simply update the `top` constraint alone.

**Comment by robertjpayne** [comment]
@sedwo if you need high performance code I recommend storing a reference to a constraint the first time you created it:

`self.topConstraint = make.top.equalTo(...)` 

and then in your updateViewConstraints code:

`self.topConstraint.constant = 5`
