### ISSUE TITLE
How cloud I use SnapKit in Objc Project???

### ISSUE THREAD

**Issue by hopy11** [SnapKit/SnapKit#512]
Hi guys ;)

I create new project with CocoaPods and of course use SnapKit in it.

and I want use third party class TreeView ,this class write by Objc.

My Q is How could I use SnapKit in class TreeView ??? Thanks ;)

**Comment by Panajev** [comment]
I think you may have an easier time with the Masonry project if you need the same functionality as SnapKit but for an Objective-C project, but your mileage may vary and while it is possible perhaps to twist SnapKit enough to work as you wish Masonry may still be your best bet (SnapKit is Masonry’s Swift successor).

**Comment by hopy11** [comment]
Thanks you @Panajev

**Comment by johndpope** [comment]
for reference https://github.com/thisfin/DigitalClock/blob/1b428ede298a720019b01467edacf87837560851/DigitalClock/DigitalClockView.m
