### ISSUE TITLE
multipliedBy not working

### ISSUE THREAD

**Issue by chimung** [SnapKit/SnapKit#513]
[ * ] I have looked at the [Documentation](http://snapkit.io/docs)
[ * ] I have read the [F.A.Q.](http://snapkit.io/faq)
[ * ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform            | ios
 Platform Version        | 9.2
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods
 

### Issue Description
I am trying make my frame of image auto change its size with "multipliedBy".
`frameImageContainer.snp.makeConstraints({(make) in
            make.width.equalTo(295).multipliedBy(0.2)
            make.height.equalTo(355).multipliedBy(0.2)
            print("ratio", ratio)
            make.top.equalToSuperview().offset(self.view.frame.height/8)
            make.centerX.equalToSuperview();
        })`

But it not working like expected. It keep their size (295x355). Can anyone figure out what i am wrong ?

**Comment by gy37** [comment]
view1.attr1 = view2.attr2 * multiplier + constant
[nslayoutconstraint ](https://developer.apple.com/documentation/uikit/nslayoutconstraint/1526954-init)
