### ISSUE TITLE
Propose to adopt Cocoapods `spec.swift_version` in podspec(s).

### ISSUE THREAD

**Issue by ShaneQi** [SnapKit/SnapKit#519]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | All
 Platform Version        | All
 SnapKit Version         | All
 Integration Method      | cocoapods
 

### Issue

Because SnapKit's podspec file doesn't explicitly declare the Swift version it's compatible with, Cocoapods sets its Swift version as the same version as the main project. 

So when SnapKit old version (< 4.0.0), which doesn't compile with Swift 4.X compiler, is a dependency of a Swift 4.X project, the project can't be compiled after `pod install`.

#### Why don't use SnapKit 4.0.0 in swift 4.X project?

For example: `MyProject` is a Swift 4.1 project, `MyPrivateLib` is a Swift 3.3 library. SnapKit 3.2.0 is a dependency of `MyPrivateLib`, and `MyPrivateLib` is a dependency of `MyProject`. 

In this case, I have to use SnapKit 3.2.0 in my Swift 4.1 project.

### Temporary Solutions 

The common solution, for now, is either manually set Swift version in SnapKit target's build setting (this needs to be done every time after `pod install`) or use Cocoapods post-install script.

### Ideal Solution / Proposal

By adopting `spec.swift_version` in SnapKit's podspec files, Cocoapods will automatically set correct Swift version for SnapKit's target, instead of using main project's Swift version.

`spec.swift_version` was released in Cocoapods 1.4.0:

People discussing mix-swfit-version issue: https://github.com/CocoaPods/CocoaPods/issues/6791
PR for `spec.swift_version`: https://github.com/CocoaPods/CocoaPods/issues/7134

### Implementation of Proposal

1. Go back to every podspec file we have pushed to Cocoapods repo, and add the `spec.swift_version` spec according to the swift version every SnapKit version is compitable with.
2. Push every modified podspec file again to Cocoapods repo to update the existing podspec files.

**Comment by rhysforyou** [comment]
This should be fixed going forward if / when #541 gets merged. Though we'll still have to go and update old versions.

**Comment by robertjpayne** [comment]
Closing as issue is syntax error not a SnapKit issue
