### ISSUE TITLE
[Feature Request] make contentSize to be ConstraintRelatableTarget for scrollable views

### ISSUE THREAD

**Issue by AV8R-** [SnapKit/SnapKit#523]
### New Issue Checklist

* [ x ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ x ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ x ] I have filled out this issue template.

## Introduction

`UIScrollView` layout relies on the explicitly specified size constraints. `contentSize` is the inner property that used to calculate the scrollable area.

## Motivation

Sometimes the size of `UIScrollView` must be equal to the size of its content. For example when you rendering the `UITableView` inside other `UIScrollView`. The situation gets more complicated when the size of the child `UITableView` is dynamically changing. 
[Example of such screen](https://lh5.googleusercontent.com/qRiTHZ4-V7rddN6tj4SPNMMywew1oTAxlaw0UT-7np-Iv9KkXYlnYDcNzxSQjF2MmiR3yX9wkI1SGAyf3dJM=w1898-h1822)

## Proposed solution

Allow to use `contentSize` as constraint target
```
tableView.snp.makeConstraints { make in
    make.height.equalTo(tableView.snp.contentSize.height)
}
```
or even with shortland syntax
```
tableView.snp.makeConstraints { make in
    make.height.equalToContent()
}
```

## Impact on existing code

This functionality is strictly additive and does not break any existing
code: it only adds one more option to constraint targets, and
does not change the behavior of any old constraint targets.

## Alternatives considered
The primarily alternative here is to do nothing: we can add some observers to `contentSize` and update constraints as it changes manually in client code.

**Comment by sharp3dges** [comment]
👍 Is there any way to get around this until it's implemented?
I need this to resize my tableview for a Eureka form.

**Comment by Tawfikk** [comment]
Who will help me solve such a problem ? 

I have a tableView into ScrollView -> ContentView, and I want set to dynamic height in willDisplayCell, but he's don't work for me. 

Thanks. @AV8R- @sharp3dges
