### ISSUE TITLE
Carthage Update Issue

### ISSUE THREAD

**Issue by hallelujahbaby** [SnapKit/SnapKit#532]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.0
 SnapKit Version         | 4.0.0
 Integration Method      | Carthage
 

### Issue Description

`github "SnapKit/SnapKit" ~> 4.0.0`

When use `Carthage update` , carthage download 0.40.0 beta instead of 4.0.0

**Comment by robertjpayne** [comment]
@hallelujahbaby this is a Carthage issue not a SnapKit issue, unfortunately I can't do anything to "fix" their version resolver
