### ISSUE TITLE
如何使组件的顶部位置为自身高度的一半

### ISSUE THREAD

**Issue by xiaoli-style** [SnapKit/SnapKit#535]
topView2.snp.makeConstraints({
            make in
            make.height.equalTo(topView).dividedBy(1.5)
            make.width.equalTo(topView).dividedBy(5)
            **make.top.equalTo(topView2.snp.height).dividedBy(2)//顶部位置为自身高度的一半**
            make.centerX.equalToSuperview()
        })

这种写法报错，请问下正确的写法 应该是怎样的？

**Comment by robertjpayne** [comment]
Closing as this does not follow issue template.
