### ISSUE TITLE
ImageView.frame is Zero

### ISSUE THREAD

**Issue by KosratDAhmad** [SnapKit/SnapKit#536]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.4
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapods

 

### Issue Description

After I set width and height constraint to an image view but when I get `Image.frame.width` it returns 0

Code snipt 

    let imageView: UIImageView = {
       let image = UIImageView(frame: .zero)
        image.backgroundColor = .lightGray
        image.contentMode = .scaleAspectFill
        image.layer.cornerRadius = 2
        image.clipsToBounds = true
        return image
    }()

    imageView.snp.makeConstraints { make in
        make.leading.top.bottom.equalTo(self).inset(UIEdgeInsets(top: 10, left: 8, bottom: 10, right: 0))
        make.width.height.equalTo(66)
    }

    print("image view: \(imageView.frame.width)")  // output: 0.0

**Comment by dev4dev** [comment]
Because it hasn't been layout yet. try to check its frame in `viewDidAppear`

**Comment by robertjpayne** [comment]
@KosratDAhmad what @dev4dev has said here is true, adding constraints does not immediately apply a layout, for that the most parent superview needs to have layoutSubviews run which normally involves invoking `setNeedsLayout` and `layoutIfNeeded`
