### ISSUE TITLE
Feature request: No calls to fatalError in production code

### ISSUE THREAD

**Issue by berikv** [SnapKit/SnapKit#537]
### New Issue Checklist

* [✅] I have looked at the [Documentation](http://snapkit.io/docs)
* [✅] I have read the [F.A.Q.](http://snapkit.io/faq)
* [✅] I have filled out this issue template.

### Issue Description

SnapKit validates its inputs and when an error is detected it calls `fatalError`.
Calling `fatalError` makes it easy to discover an issue while developing, but when the code is in production a call to `fatalError` causes a crash for an end-user. This can cause a recoverable application error to become an unavoidable crash.

### Suggested Implementation

Create an Error type that (is part of or) extends `ConstraintDescription` and captures error information.
Instantiate and return the Error type instead of calling `fatalError` when an input validation error occurs.
Add a custom error handler to `ConstraintMaker`.
In `endMakingConstraints` call the custom error handler passing the errors that have occurred when it is set. If the custom error handler is not set, call `fatalError` with the joined list of error descriptions.

I have not yet researched the overall impact of this suggestion on SnapKit's source code and I am looking for feedback before attempting an implementation.

**Comment by robertjpayne** [comment]
The purpose of fatal errors is because these errors are actually fatal and not resolvable. They should *not* be happening under normal circumstances and therefore should be corrected during testing and not be silenced via try/catch handlers.
