### ISSUE TITLE
How to add identifier to constraint 

### ISSUE THREAD

**Issue by iOSDias** [SnapKit/SnapKit#539]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 9.3
 SnapKit Version         |  - SnapKit (~> 4.0.0)
 Integration Method      | cocoapods
 

### Issue Description

Could you help me with answer for question how to set identifier or name to constraint like in easy-peasy? It is necessary to work with folding cell library of Ramotion, because : 
To create a FoldingCell, you must initialize the two above views, as well as a top constraint for each of them, named foregroundViewTop and containerViewTop, respectively. In the example, these are created with EasyPeasy, a library which provides convenient syntax for working with constraints programmatically.

In Easy-Peasy it makes like 
let top = (foregroundView <- [Top(8)]).first
    top?.identifier = "ForegroundViewTop"

**Comment by robertjpayne** [comment]
@iOSDias not really sure what Easy-Peasy is doing here, if you need specifics to integrate with another library you may just need to use the normal auto layout API's for that part of your code
