### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50: Xcode 10 Error

### ISSUE THREAD

**Issue by paulosaure** [SnapKit/SnapKit#540]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [Yes] I have looked at the [Documentation](http://snapkit.io/docs)
* [Yes] I have read the [F.A.Q.](http://snapkit.io/faq)
* [Yes] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 12.0
 SnapKit Version         | SnapKit (~> 4.0.0)
 Integration Method      | carthage
 

### Issue Description

Hello,

When trying to compile my project (with SnapKit as a Carthage) I get the following error message: Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50

Can you release a new version please ?

**Comment by uson1x** [comment]
You have to recompile the SnapKit using latest Command Line Tools (latest Xcode).
Try to run `carthage update SnapKit`

**Comment by paulosaure** [comment]
Hum, I tried but nothing ... 

I recompiled SnapKit and replace it in build carthage folder but UIView doesn't recognize snapkit anymore ...

Then I tried `carthage update SnapKit` but nothing I got already the last release 4.0.0

**Comment by uson1x** [comment]
@paulosaure the motivation to run `carthage update` is not to get newer version, but to have it rebuilt using new Xcode build system. You can run `carthage build` with the same effect.

What do you mean by 
> UIView doesn't recognize snapkit anymore ...
?

**Comment by paulosaure** [comment]
I finally succeeded.

Thanks for your help ;) !

**Comment by robertjpayne** [comment]
Sounds like this is resolved!
