### ISSUE TITLE
Xcode 10 and Swift 4.2 support

### ISSUE THREAD

**Issue by lolgear** [SnapKit/SnapKit#543]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 11.4
 SnapKit Version         | e.g. 4.0.0
 Integration Method      | e.g.cocoapods
 

### Issue Description

Subject

**Comment by jkiley129** [comment]
When do you anticipate a release to support Swift 4.2? Currently I have had to direct my pod file to compile Snapkit using Swift 4 to get my project to run.

**Comment by robertjpayne** [comment]
@jkiley129 can you explain further? the project compiles fine using Swift 4.2 or Swift 4.0 (it has #if flags) and should be fine?

**Comment by superlin** [comment]
Any plans for supporting Xcode 10 and Swift 4.2?

**Comment by robertjpayne** [comment]
Released with SnapKit 4.2.0

**Comment by soheilnikbin** [comment]
I updated pod to `pod 'SnapKit', '~> 4.2.0'` but still cannot build the project.
