### ISSUE TITLE
4.0.1 breaks existing code

### ISSUE THREAD

**Issue by marcelofabri** [SnapKit/SnapKit#544]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 12.0
 SnapKit Version         | 4.0.1
 Integration Method      | CP
 

### Issue Description

Just updated to 4.0.1 and now my existing code fails to compile:

```swift
stackView.snp.makeConstraints { make in
    make.edges.equalTo(snp.margins).priority(.required - 1) // Ambiguous use of 'required'
}
```

It looks like #466 and #467 touched this, so they might have broken this. It's not unfixable because I could explicitly use `UILayoutPriority.required - 1` but it feels worse.

**Comment by robertjpayne** [comment]
@marcelofabri hm that's really weird, what version were you running before? It doesn't feel like anything changed that should actually make this fail except maybe Xcode 10?

**Comment by marcelofabri** [comment]
I was on 4.0.0 and actually downgraded back to it and everything is fine again. Currently using Xcode 10.

**Comment by diogot** [comment]
We had an extension that was making things hard for the compiler.
```Swift
public extension UILayoutPriority {
    static func + (lhs: UILayoutPriority, rhs: Float) -> UILayoutPriority {
        return UILayoutPriority(rawValue: lhs.rawValue + rhs)
    }
}
```
After removal it was working without issues.
