### ISSUE TITLE
Silence Xcode 'Conversion to Swift 4.2 is available' warning

### ISSUE THREAD

**Issue by jessecoding** [SnapKit/SnapKit#548]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        |  9.0
 SnapKit Version         | 4.0.1
 Integration Method      | cocoapods
 xcode                            | 10
 

### Issue Description

Silence Xcode 'Conversion to Swift 4.2 is available' warning

**Comment by robertjpayne** [comment]
@jessecoding this is fixed in `develop` and will release a new version in the next 1-2 weeks

**Comment by ibrahimkteish** [comment]
@robertjpayne although I am pointing to the develop branch in my current project but the warning wont disappear

Platform : ios
SnapKit Version: 4.0.1
xcode: 10.0
Swift: 4.2
Integration Method: `pod 'SnapKit', :git => 'git@github.com:SnapKit/SnapKit.git', branch: 'develop'`

**Comment by ibrahimkteish** [comment]
@robertjpayne please take a look at my PR [#551](https://github.com/SnapKit/SnapKit/pull/551)
