### ISSUE TITLE
Xcode warns to upgrade to Swift 4.2 - new release?

### ISSUE THREAD

**Issue by benpackard** [SnapKit/SnapKit#549]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x ] I have looked at the [Documentation](http://snapkit.io/docs)
* [x ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

Will there be a (cocoapods) release with the latest commit, which fixes the 'Upgrade to Swift 4.2' warning in Xcode? Thanks.

**Comment by ibrahimkteish** [comment]
[#551](https://github.com/SnapKit/SnapKit/pull/551) should fix it

**Comment by sisufo** [comment]
+1

**Comment by robertjpayne** [comment]
Released with SnapKit 4.2.0
