### ISSUE TITLE
Syntax update need for Swift 4.2

### ISSUE THREAD

**Issue by trevor-sonic** [SnapKit/SnapKit#550]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info
In the `public enum TrackingMode: CustomStringConvertible`
a syntax changes must be made for Swift4.2 compatibility like:
from (current)
```swift 
RunLoopMode.UITrackingRunLoopMode.rawValue
```
to (new)
```swift
RunLoop.Mode.tracking.rawValue
```
AND
from (current)
```swift
RunLoopMode.commonModes.rawValue
``` 
to (new)
```swift
RunLoop.Mode.common.rawValue
```

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios 12
 Platform Version        | Swift 4.2
 SnapKit Version         | 4.0.1
 Integration Method      | cocoapods
 

### Issue Description

On Xcode 10 Swift 4.2 I had compile error.
I provide above the correction for fixing the issue.

**Comment by robertjpayne** [comment]
Released with SnapKit 4.2.0
