### ISSUE TITLE
error in Typealiases.swift with Xcode 10.1

### ISSUE THREAD

**Issue by VisualEcho** [SnapKit/SnapKit#557]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [*] I have looked at the [Documentation](http://snapkit.io/docs)
* [*] I have read the [F.A.Q.](http://snapkit.io/faq)
* [*] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                 | iOS
 Platform Version        | 12.1
 SnapKit Version           | 4.0.0
 Integration Method      | cocoapods
 

### Issue Description

I have updated my Xcode to 10.1 yesterday. And when I rebuild my project after install pods, I got several errors in Typealiases.swift. line 28 and line 29
`
```swift
#if os(iOS) || os(tvOS)
    import UIKit
    typealias LayoutRelation = NSLayoutRelation     // error: 'NSLayoutRelation' has been renamed to 'NSLayoutConstraint.Relation'
    typealias LayoutAttribute = NSLayoutAttribute   // error: 'NSLayoutAttribute' has been renamed to 'NSLayoutConstraint.Attribute'
    typealias LayoutPriority = UILayoutPriority
#else
    import AppKit
    typealias LayoutRelation = NSLayoutConstraint.Relation
    typealias LayoutAttribute = NSLayoutConstraint.Attribute
    typealias LayoutPriority = NSLayoutConstraint.Priority
#endif
```
`

**Comment by ZanderDev** [comment]
Until this is solved with an official iOS 12 / Swift 4.2 release, you can add something like this to your Podfile to ensure SnapKit continues to use Swift 4.1:

swift_4_1_pod_targets = ['SnapKit']

post_install do | installer |
    installer.pods_project.targets.each do |target|
        if swift_4_1_pod_targets.include?(target.name)
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
