### ISSUE TITLE
Value of type 'NSLayoutYAxisAnchor' has no member 'snp' when using safeAreaLayoutGuide 

### ISSUE THREAD

**Issue by alouanemed** [SnapKit/SnapKit#560]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |   ios 
 Platform Version        |  11.0
 SnapKit Version         |   4.0
 Integration Method      |   cocoapods
 

### Issue Description

I am trying to use safeAreaLayoutGuide with snap, so I changed my code per the docs from this : 

```
     view.snp.makeConstraints { (make) in
            make.left.right.equalToSuperview()
            make.top.equalTo(self.topLayoutGuide.snp.bottom)
            make.bottom.equalTo(self.bottomLayoutGuide.snp.top)
        }
```
  To this : 
```
...
            make.top.equalTo(self.view.safeAreaLayoutGuide.topAnchor.snp.bottom)
            make.bottom.equalTo(self.view.safeAreaLayoutGuide.bottomAnchor.snp.top)
...
```

The I error I get : 

> Value of type 'NSLayoutYAxisAnchor' has no member 'snp' 
 

Thanks.

**Comment by OlafAndreas** [comment]
I think you have it mixed up, try the following:
```
make.top.equalTo(self.view.safeAreaLayoutGuide.snp.bottom)
make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
```

Any luck?

**Comment by alouanemed** [comment]
Hi @OlafAndreas , Thank you for your reply!

When I submitted this issue I was just getting started on using Snap, and yeah I mixed it up :D .

Thanks you !
