### ISSUE TITLE
Incorrect behavior of inset with some types of anchors

### ISSUE THREAD

**Issue by jenox** [SnapKit/SnapKit#568]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 12.1
 SnapKit Version         | e.g. 4.2
 Integration Method      | e.g. manually
 

### Issue Description

Some types of anchors work incorrectly in combination with `inset`, whose mental model is insetting the box of the constraint relatable target before taking its anchors.

#### Center

```
make.size.equalToSuperview().inset(5)
make.center.equalToSuperview().inset(5)
```

should have the same effect as

```
make.edges.equalToSuperview().inset(5)
```

but currently the center is displaced by (5, 5). I would expect the center to match its superview's center if the inset is equal on all sides.

#### Baselines

```
make.lastBaseline.equalToSuperview().inset(5)
```

pushes the view's last baseline _below_ its superview's last baseline. This adjustment should happen in the opposite direction — after all, we inset the superview's box.

**Comment by Cyberbeni** [comment]
I also have a PR for centerX/Y for a while: https://github.com/SnapKit/SnapKit/pull/524

@robertjpayne what's the status on this?
