### ISSUE TITLE
remake constraints is not removing previous constraints

### ISSUE THREAD

**Issue by mmdock** [SnapKit/SnapKit#571]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info
Platform: iOS
Platform Version: 12.1.4
SnapKit Version: 4.2.0
Integration Method: cocoapods

### Issue Description

I first make a view as such:

```
        expandableInfoView.snp.makeConstraints({make in
            make.bottom.equalToSuperview()
            make.left.right.equalToSuperview()
            make.height.equalTo(92)
        })
```

Later, there is a button the user can tap to expand this view.  Here is the code:

```
    @objc func willChangeState(){

        if state == .collapsed {
                state = .expanded
                self.expandableInfoView.snp.remakeConstraints({ make in
                    make.bottom.equalToSuperview()
                    make.left.right.equalToSuperview()
                    make.top.equalToSuperview().offset(42)
                })
                UIView.animate(withDuration: 0.8, animations: {
                    self.layoutIfNeeded()
                })
            }
       }
```
After doing this, the following conflict occurs:

   "<SnapKit.LayoutConstraint:0x106757690@ProfileStackView.swift#92 Datt.ProfileCard:0x10eb9dac0.height == 566.0>",
    "<SnapKit.LayoutConstraint:0x106c21480@ProfileCard.swift#301 UIView:0x1070d4800.bottom == Datt.ProfileCard:0x10eb9dac0.bottom>",
    "<SnapKit.LayoutConstraint:0x106c21e20@ProfileCard.swift#303 UIView:0x1070d4800.top == Datt.ProfileCard:0x10eb9dac0.top + 42.0>",
    "<SnapKit.LayoutConstraint:0x106c24860@ProfileCard.swift#173 UIView:0x1070d4800.height == 92.0>"

So the mystery is, the height == 92 constraint was added in the initial layout.  According to SnapKit's documentation, remakeConstraints "will first remove all existing constraints installed by SnapKit".

So, why wasn't that removed before making the new constraints?

Additionally, I tried replacing .remakeConstraints with the following:

```
self.expandableInfoView.snp.removeConstraints()
self.expandableInfoView.snp.makeConstraints({ make in

```

Once again, I receive the same group of conflicting constraints with the height == 92 still existing.

EDIT: I have since updated to 5.0.1 and still see this behavior

**Comment by BossOz** [comment]
I'm figuring out the same issue in SnapKit v5.0.1

**Comment by mmdock** [comment]
> I'm figuring out the same issue in SnapKit v5.0.1

@BossOz did you ever figure this out ?

**Comment by Chesong-Lee-Hospii** [comment]
I am also seeing this.

**Comment by ckalolass** [comment]
Same here. Any update on it?

**Comment by jalone87** [comment]
Same here. Any news?

**Comment by ZhangDihan** [comment]
Same here. Any update?

**Comment by kevinlee-app** [comment]
any update?

**Comment by SeanRoberts** [comment]
Has anyone found an update or workaround for this?

**Comment by EeshwarH** [comment]
Any update for this? Having a very similar issue.

**Comment by xdh725** [comment]
Same here. and I use `view.snp.removeConstraints()` and `view.snp.makeConstraints()` to instand of `view.snp.remakeConstraints()`, and sovled this warning issue.
Because remakeConstraints only remove the items within the block you passed in, it does not remove all previous constraints you added.

一样的问题. 我用`view.snp.removeConstraints()` 和 `view.snp.makeConstraints()` 替代了`view.snp.remakeConstraints()`解决了这个警告问题。
因为remakeConstraints 只会移除你传入的block包含的item，并不会移除之前所有添加的约束。

```
    // before make constraints
    gamePlayersView.snp.makeConstraints { make in
        make.top.left.right.equalTo(view)
        make.height.equalTo(360)
    }
    // after remake constraints, and the left constraints will not removed
    gamePlayersView.snp.remakeConstraints { make in
        make.right.equalTo(view)
        make.width.equalTo(70)
        make.bottom.equalTo(chatInputView.snp.top)
        make.top.equalTo(view).offset(8)
    }

    internal static func remakeConstraints(item: LayoutConstraintItem, closure: (_ make: ConstraintMaker) -> Void) {
        self.removeConstraints(item: item)
        self.makeConstraints(item: item, closure: closure)
    }

    internal static func removeConstraints(item: LayoutConstraintItem) {
        let constraints = item.constraints
        for constraint in constraints {
            constraint.deactivateIfNeeded()
        }
    }
```

**Comment by MrJorgeXavier** [comment]
I'm also having the same issue. The last version of the library was launched on 2019, and theres a bunch of pull requests with fixes open.. This library is extremely awesome and useful, but it's still being maintained?

**Comment by zhuweifeng314** [comment]
我有一个发现。

```
// 会出现警告：类似 view1.top 和 view2.bottom 冲突之类的，但明明后面我有一句 view2.removeConstraints。
view1.remakeConstraints...
view2.removeConstraints...

// 不会出现警告
view2.removeConstraints...
view1.remakeConstraints...
```

根据上面的案例，我初步判断，这两句代码，总体上，如果一起执行完，是不会出现警告的。但如果先执行`view1.remakeConstraints`， view2 上面的约束还没去掉，这时候就造成冲突了，出现警告了。如果先执行`view2.removeConstraints`再执行`view1.remakeConstraints`，执行过程中都不会造成约束冲突。

所以，在重建约束的过程中，除了整体约束不冲突以外，还要保证任何执行单元在执行的过程中都不会造成冲突，这样就不会出现警告了。
