### ISSUE TITLE
Support swift 5

### ISSUE THREAD

**Issue by smolskyaleksey** [SnapKit/SnapKit#580]

**Comment by romanwb** [comment]
Update carthage (or pods)
`carthage update --platform ios`

**Comment by smolskyaleksey** [comment]
in Podspec file
  s.swift_version = '4.2'

**Comment by fish-yan** [comment]
i have many errors after i update xcode to 10.2

**Comment by windseason** [comment]
Snapkit Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

**Comment by cloc** [comment]
@windseason is correct.
The project I'm working on uses a lot of pods and SnapKit is preventing us from moving to Swift 5. I get `cannot load underlying module for 'SnapKit'` when trying to migrate using Xcode's conversion tool.

**Comment by robertjpayne** [comment]
Latest develop should now support Swift 5

**Comment by smolskyaleksey** [comment]
Do you create tag? Do you update version in podspec file?

**Comment by cloc** [comment]
@robertjpayne Awesome man! 🍻

I edited my Podfile to try the `develop` branch
`pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git', :branch => 'develop'`
`pod install`
But I get the same error when migrating.

Maybe I need to do something else 🧐

**Comment by PreAnti** [comment]
Why the latest version is still 4.2.0?

**Comment by yusuftor** [comment]
Can you guys release the swift 5 version as an update please!

**Comment by Damonvvong** [comment]
So, When will Swift 5 Tag release ?

**Comment by lm2343635** [comment]
When will Swift 5 Tag release~

**Comment by Dwar3xwar** [comment]
When will Swift 5 Tag release~

**Comment by robertjpayne** [comment]
This is done, see the releases page
