### ISSUE TITLE
Create release that supports Swift 5.0

### ISSUE THREAD

**Issue by alexpersian** [SnapKit/SnapKit#583]
Currently the most recent release here and on Cocoapods trunk is 4.2.0. This release doesn't play well with Xcode 10.2.

Please create release from latest `develop` to include the support for Swift 5.0.

**Comment by aymericio** [comment]
That would be better but stop crying, you can do it like that for the moment 😗 

```
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git', :branch => 'develop'
```

**Comment by alexpersian** [comment]
> stop crying
Haha, seriously dude?

**Comment by kylebrowning** [comment]
@alexpersian that response aside I would recommend looking at the issue queue before creating new issues.

https://github.com/SnapKit/SnapKit/issues/580

**Comment by alexpersian** [comment]
Thanks @kylebrowning. Closing this issue since that one covers the request for release within the comments.
