### ISSUE TITLE
Initial setup constraints code shouldn't be written in "updateConstraints" method

### ISSUE THREAD

**Issue by Huanhoo** [SnapKit/SnapKit#585]
Hi,

According to the [Apple Developer Document](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ModifyingConstraints.html)

> In general, you can make these changes at any time. Ideally, most constraints should be set up in Interface Builder, or programatically created by the view controller during the controller’s initial setup (for example, in viewDidLoad). If you need to dynamically change constraints at runtime, it’s usually best to change them when the application’s state changes. For example, if you want to change a constraint in response to a button tap, make that change directly in the button’s action method.

Apple's recommended most constraints should be set up in Interface Builder or during the controller’s initial setup (for example, in viewDidLoad).

But you suggest writing the "adding" code in the updateConstraints method which will add (include initial setup constraints) constraints to UIView

![image](https://user-images.githubusercontent.com/3039189/56333257-0cf03b00-61c6-11e9-8a97-b33d83291876.png)

Incorrect comments will lead developer to write inappropriate code. I have found that many developers will write the initial setup constraint code in "updateConstraints" method and said that this is what the Snapkit team suggested doing this.

So your [document](http://snapkit.io/docs/) should be modified?

Note: I also opened the same issue in "[Masonry](https://github.com/SnapKit/Masonry/issues/558)".

**Comment by cntrump** [comment]
> https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ModifyingConstraints.html
>
> Update Pass
>
>The system traverses the view hierarchy and calls the updateViewConstraints method on all view controllers, and the updateConstraints method on all views. You can override these methods to optimize changes to your constraints (see [Batching Changes](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ModifyingConstraints.html#//apple_ref/doc/uid/TP40010853-CH29-SW2)).
