### ISSUE TITLE
swift5 when use have a error Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by HackerChris** [SnapKit/SnapKit#592]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️ 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/23093086/56860953-b4434e00-69ce-11e9-942a-081600ec11c4.png">
Thread 1: signal SIGABRT

**Comment by HackerChris** [comment]
only me meet this problem?

**Comment by bill350** [comment]
@HackerChris can you complete the **Issue Info** part please?

**Comment by HackerChris** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/23093086/56872336-915e7b80-6a5a-11e9-8259-028a3e01ea78.png">
That's all the code

**Comment by HackerChris** [comment]
I run in ios12.2 swift5.0 and Xcode10.2.1
