### ISSUE TITLE
"Migration guide" link broken in Readme

### ISSUE THREAD

**Issue by LinusU** [SnapKit/SnapKit#597]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | n/a
 Platform Version        | n/a
 SnapKit Version         | n/a
 Integration Method      | n/a
 

### Issue Description

The "Migration guide" link in the readme doesn't lead anywhere. Wanted to look up what has changed between 4.x and 5.x ☺️

**Comment by b-onc** [comment]
I'm also having a hard time finding a CHANGELOG. Wanted to check why my UI was broken after I've changed to 5.0
