### ISSUE TITLE
snapkit No support for iOS10 or below?

### ISSUE THREAD

**Issue by MoShenGuo** [SnapKit/SnapKit#598]
hello snapkit No support for iOS10 or below?What do you do with that? thank you

**Comment by wangyutao0424** [comment]
We need support iOS 9, please…

**Comment by WeMadeCode** [comment]
We need support iOS 8, please…

**Comment by codeguesser** [comment]
please support ios 8,thanks

**Comment by robertjpayne** [comment]
See #605
