### ISSUE TITLE
Snapkit with scrollview content size problem

### ISSUE THREAD

**Issue by kamokaizen** [SnapKit/SnapKit#599]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 12.0
 SnapKit Version         | 4.2.0
 Integration Method      | cocoapods
 

### Issue Description

 first of all, thanks for creating such a good framework, my problem is that i cant setup scrollview content properly. i missed something. Below is my code;

    lazy var scrollView : UIScrollView = {
        let scrollView = UIScrollView()
        scrollView.backgroundColor = Color.white
        return scrollView
    }()
    
    lazy var box : UIView = {
        let box = UIView()
        box.backgroundColor = Color.white
        return box
    }()
    var chartView: PieChartView!    
    var vehicleSummaryVC: VehicleSummaryVC

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.addSubview(scrollView)
        scrollView.addSubview(box)
        
        scrollView.snp.makeConstraints { (make) in
            make.edges.equalTo(self.view)
        }
        box.snp.makeConstraints { (make) in
            make.top.bottom.equalTo(scrollView)
            make.left.right.equalTo(self.view)
            make.width.equalTo(scrollView)
            make.height.equalTo(scrollView)
        }

        setupChartView()
        let detail = getDetail()
        box.addSubview(vehicleSummaryVC.view)
        box.addSubview(detail)
        box.addSubview(chartView)
        
        vehicleSummaryVC.view.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(box.snp.top).offset(0)
            make.left.equalTo(box.snp.left).offset(0)
            make.right.equalTo(box.snp.right).offset(0)
            make.width.equalTo(box.snp.width)
            make.height.equalTo(370)
        }
        detail.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(vehicleSummaryVC.view.snp.bottom).offset(10)
            make.left.equalTo(box.snp.left).offset(10)
            make.right.equalTo(box.snp.right).offset(-10)
            make.width.equalTo(box.snp.width)
        }
        chartView.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(detail.snp.bottom).offset(10)
            make.left.equalTo(box.snp.left).offset(10)
            make.right.equalTo(box.snp.right).offset(-10)
            make.width.equalTo(box.snp.width)
            make.height.equalTo(500)
        }
    }

    func setupChartView() { chartView = PieChartView() }

    func getDetail() -> CardPartStackView {
        let mainSVVertical = CardPartStackView()
        mainSVVertical.spacing = 10
        mainSVVertical.distribution = .fill
        mainSVVertical.axis = .vertical
        
        let modelYearButton = CardPartsUtil.getButton(target: self, action: #selector(modelYearButtonTapped), event: .touchUpInside)
        let usageButton = CardPartsUtil.getButton(target: self, action: #selector(usageButtonTapped), event: .touchUpInside)
        let modelYearItem = CardPartsUtil.generateItemWithElement(letfLabelText: "model_year".localized(), element: modelYearButton)
        let usageItem = CardPartsUtil.generateItemWithElement(letfLabelText: "usage".localized(), element: usageButton)
        let seperator = CardPartSeparatorView()
        mainSVVertical.addArrangedSubview(modelYearItem)
        mainSVVertical.addArrangedSubview(usageItem)
        mainSVVertical.addArrangedSubview(seperator)
        
        return mainSVVertical
    }

**Comment by kamokaizen** [comment]
<img width="398" alt="Screen Shot 2019-05-22 at 1 30 46 AM" src="https://user-images.githubusercontent.com/3720242/58135729-3cb2b880-7c34-11e9-8798-fe584358bc58.png">

Content view size not automatically set for uiscrollview, so chart is missing. need to set content view size manually?

**Comment by kamokaizen** [comment]
Is there anybody to help ?

**Comment by PuscaGhenadie** [comment]
In this:
chartView.snp.makeConstraints { (make) -> Void in
        make.top.equalTo(detail.snp.bottom).offset(10)
        make.left.equalTo(box.snp.left).offset(10)
        make.right.equalTo(box.snp.right).offset(-10)
        make.width.equalTo(box.snp.width)
        make.height.equalTo(500)
    }
You need to add:
make.bottom.equalTo(box.snp.bottom).
constrain the chart view bottom to the box bottom.

**Comment by kamokaizen** [comment]
Hi PuscaGhenadie, thanks for the help,
i did it and add the bottom constraint into chartView. it makes chartView visible but, main scroll view content size is not increased. other parts are shrinked.

<img width="320" alt="Screen Shot 2019-05-26 at 1 40 51 PM" src="https://user-images.githubusercontent.com/3720242/58380640-1e461780-7fbc-11e9-930a-59fa602e0aae.png">

This is the baseVC, the other view extend from this.

class BaseVC : UIViewController {
    
    lazy var scrollView : UIScrollView = {
        let scrollView = UIScrollView()
        scrollView.backgroundColor = Color.white
        return scrollView
    }()
    
    lazy var box : UIView = {
        let box = UIView()
        box.backgroundColor = Color.white
        return box
    }()
    
    let bag = DisposeBag()
    
    init() {
        super.init(nibName: nil, bundle: nil)
    }
    
    required public init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = Color.white
        prepareNavigationItem()
        self.view.addSubview(scrollView)
        scrollView.addSubview(box)
        
        scrollView.snp.makeConstraints { (make) in
            make.edges.equalTo(self.view)
        }
        box.snp.makeConstraints { (make) in
            make.top.bottom.equalTo(scrollView)
            make.left.right.equalTo(self.view)
            make.width.equalTo(scrollView)
            make.height.equalTo(scrollView)
            make.bottom.equalTo(scrollView.snp.bottom)
        }
        setAdditionalConstraints()
    }
    
    func prepareNavigationItem() {
        fatalError("Subclasses need to implement this method.")
    }
    func setAdditionalConstraints() {
        fatalError("Subclasses need to implement this method.")
    }
}

This is the childView, extends from baseVC

class VehicleValueVC : BaseVC, ChartViewDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
        
    override func setAdditionalConstraints(){
        let detail = getDetail()
        box.addSubview(vehicleSummaryVC.view)
        box.addSubview(detail)
        box.addSubview(chartView)
        
        vehicleSummaryVC.view.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(box.snp.top).offset(0)
            make.left.equalTo(box.snp.left).offset(0)
            make.right.equalTo(box.snp.right).offset(0)
            make.width.equalTo(box.snp.width)
            make.height.equalTo(370)
        }
        detail.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(vehicleSummaryVC.view.snp.bottom).offset(10)
            make.left.equalTo(box.snp.left).offset(10)
            make.right.equalTo(box.snp.right).offset(-10)
            make.width.equalTo(box.snp.width)
        }
        chartView.snp.makeConstraints { (make) -> Void in
            make.top.equalTo(detail.snp.bottom).offset(10)
            make.left.equalTo(box.snp.left).offset(10)
            make.right.equalTo(box.snp.right).offset(-10)
            make.width.equalTo(box.snp.width)
            make.height.equalTo(500)
            make.bottom.equalTo(box.snp.bottom)
        }
    }
}

**Comment by PuscaGhenadie** [comment]
@kamokaizen This is for sure not the problem with the SnapKit, your constraints are not set somewhere right, from your code my first guess would be:

Change this:
  box.snp.makeConstraints { (make) in
        make.top.bottom.equalTo(scrollView)
        make.left.right.equalTo(self.view)
        make.width.equalTo(scrollView)
        make.height.equalTo(scrollView)
        make.bottom.equalTo(scrollView.snp.bottom)
    }
to:
box.snp.makeConstraints { (make) in
        make.top.bottom.equalTo(scrollView)
        make.left.right.equalTo(self.view)
 }
remove the width and height constraint, it's not needed, you have set already top and bottom (this can be the cause of the issue, but not sure).

**Comment by kamokaizen** [comment]
no chance. yes it is not issue with core snapkit. its issue related with fucking scroll view content size not changed. i tried with set content size manually, no work.

**Comment by kamokaizen** [comment]
@PuscaGhenadie your suggestion is true but not enough to success. but i tried all cases then  i did it to set content size properly. Magical point is offset() 

chartView.snp.makeConstraints { (make) -> Void in
make.top.equalTo(detail.snp.bottom).offset(10)
make.left.equalTo(box.snp.left).offset(10)
make.right.equalTo(box.snp.right).offset(-10)
make.width.equalTo(box.snp.width)
make.height.equalTo(500)
make.bottom.equalTo(box.snp.bottom).offset(0)
}
