### ISSUE TITLE
Causes the view not to show when setting a partial fillet of the view 

### ISSUE THREAD

**Issue by chujiandaochuxia** [SnapKit/SnapKit#600]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        |  10
 SnapKit Version         |  '~> 4.0.0'
 Integration Method      |  cocoapods
 

### Issue Description
Causes the view not to show when setting a partial fillet of the view .
How should I set part of the fillet

let path = UIBezierPath(roundedRect: self.bounds, byRoundingCorners: UIRectCorner.allCorners, cornerRadii:CGSize(width: 10, height: 10))
let maskLayer = CAShapeLayer()
maskLayer.frame = bounds
maskLayer.path = path.cgPath
self.layer.mask = maskLayer

**Comment by greezi** [comment]
I these two days have also met this question.

**Comment by yiruchujian** [comment]
我现在的解决方案是 在view上添加个圆角图片 如果有其他更好的解决方案请告诉我

**Comment by SunOfSoul** [comment]
bounds没有拿到，都是0
