### ISSUE TITLE
Make right and left constraints in UIStackView

### ISSUE THREAD

**Issue by grifas** [SnapKit/SnapKit#603]
* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 12.0.1
 SnapKit Version         | 5.0.0
 Integration Method      | cocoapods
 

### Issue Description

I would like to set right and left constraints of a subview in a vertical UIStackView, but when I apply the followed code, just the left constraint worked.
```
verticalStackView.addArrangedSubview(subview)

subview.snp.makeConstraints { make in
 make.left.right.equalToSuperview().inset(15)
 make.height.equalTo(44)
}
```

How to fix that ?

**Comment by nodediggity** [comment]
Autolayout wouldn't work in a `UIStackview` - that isn't how they are intended to be used.

You _could_ add a container `UIView` to the stack and make your subview a child of _that_.

This would allow you to enable constraints on your view. 

```swift
        let myVerticalStackview = UIStackView(frame: .zero)
        myVerticalStackview.axis = .vertical

        let myContainerView = UIView(frame: .zero)
        let mySubview = UIView(frame: .zero)

        myContainerView.addSubview(mySubview)

        mySubview.snp.makeConstraints { make in
            make.left.right.equalToSuperview().inset(15)
            make.height.equalTo(44)
        }

        [myContainerView].forEach { myVerticalStackview.addSubview($0) }
```

**Comment by Mildwhale** [comment]
Same issue here and I solved it.
If you set `alignment` to `fill` the subview will fills to fit the size of the stackview.
So you just set the `alignment` to `center` that's it.
