### ISSUE TITLE
`updateConstraints` not working with `width` `multipliedBy` attributes

### ISSUE THREAD

**Issue by joeljfischer** [SnapKit/SnapKit#604]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 12.3
 SnapKit Version         | 5.0.0
 Integration Method      | cocoapods
 

### Issue Description

I've seen that this has been opened a few times before, but I'm currently frustrated with what I'm seeing in my project, and it doesn't seem to correlate exactly with others' usage. Below is example code:

```swift
// In one method called early
progressView.snp.remakeConstraints { (make) in
    make.leading.equalToSuperview()
    make.top.equalToSuperview()
    make.bottom.equalToSuperview()
    make.width.equalToSuperview().multipliedBy(timerPercentComplete)
}

// Also in the code
override func updateConstraints() {
    progressView.snp.updateConstraints { (make) in
        make.width.equalToSuperview().multipliedBy(timerPercentComplete)
    }

    super.updateConstraints()
}
```

I'm getting:

```
Thread 1: Fatal error: Updated constraint could not find existing matching constraint to update: <SnapKit.LayoutConstraint:0x600001e2f480@StepView.swift#197 UIView:0x7ff7ee6227d0.width == XXX.StepView:0x7ff7ee71eab0.width * 2.7620041370391846>
```

Does `updateConstraints` simply not work for this use case?

**Comment by Overcot** [comment]
@joeljfischer 
```
progressView.snp.remakeConstraints { (make) in
    make.leading.equalToSuperview()
    make.top.equalToSuperview()
    make.bottom.equalToSuperview()
    make.width.equalToSuperview().multipliedBy(timerPercentComplete)
}
```
Where exactly do you call these lines of code? 
Maybe your view not exactly in view hierarchy and constraints didn't activate? 
Put a skipping breakpoint before `progressView.snp.updateConstraints` and check if you have this constraint activated

**Comment by benpackard** [comment]
Here is a full failing test case for this issue.

```
override func viewDidLoad() {
		super.viewDidLoad()

		view.backgroundColor = .red

		let container = UIView()
		container.backgroundColor = .yellow
		container.translatesAutoresizingMaskIntoConstraints = false
		view.addSubview(container)
		container.snp.makeConstraints { make in
			make.top.bottom.leading.equalToSuperview()
			make.width.equalToSuperview().multipliedBy(1)
		}

		container.snp.updateConstraints { make in
			make.width.equalToSuperview().multipliedBy(0.5)
		}
	}
```

**Comment by LukasHromadnik** [comment]
I think this can be closed. More info here #386

**Comment by benpackard** [comment]
@LukasHromadnik I agree, I wasn't aware of this limitation but of course it makes sense.
