### ISSUE TITLE
Why SnapKit 5.0.0 with support for swift 5.0 only support iOS 10 or higher?

### ISSUE THREAD

**Issue by wudijimao** [SnapKit/SnapKit#605]
I wonder that, why SnapKit 5.0.0 with support for swift 5.0 only support iOS 10 or higher?

**Comment by Adrift001** [comment]
I wonder that, why SnapKit 5.0.0 with support for swift 5.0 only support iOS 10 or higher?

**Comment by Adrift001** [comment]
I think iOS 9 should be supported!

**Comment by figureai** [comment]
> I think iOS 9 should be supported!

yes, I think so

**Comment by Adrift001** [comment]
Who can answer my question?

**Comment by Adrift001** [comment]
Who can answer my question?

**Comment by Adrift001** [comment]
Who can answer my question??

**Comment by dqb101140127** [comment]
I think iOS 9 should be supported!

**Comment by Hstripe** [comment]
Pls support iOS 9~

**Comment by cddjr** [comment]
+1

**Comment by Adrift001** [comment]
who can answer my question?

**Comment by youzg** [comment]
> I think iOS 9 should be supported!

yes, I think so

**Comment by robertjpayne** [comment]
You can continue to use SnapKit 4.2 if you need iOS 9 support. There are a number of changes that make backwards compatibility harder and harder to maintain. At this point iOS 9 is nearly 4 years old and I don't have any intention of supporting it anymore.

There's no reason you can't just continue use SnapKit 4.2, it'll compile fine and you can use both Swift 4/5 modules in the same project.

**Comment by zhanwufeng** [comment]
Thank you for your reply to help me solve this problem

**Comment by jzdeng** [comment]
你好，我已经收到您发来的邮件，祝您身体健康，万事如意^_^     -邓江洲
