### ISSUE TITLE
ios11.3显示错乱，子布局获取不到父布局的top属性

### ISSUE THREAD

**Issue by jackydhc** [SnapKit/SnapKit#610]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by jackydhc** [comment]
ios11.3显示错乱，子布局获取不到父布局的top属性

**Comment by Adrift001** [comment]
兄弟,能不能不用中文?

**Comment by cddjr** [comment]
来段代码看看呀
