### ISSUE TITLE
Unable to use custom tableHeaderView with snap kit

### ISSUE THREAD

**Issue by nandha-kumar** [SnapKit/SnapKit#612]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 12.2
 SnapKit Version         | 0.19.0
 Integration Method      | manually
 

### Issue Description

I am trying to set custom tableHederView whose frame will get set based on its content. But the custom tableHeaderView is not rendering.  Not sure what causing this issue.

    class ViewController: UIViewController {
    private var tableView: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView = UITableView(frame: CGRect.zero, style: .plain)
        tableView.clipsToBounds = false
        tableView.separatorStyle = UITableViewCell.SeparatorStyle.none
        tableView.backgroundColor = UIColor.lightGray
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 70.0
        tableView.showsHorizontalScrollIndicator = false
        tableView.showsVerticalScrollIndicator = false
        
        view.addSubview(tableView)
        tableView.snp.makeConstraints({ make in
            make.top.equalTo(40)
            make.left.right.bottom.equalToSuperview().inset(20)
        })
        
        let headerView = UIView(frame: CGRect.zero)
        headerView.backgroundColor = UIColor.green
        tableView.tableHeaderView = headerView
        headerView.snp.makeConstraints({ make in
            make.left.right.top.bottom.equalToSuperview()
        })
        
        let label = UILabel(frame: CGRect.zero)
        label.text = "I have a custom view that assign to tableHeaderView. I used snapkit to made custom view layout. But the headerview is never shown."
        label.numberOfLines = 0
        label.lineBreakMode = .byWordWrapping
        label.textAlignment = .center
        headerView.addSubview(label)
        label.snp.makeConstraints({ make in
            make.left.right.bottom.equalToSuperview().inset(20)
        })
 
    }
   }

Screenshot for reference,

![Simulator Screen Shot - iPhone Xs - 2019-07-15 at 21 21 07](https://user-images.githubusercontent.com/4947528/61259721-6b876f80-a749-11e9-96b1-68e7ef889db7.png)

**Comment by dong09000** [comment]
headerView.snp.makeConstraints({ make in
        make.left.right.top.bottom.equalToSuperview()
    })

you should set a frame for headerView，try it
