### ISSUE TITLE
Update Quick Start section of Readme.md

### ISSUE THREAD

**Issue by iosmo** [SnapKit/SnapKit#616]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Description

Having followed the guide to setting things up I added the code from the code snippet from the `Quick Start` section of the readme. I could not see the view that the code was referring to. 

Adding `box.backgroundColor = .green` before the constraint setup allowed me to see the view that was added.

I think updating the readme with the above line might help others in future.

I have a branch ready to submit as a PR however I have no permissions to create the PR. Happy to help if needed.

| Before | After |
|---|---|
| <img width="584" alt="Screenshot 2019-07-29 at 09 21 13" src="https://user-images.githubusercontent.com/32336260/62032696-3ca9d880-b1e2-11e9-9307-1c3d43f1e2bd.png"> | <img width="584" alt="Screenshot 2019-07-29 at 09 19 43" src="https://user-images.githubusercontent.com/32336260/62032652-2439be00-b1e2-11e9-82ef-abe9f61b6239.png"> |

**Comment by robertjpayne** [comment]
@iosmo You should be fine to create a PR? I don't have it blocked?

**Comment by iosmo** [comment]
I cloned and branched instead of forking. Sorted now 👍
