### ISSUE TITLE
Unable to build on XCode 11

### ISSUE THREAD

**Issue by seljabali** [SnapKit/SnapKit#621]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS 13.0
 Platform Version        | 13.0
 SnapKit Version         | 5.0.1
 Integration Method      | carthage
 XCode      | 11.0 beta 5

### Issue Description

Hello, I'm unable to build my app due to SnapKit on XCode 11 beta 5 with an error message `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/...../SnapKit.swiftmodule/x86_64.swiftmodule`

I saw this pull request https://github.com/SnapKit/SnapKit/pull/615/ for the latest version `5.0.1`, hence assumed the effort to support XCode 11.

**Comment by hiddevdploeg** [comment]
I would love to see this too, I'm pretty much stuck now and can't work on any features for iOS 13. Anyone knows a workaround for this maybe?

**Comment by Mazyod** [comment]
If you have multiple Xcode versions installed, double check which version is `xcodebuild` using by running `xcode-select -p`. It needs to be pointing to Xcode beta for Carthage to use that for building the framework for Swift 5.1.

In order to switch it to Xcode beta, either use:

```sh
sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer
```

or simply switch it from Xcode preferences.

**Comment by hiddevdploeg** [comment]
Fixed it by running
`sudo xcode-select -s /Applications/Xcode-beta.app`
 
Then run carthage update
`carthage update --platform iOS` 

thanks @Mazyod
