### ISSUE TITLE
make.center.equalToSuperview()  无效报约束冲突

### ISSUE THREAD

**Issue by enamor** [SnapKit/SnapKit#623]
版本5.0.1 make.center.equalToSuperview()  无效报约束冲突

**Comment by mrrhysbutler** [comment]
I see the same issue, seems using .centerX.centerY. resolves issue, but it's not ideal.

**Comment by qiuncheng** [comment]
I meet too.

**Comment by Ricardo1980** [comment]
Same here

**Comment by lzzhoujielun** [comment]
I have the same problem that whenever I update the center constraint, I will report a constraint conflict
