### ISSUE TITLE
constraint(equalToSystemSpacingBelow:multiplier:) not supported

### ISSUE THREAD

**Issue by kevinmbeaulieu** [SnapKit/SnapKit#630]
### New Issue Checklis

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios/tvos
 Platform Version        | All
 SnapKit Version         | 5.0.1
 Integration Method      | All
 

### Issue Description

When laying out a series of labels vertically, [constraint(equalToSystemSpacingBelow:multiplier:)](https://developer.apple.com/documentation/uikit/nslayoutyaxisanchor/2866022-constraint) is useful, but it is not currently supported in SnapKit as far as I can tell. While it is possible to create this constraint using vanilla UIKit and the rest of our constraints in SnapKit, it would be ideal if we could do something like
```
label2.snp.makeConstraints { make in 
    make.firstBaseline.equalToSystemSpacingBelow(label1.snp.lastBaseline).multipliedBy(1)
}
```
which would be analogous to
```
label2.firstBaselineAnchor.constraint(equalToSystemSpacingBelow: label1.lastBaselineAnchor, multiplier: 1).isActive = true
```

If this is a feature people would be open to adding, I can look into what it would take to support it.

**Comment by robertjpayne** [comment]
Ah I closed your PR but I see this actually has a system API. Unfortunately it doesn't look like there is any way to get that "standard spacing" without the visual format parsing? Due to the inner workings of SnapKit and remake/update constraints I worry about that actually working that well?
