### ISSUE TITLE
Why SnapKit 5.x not support iOS9

### ISSUE THREAD

**Issue by kagenZhao** [SnapKit/SnapKit#631]
Why SnapKit 5.x not support iOS9

**Comment by ShenYj** [comment]
+1

**Comment by yaochenfeng** [comment]
+1

**Comment by robertjpayne** [comment]
iOS 9 is now 5 years old and obsoleted by Apple from security updates or any software updates. Unfortunately it's not feasible for us to continue to support platforms this old.
