### ISSUE TITLE
Support Xcode 11 SPM

### ISSUE THREAD

**Issue by chengkaizone** [SnapKit/SnapKit#632]
Hello, I hope to provide support for Xcode 11 SPM.

**Comment by miaoruiyuan** [comment]
i hope so

**Comment by Overcot** [comment]
Isn't it already implemented in #615?

**Comment by jenhausu** [comment]
yes, it is. This PR can be closed. @robertjpayne

**Comment by Qwert547185** [comment]
pgotmaYtijpg]nj]mmts
