### ISSUE TITLE
Duplicate constraints on single view.

### ISSUE THREAD

**Issue by Kaakati** [SnapKit/SnapKit#633]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info
When I inspect the Constraints of the UI I find duplicate constraints connected to the view.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform               |  ios
 Platform Version   | 12.0
 SnapKit Version         | 5.0.0
 Integration Method      | cocoapods
 

### Issue Description
When I inspect the Constraints of the UI I find duplicate constraints connected to the view.

here is my constraints build
```swift
tableView.snp.makeConstraints { (make) in
    make.top.equalTo(mainView.snp.bottom)
    make.leading.trailing.equalTo(self).inset(16)
    make.bottom.equalTo(shipmentNotice.snp.top)
}
```
![Screen Shot 2019-10-02 at 4 36 26 PM](https://user-images.githubusercontent.com/5206411/66048900-0d418000-e533-11e9-81cb-60554ed264b4.png)

**Comment by Overcot** [comment]
@Kaakati  Where do you put thiscode? Does it called multiple times?

**Comment by Kaakati** [comment]
@Overcot No it's only called once in viewDidLoad.

**Comment by Overcot** [comment]
@Kaakati what exactly did you want to achieve with line
`make.leading.trailing.equalTo(self).inset(16) `
Maybe you meant `equalToSuperview`?

**Comment by Kaakati** [comment]
@Overcot `self` is a `viewController`

**Comment by Overcot** [comment]
> @Overcot `self` is a `viewController`

When using constraints you need to attach your views to `view` of `viewController`. Try it

**Comment by Kaakati** [comment]
@Overcot I'll try it, thanks for the help.
