### ISSUE TITLE
remakeConstraints not working !!

### ISSUE THREAD

**Issue by Goallying** [SnapKit/SnapKit#635]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | iOS 13
 SnapKit Version         | 5.0.1
 Integration Method      | cocoapods
 

### Issue Description
I add a tableView like this firstly:

        self.view.addSubview(self.tableView)
        self.tableView.snp.makeConstraints { (make) in
           if #available(iOS 11 , *){
                make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
                make.leading.equalTo(self.view.safeAreaLayoutGuide.snp.leading)
                make.bottom.equalTo(self.view.safeAreaLayoutGuide.snp.bottom)
                make.trailing.equalTo(self.view.safeAreaLayoutGuide.snp.trailing)
           }else{
                make.top.leading.bottom.trailing.equalTo(self.view)
           }
        }
then I did this :
            self.tableView.snp.remakeConstraints { (make) in
            make.top.equalTo(self.view.snp.top).offset(20)
            make.leading.bottom.trailing.equalTo(self.view)
        }
BUT NO Changes!   whats wrong ? thanks
I did this in iphone11 simulator.

**Comment by sedwo** [comment]
Where are you placing this code?

Move your `remakeConstraints` to `override func viewWillLayoutSubviews() {`

**Comment by robertjpayne** [comment]
Closing as tests confirm this isn't really an issue, use breakpoints please and make sure you're code is actually running. If still an issue isolate to a sample project if possible or provide more context!
