### ISSUE TITLE
layoutMargins not works appropriately.

### ISSUE THREAD

**Issue by minho-park** [SnapKit/SnapKit#636]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.0
 SnapKit Version         | latest version(I don't know cause of used by download zip, but I tested as latest version.)
 Integration Method      | manually
 

### Issue Description

When I use layoutMargin or directionalLayoutMargin property in UIView, it doesn't work appropriately.
For example:

        let testView = UIView()
        testView.backgroundColor = .black
        testView.directionalLayoutMargins = NSDirectionalEdgeInsets(top: 10, leading: 20, bottom: 10, trailing: 20)
        view.addSubview(testView)
        testView.snp.makeConstraints { (make) in
            make.top.leading.equalToSuperview().offset(50)
            make.size.equalTo(CGSize(width: 100, height: 100))
        }
        
        let testSubview = UIView()
        testSubview.backgroundColor = .red
        testView.addSubview(testSubview)
        testSubview.snp.makeConstraints { (make) in
            make.directionalMargins.equalToSuperview()
        }

_testSubview_'s x-position start with 12 and y-position start with 2.
As a result of my test, result position was layoutMargin property values **minus 8**
If I set layoutMargin.top = 50, result value is 42: minus 8
If I use default method provided by Apple, it works fine expectedly.

**Comment by XavierLost** [comment]
me too

**Comment by XavierLost** [comment]
use   self.xxx.snp.right

**Comment by robertjpayne** [comment]
You need to bind constraints to `leadingMargin` not `leading`
