### ISSUE TITLE
Cannot checkout version 5.0.0

### ISSUE THREAD

**Issue by shinrikiken** [SnapKit/SnapKit#638]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS 12.2
 Platform Version        | Xcode 10.2
 SnapKit Version         | 5.0.0
 Integration Method      | carthage
 

### Issue Description

I am trying to update version to support `Swift 5` by changing version in cartfile to `5.0.0`
but when it comes to checking out the branch, it checked a wrong version `Checking out SnapKit at "0.40.0.beta4"`

<img width="1238" alt="Screen Shot 2562-10-13 at 23 12 17" src="https://user-images.githubusercontent.com/16188265/66718563-77013a00-ee0f-11e9-8256-c91e509fadd7.png">

⚠️ Replace this with the description of your issue. ⚠️

**Comment by robertjpayne** [comment]
This is a carthage bug not a SnapKit bug, we can't assist in how come Carthage may resolve the wrong version.
