### ISSUE TITLE
Have constraint in make block start out as uninstalled

### ISSUE THREAD

**Issue by michaeleisel** [SnapKit/SnapKit#640]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 13.0
 SnapKit Version         | 4.0.1
 Integration Method      | cocoapods
 

### Issue Description

I have this code:
```
    self.myView.view.snp.makeConstraints { make in
      make.top.equalToSuperview()
      make.left.equalToSuperview()
      make.right.equalToSuperview()
      let bottomItem = self.view.safeArea.bottom
      self.downToBottomConstraint =
        make.bottom.equalTo(bottomItem).constraint
      self.downToMiniPlayerConstraint =
        make.bottom.equalTo(bottomItem)
          .offset(20).constraint
    }
```

You can see that it's over-constrained by the last two constraints. The idea is to only have one of them active at a time by using `install`/`uninstall`. However, this code creates a temporary constraint violation before I can call `uninstall`. Is there a simple way to fix this? And yes, I could use `updateConstraints` here, but there are lots of other places where I can't, so I want to find an alternate that I can use consistently (also I have a bunch of other objections to `updateConstraints`).

**Comment by robertjpayne** [comment]
@michaeleisel Does this actually fire errors about invalid constraints? The constraint tree is updated atomically once the closure finishes so it shouldn't matter?

**Comment by kevinmbeaulieu** [comment]
I believe you can use `prepareConstraints` for this- it creates the constraints without activating them

**Comment by michaeleisel** [comment]
@kevinmbeaulieu sounds good. Ideally, I’d just mark a single constraint as not to be immediately installed, but that sounds fine
