### ISSUE TITLE
UIButton or UITextfield couldn't work in UIScrollView

### ISSUE THREAD

**Issue by iHamburg** [SnapKit/SnapKit#642]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [yes] I have looked at the [Documentation](http://snapkit.io/docs)
* [yes] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ yes] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 13.0
 SnapKit Version         | 5.0.1
 Integration Method      | cocoapods
 

### Issue Description

when button or textfield are added  in contentview, which is added in scrollview, they couldn't be touched or input. 

Is there any workable solution for button or textfield in the scrollview? 

thx

`
let scrollView = UIScrollView()
  
      let contentView = UIView()
        view.addSubview(scrollView)
        scrollView.addSubview(contentView)
        scrollView.snp.makeConstraints { (make) -> Void in
            make.edges.equalToSuperview()
        }
        contentView.snp.makeConstraints { (make) -> Void in
            make.edges.equalTo(scrollView)
            make.width.equalTo(view) 
        }
        let btn = UIButton()
        btn.backgroundColor = .blue
        contentView.addSubview(btn)
        btn.addTarget(self, action: #selector(buttonClicked(_:)), for: .touchUpInside)

        btn.snp.makeConstraints { (make) -> Void in
            make.centerX.equalToSuperview()
            make.top.equalToSuperview().offset(100)
            make.width.equalTo(100)
            make.height.equalTo(50)
        }

        let tf = UITextField()
        tf.backgroundColor = .blue
        contentView.addSubview(tf)
        tf.snp.makeConstraints { (make) -> Void in
            make.left.equalToSuperview()
            make.top.equalTo(btn.snp.bottom).offset(50)
            make.right.equalToSuperview()
            make.height.equalTo(40)
        }`

**Comment by robertjpayne** [comment]
@iHamburg Don't think this is an issue relating to snapkit if the views are visible. You might look at some of the touch properties on UIScrollView as some will capture touches rather than sending them to subviews.

**Comment by dianyij** [comment]
add the height constraint of contentView
  
```patch
contentView.snp.makeConstraints { (make) -> Void in
        make.edges.equalTo(scrollView)
+       make.width.equalTo(scrollView) 
+       make.height.greaterThanOrEqualTo(scrollView)
}
```

**Comment by johnosorio** [comment]
> add the height constraint of contentView
> 
> ```diff
> contentView.snp.makeConstraints { (make) -> Void in
>         make.edges.equalTo(scrollView)
> +       make.width.equalTo(scrollView) 
> +       make.height.greaterThanOrEqualTo(scrollView)
> }
> ```

Thanks, this works for me.
