### ISSUE TITLE
父视图的1/3处不起作用

### ISSUE THREAD

**Issue by shuilanjianyue** [SnapKit/SnapKit#648]
在父视图的1/3处怎么实现呀。不是宽度1/3处。是离左边1/3处
make.width.equalToSuperview().dividedBy(3)
make.height.equalTo(49)
make.leading.equalToSuperview().dividedBy(6)。不起作用

**Comment by kevinmbeaulieu** [comment]
For anyone who comes across this, my Chinese is hit or miss but I believe the question is how to get the leading edge of a view to be inset from the superview's leading edge by 1/3 the superview's width. i.e. something like `make.leading.equalTo(superview.snp.width).dividedBy(3)`, except that attempting to do that results in `NSInvalidArgumentException ... Invalid pairing of layout attributes.`

**Comment by dengfeng520** [comment]
```
       let testView = UIView()
        self.view.addSubview(testView)
        testView.layer.backgroundColor = UIColor.red.cgColor
        testView.snp.makeConstraints { [weak self] (make)  in
            make.width.equalToSuperview().dividedBy(3)
            make.height.equalTo(49)
            make.left.equalTo(self!.view.snp.left).offset(self!.view.frame.width / 3)
            make.centerY.equalTo(self!.view)
       }
```

**Comment by benlue1992** [comment]
因为这是明显的语义错误，leading 和 left 一样，它是一个比较属性值，参考的是equalTo(view)的X值
