### ISSUE TITLE
How to get constant from SnapKit

### ISSUE THREAD

**Issue by Korefey** [SnapKit/SnapKit#652]
Tell me please, how to get constant positionX for testButton (as it is done in frames) after set constraints to testButton.

`self.testButton.snp.makeConstraints { (make) -> Void in
      make.centerX.equalTo(self.carListView)
      make.width.equalTo(200)
      make.height.equalTo(20)
      make.top.equalTo(self.carListArray.last!.snp.bottom).offset(14)
  }`

**Comment by Overcot** [comment]
You can't
You need to wait when viewLays out correctly and then get the value of centerX using frame like this:
`
let centerX= self.testButton.frame.center.x
`

**Comment by JonathanChen123** [comment]
> You can't
> You need to wait when viewLays out correctly and then get the value of centerX using frame like this:
> `let centerX= self.testButton.frame.center.x`

so how to make sure that the view finished layouts?

**Comment by Overcot** [comment]
> > You can't
> 
> > You need to wait when viewLays out correctly and then get the value of centerX using frame like this:
> 
> > `let centerX= self.testButton.frame.center.x`
> 
> 
> 
> so how to make sure that the view finished layouts?

In your viewController you can do it in `viewDidLayoutSubviews` or in view in `layoutSubviews`
