### ISSUE TITLE
iOS 10 crash

### ISSUE THREAD

**Issue by AfrozZaheer** [SnapKit/SnapKit#656]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                                                   |           iOS
 Platform Version                                       |         10.3.1
 SnapKit Version                                         |          4.0.1
 Integration Method                                     |       cocoapods
 

### Issue Description

App successfully build but crash at runtime on iOS version 10.3.1.. Attached is the image showing crash where it occurred. If I put check if available iOS 11.0, * then it works fine 

<img width="1440" alt="Screenshot 2020-02-21 at 7 06 50 PM" src="https://user-images.githubusercontent.com/25176835/75030767-cb17db80-54df-11ea-8c8d-9ea1bb65eaa9.png">

**Comment by martinpucik** [comment]
@AfrozZaheer could you put together an example project where I'll be able to reproduce this crash?

**Comment by martinpucik** [comment]
@AfrozZaheer did you resolve the cause of the crash?

**Comment by AfrozZaheer** [comment]
Hi, I don't know what but when I update the pod it works fine.
