### ISSUE TITLE
Unexpected behaviour UILabel's width with '.greaterThanOrEqualTo'.

### ISSUE THREAD

**Issue by thomasneuteboom** [SnapKit/SnapKit#658]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 11.3.1
 SnapKit Version         | 5.0.1
 Integration Method      | Cocoapods
 

### Issue Description

I'm expecting a `UILabel` to resize to its intrinsic content size when constraining it to the superview's center, with leading and trailing constraints relation set to 'Greater Than Or Equal'. Instead, SnapKit displays the `UILabel` in full width. I've created an example with Storyboard and Snapkit, both having the same constraints. Am I missing something here?

**SnapKit code:**
```
class SnapKitExampleViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let snapKitLabel = UILabel()
        snapKitLabel.text = "SnapKit example"
        snapKitLabel.textColor = .white
        snapKitLabel.backgroundColor = .purple
        self.view.addSubview(snapKitLabel)
        
        // Setup constraints.
        snapKitLabel.snp.makeConstraints { (make) in
            make.center.equalTo(self.view.safeAreaLayoutGuide)
            make.leading.greaterThanOrEqualTo(self.view.safeAreaLayoutGuide).offset(15)
            make.trailing.greaterThanOrEqualTo(self.view.safeAreaLayoutGuide).offset(-15)
        }
    }

}
```

### With **Storyboard** constraints (expected behaviour):

![Schermafbeelding 2020-03-03 om 15 18 12](https://user-images.githubusercontent.com/1652432/75784646-d500d080-5d62-11ea-80a7-24fca6ba13d6.png)

![Schermafbeelding 2020-03-03 om 15 16 56](https://user-images.githubusercontent.com/1652432/75784637-cfa38600-5d62-11ea-9f9c-358b1f0dfcbc.png)

### With **SnapKit** constraints (unexpected behaviour):

![Schermafbeelding 2020-03-03 om 15 18 24](https://user-images.githubusercontent.com/1652432/75784734-f19d0880-5d62-11ea-9523-61db574e5840.png)

**Comment by martinpucik** [comment]
@thomasneuteboom could you please also add an example recreated with `NSLayoutConstraint`s?

**Comment by thomasneuteboom** [comment]
Hi @martinpucik, thanks for your reply! I tested it with standard `NSLayoutConstraint`'s and the problem seems to persist. Apparently it has nothing to do with SnapKit. I'll address this issue somewhere else. Thank you.

**Comment by wojciech-kulik** [comment]
You have incorrect trailing constraint. It should be:
```
make.leading.greaterThanOrEqualTo(self.view.safeAreaLayoutGuide).offset(15)
make.trailing.lessThanOrEqualTo(self.view.safeAreaLayoutGuide).offset(-15)
```
