### ISSUE TITLE
Create a Sample App

### ISSUE THREAD

**Issue by omidkh68** [SnapKit/SnapKit#66]
is anyone have sample executable app with this library?

**Comment by stormhouse** [comment]
firefox-ios  https://github.com/mozilla/firefox-ios

**Comment by robertjpayne** [comment]
@omidkh68 @stormhouse there's not an example app yet, your best bet is to look at some of the tests or just play around along with the readme.

It may help to look at Masonry examples too as Snap is a port of it.

**Comment by omidkh68** [comment]
@robertjpayne  tnx man

**Comment by mwawrusch** [comment]
I know it's a bit of work, but it would be so much more useful if you would provide use cases (with a picture) and corresponding code). The current docs are a tough read for people who aren't into autolayout every day (me ;-))

**Comment by sahandnayebaziz** [comment]
Hey guys. I saw this issue and, as a big fan, thought it'd be fun to contribute. I spent a little time on an app we could use to teach people how to use SnapKit and show off great use cases. Not to worry, no pressure to use this, I don't know if you've all already started on something. Just wanted to throw it out there. You can see it here, I just gave it a quick name of [SnapKit Samples](https://github.com/sahandnayebaziz/SnapKit-Samples).

I tried to keep a couple of qualities in mind, namely that the sample app would be...
+ somewhat easy to browse as a reference
+ somewhat easy to contribute to

The way it's hooked up now is a simple tableView that's listing out objects of a small type called 'Sample'. To contribute a sample, somebody would have to add a 'Sample' struct to the 'SampleLibrary' file and add a viewController that shows off the hands-on SnapKit use case they want to demonstrate. 

I figure everyone must use SnapKit in their own special way, so I'm hoping this structure of each individual sample in the sample app will encourage someone to contribute another when they get excited about what they're doing with SnapKit. 

I've put a couple basic samples in there. The code for each example is broken down and commented the way I'd explain it to somebody who was new to SnapKit and doesn't use AutoLayout all the time.

It was fun to make and I hope it gives you some ideas. Cheers.

**Comment by neelamsharma12** [comment]
I have created one sample application of SnapKit using Cocoapods. please have a look. Here is the link: 
https://github.com/SnapKit/SnapKit/pull/180

**Comment by migore** [comment]
@sahandnayebaziz Your sample was very useful to me. Thanks!

To whoever might be searching for samples, [this project](https://github.com/richeterre/SwiftGoal) was also helpful.

**Comment by robertjpayne** [comment]
This is done! Thanks to #201 whoop!
