### ISSUE TITLE
Offset and inset not working

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [SnapKit/SnapKit#660]
When I call this snippet of code:

myView.snp.updateConstraints { make in
      make.centerY.equalToSuperview().inset(offset)
}

or

myView.snp.updateConstraints { make in
      make.centerY.equalToSuperview().offset(offset)
}

The inset and the offset methods are not taken into account

**Comment by robertjpayne** [comment]
This issue does not follow the issue template and has been closed.
