### ISSUE TITLE
Interface Builder now it's transparent and doesn't auto update

### ISSUE THREAD

**Issue by matheusmaus** [SnapKit/SnapKit#661]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 13.4
 SnapKit Version         | 5.0.1
 Integration Method      | Carthage
 

### Issue Description

After updating my Xcode to Version 11.4 (11E146) I started to have the following issue: 

```
_error: IB Designables: Failed to render and update auto layout status for UIView (iN0-l3-epB): dlopen(Components.framework, 1): Library not loaded: @rpath/SnapKit.framework/SnapKit
  Referenced from: Components.framework
  Reason: image not found_
```

I need to update because I had an issue that only iOS 13.4 fixed.

Already clean the Derived Data Folder and debugging via console.

**Comment by matheusmaus** [comment]
Temporary fix: 

I needed to install Xcode 11.3.1 back to my machine and all of my stuff I need to do in the IB I do in the Xcode 13.3.1 and the rest, like coding, Xcode 11.4.

**Comment by robertjpayne** [comment]
I believe this is no longer an issue nor a SnapKit specific issue so closing.
