### ISSUE TITLE
Xcode11.4 Swift5.2 support

### ISSUE THREAD

**Issue by desmondYing** [SnapKit/SnapKit#662]
I use Carthage to integrate SnapKit into my project:

"github "SnapKit/SnapKit" ~> 5.0.0"

When my Xcode update to 11.4 version, the error occurs:

"Module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2 compiler"

**Comment by klundberg** [comment]
If you rebuild your carthage dependencies using Xcode 11.4, this error will go away. You'll need to make sure `xcode-select -p` points to the right version of xcode, if you have multiple on your computer.

**Comment by desmondYing** [comment]
That's it! Thanks a lot!
