### ISSUE TITLE
How to use aspect ratio constraint?

### ISSUE THREAD

**Issue by rafagan** [SnapKit/SnapKit#668]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 13.0
 SnapKit Version         | latest
 Integration Method      | cocoapods
 

### Issue Description

I trying to create an aspect ratio constraint 1:1. How can I achieve that?

**Comment by rafagan** [comment]
In swift I've done in that way:
`
extension UIView {
    func aspectRatio(_ ratio: CGFloat) -> NSLayoutConstraint {
        return NSLayoutConstraint(item: self, attribute: .height, relatedBy: .equal, toItem: self, attribute: .width, multiplier: ratio, constant: 0)
    }
}
`

In snapkit:

`
button.snp.makeConstraints { (make) in
                make.width.equalTo(button.snp.height).multipliedBy(1.0 / 1.0)
            }
`

**Comment by robertjpayne** [comment]
Will be possible in next release via your own extensions due to #693
