### ISSUE TITLE
Update the center constraint report conflict in the view created by xib

### ISSUE THREAD

**Issue by lzzhoujielun** [SnapKit/SnapKit#669]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [√] I have looked at the [Documentation](http://snapkit.io/docs)
* [√ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [√] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                           |    ios
 Platform Version        |  xcode11
 SnapKit Version         | 5.0.1
 Integration Method    |  cocoapods
 

### Issue Description
1. I created a UIImageVIew view through xib through the layout
2. Dynamically update the center.y constraint in this UIImageView
    The following code:
    `self.imgView.snp.updateConstraints { (make) in
                    make.centerY.equalToSuperview().offset(30)
                }`
3. Warning after running: center.Y in xib conflicts with my updated center.Y constraint

### Console print content
2020-05-19 16:10:18.701561+0800 PlayDemo[67162:9829601] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000394def0 UIImageView:0x7f8ccc738860.centerY == HeaderContentView:0x7f8ccc61d070.centerY + 24   (active)>",
    "<SnapKit.LayoutConstraint:0x600003e52040@IntroHeadView.swift#47 UIImageView:0x7f8ccc738860.centerY == HeaderContentView:0x7f8ccc61d070.centerY + 30.0>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x600003e52040@IntroHeadView.swift#47 UIImageView:0x7f8ccc738860.centerY == HeaderContentView:0x7f8ccc61d070.centerY + 30.0>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by martinpucik** [comment]
Hey @lzzhoujielun `snp.updateConstraints` will only update constraints created by SnapKit. That's why you have 2 centerY constraints in your stacktrace. If you're creating constraints from xib/storyboard, you should make `IBOutlet` from them to code so you'll be able to update the constants.
