### ISSUE TITLE
Animating constraints

### ISSUE THREAD

**Issue by trustyfrog** [SnapKit/SnapKit#67]
Do you have any examples updating and animating constraints? I've applied the same approach I used with Masonry but I'm not seeing anything happening.

**Comment by robertjpayne** [comment]
@trustyfrog can you post your example?

**Comment by trustyfrog** [comment]
var detailTopConstraint: Constraint? = nil

viewDidLoad: 
// ...
        self.detailViewController.view.snp_makeConstraints { (make) -> Void in
            
            self.detailTopConstraint = make.top.equalTo(self.view.snp_top)
            make.width.equalTo(self.view.snp_width)
            make.height.equalTo(self.view.snp_height)
            make.centerX.equalTo(self.view)
            
            return
        }

// Later on....

            if let t = self.detailTopConstraint {
                t.offset(200)
            }
            self.view.setNeedsLayout()
            self.view.layoutIfNeeded() // Also tried this in UIView.animateWithDuration

Thanks
Scott

**Comment by robertjpayne** [comment]
@trustyfrog yea I need to fix this, never realised that it works like that in Masonry.

For now you'll need to use an update block

```
updateConstraints { make in
    make.top.equalTo(self.view.snp_top).offset(200)
    return
}
```

Remember an update block can only modify constants though

**Comment by robertjpayne** [comment]
@trustyfrog the develop branch now has support for better updating:

```swift
var constraint: Constraint? = nil
view.snp_makeConstraints { (make) -> Void in
    constraint = make.edges.equalTo(UIEdgeInsetsMake(10,10,10,10))
}
constraint?.updateInsets(UIEdgeInsetsMake(20,20,20,20))
```
