### ISSUE TITLE
AppCode 2020.1 don't support code  complete

### ISSUE THREAD

**Issue by tanpengsccd** [SnapKit/SnapKit#670]
AppCode 2020.1

AppCode 2020.1
Build #OC-201.6668.159, built on April 20, 2020
Licensed to John Martino
Subscription is active until August 20, 2020
For educational use only.
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2487M
Cores: 8
Registry: max.suggested.heap.size=8192
Non-Bundled Plugins: com.appcodeplugins.swiftlint, training

### Issue Description

AppCode 2020.1 don't support code  complete.

![image](https://user-images.githubusercontent.com/13959880/82853577-b876cd80-9f38-11ea-92a8-65407dd57982.png)

**Comment by tanpengsccd** [comment]
I fonnd that 2020.1 has fixed this issue SnapKit symbols "Regression when SnapKit symbols were not resolved (OC-19568)" in https://blog.jetbrains.com/objc/

**Comment by sdyalor** [comment]
Someone help with this :(

**Comment by sdyalor** [comment]
I'm using appcode 2020.2 early access, reading some issues I found this workaround on ConstraintView.swit
don't know how or why but this fixes .snp completion
remove || os(tvOS)

![image](https://user-images.githubusercontent.com/50224521/85215158-3d87b380-b33a-11ea-94b0-c4ba652cda77.png)

This is not a fix, is a workaround :(

**Comment by kxvn-lx** [comment]
Why not use xcode instead?

**Comment by tanpengsccd** [comment]
> Why not use xcode instead?

Jetbrains's IDE  is more convenient in code complete

**Comment by robertjpayne** [comment]
Hi this isn't a SnapKit issue and as such I'm closing it.
