### ISSUE TITLE
Added by means of SPM. On iphone 5, ios 10 - Crash always.

### ISSUE THREAD

**Issue by diss1993** [SnapKit/SnapKit#681]
When we add SnapKit by SPM. We have crash on iphone 5, ios 10.

**Comment by tibo9** [comment]
Same here, crash only on iOS 10 devices with error like 
Fatal error: Invalid constraint. (filename.swift, 26): file /Users/../ConstraintMakerRelatable.swift, line 66

**Comment by robertjpayne** [comment]
@diss1993 @tibo9 Are you integrating via Xcode directly to an App Target?

**Comment by tibo9** [comment]
Yes
