### ISSUE TITLE
How to make updates with multipliedBy

### ISSUE THREAD

**Issue by blainekasten** [SnapKit/SnapKit#683]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | e.g. 8.0
 SnapKit Version         | 5.0.1
 Integration Method      | carthage
 

### Issue Description

Is it possible and how can I make updates when using a constraint based on `multipliedBy`. I'm building a playback scrubber for an audio app where the width of the scrubber is a percent of the overall whole.

So my initialization code looks like this:

```swift
scrubber.snp.makeConstraints { (make) in
  var percent = offset / duration
  if (percent.isNaN) {
    percent = 0
  }
  make.width.equalToSuperview().multipliedBy(percent)
}
```

And then in a Timer that listens for updates to the offset of the player, I run a similar set of code with `updateConstraints` like this:

```swift
scrubber.snp.updateConstraints { (make) in
  var percent = offset / duration
  if (percent.isNaN) {
    percent = 0
  }
  make.width.equalToSuperview().multipliedBy(percent)
}
scrubber.superview?.layoutIfNeeded()
```

Anytime I do this I get the `Updated constraint could not find existing matching constraint to update:`

And it says: `UIView:0x7fe661322740.width == UIView:0x7fe661309060.width * 0.0033447903115302324>`

Any ideas here?

**Comment by blainekasten** [comment]
I've found that I can do this by using `remakeConstraints`, but now I lose the ability to wrap the update in an Animation.

**Comment by apollonian** [comment]
@blainekasten I believe it is not possible to update a multiplier.

From https://github.com/SnapKit/SnapKit/issues/386#issuecomment-270847214
>... unfortunately NSLayoutConstraint's API's do not allow updating the multiplier (you have to re-build the constraint from scratch) hence we cannot do it via SnapKit. SnapKit's update method is an optimised update, it only updates the .constant value of the NSLayoutConstraint(s) for performance reasons.

**Comment by robertjpayne** [comment]
@apollonian is correct here. The API does not allow modifying the multiplier so there is no way to update it outside of removing and remaking the constraint(s).
