### ISSUE TITLE
How to change UIView height(increase and decrease) with button?

### ISSUE THREAD

**Issue by cemalsayin** [SnapKit/SnapKit#686]
#233 # New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ Y] I have looked at the [Documentation](http://snapkit.io/docs)
* [ Y] I have read the [F.A.Q.](http://snapkit.io/faq)
* [Y ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️ 

Hi i want to change my uiview's height with button; i try a code block which is in bellow however i can't use that second time it doesn't work. How it possible

```
// button click
 @objc func doPayment(sender:UIButton){
        if shouldCollapse {
            animateView(isCollapse: false,
                        buttonText: buttonTitle,
                        heighConstraint: 433)
        } else {
            animateView(isCollapse: true,
                        buttonText: buttonTitle,
                        heighConstraint: 333)
        }
    }
      
    private func animateView(isCollapse: Bool,
                             buttonText: String,
                             heighConstraint: Double) {
        shouldCollapse = isCollapse
        self.getDesignCart(_height: heighConstraint)
        _btnPay.setTitle(buttonTitle, for: .normal)
        
        UIView.animate(withDuration: 1) {
           self.view.layoutIfNeeded()
        }
    }

//design fucn 
 @objc func getDesignCart(_height: Double){
       _viewBottom.snp.makeConstraints { (make) in
            make.top.equalTo(self.view.snp.top).offset(_height)
            make.bottom.equalTo(self.view.snp.bottom).offset(-tabBarHeight2)
            make.left.right.equalTo(self.view)
            make.width.equalTo(self.view)
            //make.height.equalTo(208)
        }
```

}

**Comment by robertjpayne** [comment]
Try using `updateConstraints` rather than `makeConstraints`?
