### ISSUE TITLE
Could not find module 'SnapKit' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by abdrrhmn-usklu** [SnapKit/SnapKit#687]
Platform: Osx
Platform Version: Catalina 10.15.7
Xcode version : 12.0.1
SnapKit Version: 5.0.1

Cartfile:
github "SnapKit/SnapKit" ~> 5.0.0
github "ladmini/LZViewPager" ~> 1.2.5

command: brew update

and 

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create ... /bla /bla /... Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/SnapKit/5.0.1/Build/Intermediates.noindex/ArchiveIntermediates/SnapKit/IntermediateBuildFilesPath/UninstalledProducts/appletvos/SnapKit.framework/SnapKit /Users/abdurrahmanusuklu/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/SnapKit/5.0.1/Build/Products/Release-appletvsimulator/SnapKit.framework/SnapKit -output /bla/bla... This usually indicates that project itself failed to compile.

last error: Could not find module 'SnapKit' for target 'x86_64-apple-ios-simulator'

**Comment by bstillitano** [comment]
Same issue here @abdrrhmn-usklu did you ever resolve this?

**Comment by dotkebi** [comment]
Same issue here
* Apple Silicon MacBook Air.
*

**Comment by MoonMD** [comment]
I added this code in `podfile`

```ruby
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['VALID_ARCHS'] = 'arm64, arm64e, x86_64'
  end
end
```
and build success.

But I don’t know why the simulator architecture verification failed only snapkit.

**Comment by robertjpayne** [comment]
I don't have access to a M1 mac. Can anyone here submit a PR?

**Comment by RongLi77** [comment]
> I added this code in `podfile`
> 
> ```ruby
> post_install do |installer|
>   installer.pods_project.build_configurations.each do |config|
>     config.build_settings['VALID_ARCHS'] = 'arm64, arm64e, x86_64'
>   end
> end
> ```
> 
> and build success.
> 
> But I don’t know why the simulator architecture verification failed only snapkit.

It doesn't work for me...

**Comment by Chouee** [comment]
Same to me.

**Comment by marcnpopa** [comment]
same issue for m1 chip -> Could not find module 'SnapKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator. no solution found on stackoverflow works..
SnapKit added with SPM

**Comment by robertjpayne** [comment]
Hey all, I cannot replicate this using Cocoapods (latest) or Swift PM. Is this still an issue for anyone?

I don't support Carthage out of the box anymore.

**Comment by sakiyamaK** [comment]
I same issue for m1 chip again
Could not find module 'SnapKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator. no solution found on stackoverflow works..
SnapKit added with SPM

**Comment by tuando3i** [comment]
same issue for m1 chip again
Could not find module 'SnapKit' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator.
SnapKit added with SPM, when build for Simulator and added Excluded architectures for Any iOS Simulator SDK = arm64 then the issue happens

**Comment by paulo-coutinho** [comment]
Hi,

Im with the same problem.

There is any solution?

**Comment by robertjpayne** [comment]
Duplicate now of #708 continue all discussion there
