### ISSUE TITLE
 Terminating app due to uncaught exception ‘NSGenericException’, reason: ‘Unable to activate constraint with anchors  because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That’s illegal.’

### ISSUE THREAD

**Issue by diksha-goyal07** [SnapKit/SnapKit#694]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ✓] I have looked at the [Documentation]
* [ ✓] I have read the [F.A.Q.](http://snapkit.io/faq)
* [✓ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 14
 SnapKit Version         | 5.0.0
 Integration Method      | cocoapods
 

### Issue Description

Getting this crash :

<img width="679" alt="Screenshot 2020-12-08 at 1 26 46 PM" src="https://user-images.githubusercontent.com/68368782/101455723-07c29f80-3959-11eb-88da-edab321132d8.png">

**Comment by bstillitano** [comment]
You are likely setting a view's (GradientCoachmarkView) topMargin constraint against the bottom constraint of a UIButton without the two views being children of the same parent view. 

For constraints to work, the views referencing each other within your 'make' closure must be embedded within the same parent view.

**Comment by robertjpayne** [comment]
As above likely something to do with constraint usage, not a SnapKit bug. Try and play around with your constraints more and make sure you don't have issues relating to auto layout directly
