### ISSUE TITLE
Bug when using equalToSuperview to constraint contents to a UIScrollView

### ISSUE THREAD

**Issue by warpling** [SnapKit/SnapKit#695]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X ] I have looked at the [Documentation](http://snapkit.io/docs)
* [X ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 14.2
 SnapKit Version         | 5.0.1
 Integration Method      | cocoapods
 

### Issue Description

Using AutoLayout with UIScrollView is a tricky thing. I wanted to document this issue in case it helps others in the future but perhaps as a special-case to be added to SnapKit in future versions.

When setting up constraints such that a simple content view fits a UIScrollView horizontally but can scroll vertically it might make sense to use the following constraints:
```swift
        scrollView.snp.makeConstraints { make in
        make.edges.equalToSuperview()
    }

        contentView.snp.makeConstraints { make in
            make.width.equalToSuperview()
            make.edges.equalToSuperview()
        }
```

However this won't always size the UIScrollView correctly and seems to be different than… I would expect this to behave no differently alas…

```swift
        scrollView.snp.makeConstraints { make in
        make.edges.equalToSuperview()
    }

        contentView.snp.makeConstraints { make in
            make.width.equalTo(scrollView)
            make.edges.equalTo(scrollView)
        }
```

It appears in this case that "superview" isn't actually the scrollview even though contentView is its direct descendent! The later seems to be necessary for UIScrollView to do it's AL rule breaking magic to know how to size itself. Hopefully this saves someone else future headache and is something this wonderful library could incorporate in the future if it is indeed a "bug".

**Comment by robertjpayne** [comment]
Not sure this is really fixable, UIScrollView actually does have internal views and thus equalToSuperview isn't actually the best.

In hindsight I should have kept this "api helper" out of the core library as it's causing other issues where users are unaware there are real views in between.

**Comment by warpling** [comment]
I appreciate and use it A LOT but totally get what you mean!
Maybe a middle ground could be to add a console warning when superview is the immediately child of a `UIScrollView`? I don't actually know the internals of `UIScrollView` well so maybe this is too brittle. It's originally Apple's fault that the magic of these is unintuitive without a `contentView`. At the very least a prominent addition to the FAQ or examples would help many frantically googling I'm sure :)

**Comment by imbaTao** [comment]
It's working for me!

contentView.snp.makeConstraints { (make) in
    make.top.bottom.equalTo(self.scrollView)
    make.left.right.equalTo(self.view)
    make.width.equalTo(self.scrollView)
    make.height.equalTo(self.scrollView)
    // or:
    // make.centerX.equalTo(self.scrollView)
    // make.centerY.equalTo(self.scrollView)
}

// link
[https://stackoverflow.com/questions/52855503/using-snapkit-autolayout-with-uiscrollview](url)
