### ISSUE TITLE
ios11 snp.top has a problem

### ISSUE THREAD

**Issue by maomao520benben** [SnapKit/SnapKit#696]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 11.2.1
 SnapKit Version         | e.g. 4.2.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description
i create segmentcontrolview by myself.
self.navigationItem.titleView = self.segment
and set subviews contriants of segment. it top is  Invalid setting. 
self.btnArr.snp.distributeViewsAlong(axisType: .horizontal, fixedSpacing: 40, leadSpacing: 0, tailSpacing: 0)
        self.btnArr.snp.makeConstraints{
            $0.top.equalTo(self)
            $0.height.equalTo(40)
        }

**Comment by maomao520benben** [comment]
it appears only initialize current view.

**Comment by josharnoldjosh** [comment]
Have you tried using the safeAreaLayoutGuide ? Does this solve your issue?

**Comment by maomao520benben** [comment]
i have tried using the safeAreaLayoutGuide.it doesn‘t work.it is strange because it appears when the view is first initialized. it disappears when view is from it's child view pop to it.

**Comment by josharnoldjosh** [comment]
What exactly are you trying to do? Could you post an image of what you have, and then an image of what you want?
