### ISSUE TITLE
How to update the height with animation

### ISSUE THREAD

**Issue by LCBbest** [SnapKit/SnapKit#698]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️ 

i want to Update the height with animation，Use the following code

```
timeBackView.snp.makeConstraints { (m) in
    m.left.equalTo(0)
    m.top.equalTo(45)
    m.width.equalTo(S_W - 151)
    m.height.equalTo(0)
}

 UIView.animate(withDuration: 2) {
      self.timeBackView.snp.updateConstraints { (m) in
          m.height.equalTo(220)
      }
      self.timeBackView.superview?.layoutIfNeeded()
  }
```
Why not the top-down effect, but the effect from the upper left corner to the lower right corner?
<img width="227" alt="WechatIMG694" src="https://user-images.githubusercontent.com/12879534/103125032-b5a5ac00-46c4-11eb-9eaf-3e84cfa0e084.png">
![WechatIMG695](https://user-images.githubusercontent.com/12879534/103125034-b8080600-46c4-11eb-8bae-94b5e06de540.jpeg)

**Comment by robertjpayne** [comment]
It should work if you update the constraints *outside* the animation block and then call layoutIfNeeded() on the superview inside the block.

You may also want to call setNeedsLayout() on the view itself too.
