### ISSUE TITLE
Will not automatically wrap when override frame of tableviewcell

### ISSUE THREAD

**Issue by Liway** [SnapKit/SnapKit#700]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios   iPhone12 Pro
 Platform Version        | e.g. 14.3
 SnapKit Version         | e.g. 5.0.1
 Integration Method      | e.g. cocoapods
 

### Issue Description

`class TableViewCell: UITableViewCell {
    private lazy var titleLabel: UILabel = {
        let label = UILabel()
        label.textColor = UIColor.black
        label.font  = UIFont.systemFont(ofSize: 16)
        label.numberOfLines = 0
        return label
        
    }()
    
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        contentView.addSubview(titleLabel)
        titleLabel.snp.makeConstraints { (make) in
            make.top.equalTo(22)
            make.bottom.equalTo(-22)
            make.left.equalTo(12)
            make.right.equalTo(-12)
            
        }

    }
    
    func configureData() {
        titleLabel.text = "You should use the same reuse identifier for cell"
    }
    
    override var frame: CGRect {
        didSet {
            var tempFrame = frame
            tempFrame.origin.x += 15
            tempFrame.size.width -= 15*2
            super.frame = tempFrame

        }
    }
    
   required init?(coder: NSCoder) {
       fatalError("init(coder:) has not been implemented")
   }
       
    
}`
![截屏2020-12-30 上午11 05 35](https://user-images.githubusercontent.com/12988841/103327335-151e0600-4a8f-11eb-844b-f1c07163285d.png)

Will not automatically wrap when there is one more character in a single line

**Comment by robertjpayne** [comment]
Hi I don't believe this is a SnapKit issue as this would be iOS's text layout engine.
