### ISSUE TITLE
Is the project dead? [No]

### ISSUE THREAD

**Issue by iamszabo** [SnapKit/SnapKit#706]
This framework is awesome, I use it on every project but I'm wondering if the project is dead as there has been no new release for 2 years now.

**Comment by Ariandr** [comment]
Hi @robertjpayne 
Do you have an update on this?

**Comment by robertjpayne** [comment]
Hi fellas, the project is still stable and thus there's really been no reason for another update. The Auto Layout api hasn't really changed in years and I don't have a focus on expanding SnapKit beyond it's basics. Is there any PR's or Issues you can point to that need to be fixed for a release?

**Comment by Ariandr** [comment]
@robertjpayne 
It's great to know the project is alive :)

I'm using it in many of my projects and it's awesome. I personally don't follow any PRs since I don't experience any issues. But probably I'm not the right person to talk to about it.

**Comment by iamszabo** [comment]
It's great news that you still look out for the project. I was just asking why it hasn't been updated for a while.
I don't have any issues personally neither, so all good.
