### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by zxd-rsj** [SnapKit/SnapKit#711]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](http://snapkit.io/docs)
* [ ] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

Undefined symbols for architecture arm64:
  "nominal type descriptor for SnapKit.Constraint", referenced from:
      _symbolic _____y_____G s23_ContiguousArrayStorageC 7SnapKit10ConstraintC in SAlertManager.o
  "SnapKit.ConstraintViewDSL.prepareConstraints((SnapKit.ConstraintMaker) -> ()) -> [SnapKit.Constraint]", referenced from:
      SEngine.ConstraintArrayDSL.prepareConstraints((SnapKit.ConstraintMaker) -> ()) -> [SnapKit.Constraint] in ConstraintArrayDSL.o
  "type metadata accessor for SnapKit.Constraint", referenced from:
      SEngine.ConstraintArrayDSL.prepareConstraints((SnapKit.ConstraintMaker) -> ()) -> [SnapKit.Constraint] in ConstraintArrayDSL.o
      generic specialization <SnapKit.Constraint> of Swift._ArrayBuffer._getElementSlowPath(Swift.Int) -> Swift.AnyObject in SAlert.o
  "protocol witness table for __C.CGSize : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopUpgradeAlert.setSubUI() -> () in SPopAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopWXAlert.setSubUI() -> () in SPopAlert.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.STab.resetMenu() -> () in STab.o
      closure #1 (SnapKit.ConstraintMaker) -> () in closure #1 () -> () in SEngine.STab.resetSelected() -> () in STab.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SReloadView.(setupUI in _C385F6BF54429932FC138C069CFBA008)() -> () in SHUD.o
      merged closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SWaitView.(setupUI in _C385F6BF54429932FC138C069CFBA008)() -> () in SHUD.o
      partial apply forwarder for closure #1 (SnapKit.ConstraintMaker) -> () in static SEngine.SHUD.(screenInfo in _C385F6BF54429932FC138C069CFBA008)(Swift.String) -> () in SHUD.o
      ...
  "(extension in SnapKit):SnapKit.ConstraintBasicAttributesDSL.left.getter : SnapKit.ConstraintItem", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in static SEngine.SHUD.(screenInfo in _C385F6BF54429932FC138C069CFBA008)(Swift.String) -> () in SHUD.o
      closure #9 (SnapKit.ConstraintMaker) -> () in SEngine.SDKReceiveAlert.setupUI() -> () in SDKReceiveAlert.o
  "(extension in SnapKit):SnapKit.ConstraintBasicAttributesDSL.top.getter : SnapKit.ConstraintItem", referenced from:
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopAlert.setupUI() -> () in SPopAlert.o
      closure #2 (SnapKit.ConstraintMaker) -> () in static SEngine.SHUD.(screenInfo in _C385F6BF54429932FC138C069CFBA008)(Swift.String) -> () in SHUD.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SH5Alert.setupUI() -> () in SH5Alert.o
  "static SnapKit.ConstraintPriority.low.getter : SnapKit.ConstraintPriority", referenced from:
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SReloadView.(setupUI in _C385F6BF54429932FC138C069CFBA008)() -> () in SHUD.o
  "static SnapKit.ConstraintPriority.high.getter : SnapKit.ConstraintPriority", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SReloadView.(setupUI in _C385F6BF54429932FC138C069CFBA008)() -> () in SHUD.o
  "(extension in SnapKit):SnapKit.ConstraintBasicAttributesDSL.bottom.getter : SnapKit.ConstraintItem", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      ...
  "(extension in SnapKit):SnapKit.ConstraintBasicAttributesDSL.centerX.getter : SnapKit.ConstraintItem", referenced from:
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.STab.resetMenu() -> () in STab.o
      closure #1 (SnapKit.ConstraintMaker) -> () in closure #1 () -> () in SEngine.STab.resetSelected() -> () in STab.o
  "protocol witness table for Swift.Int : SnapKit.ConstraintOffsetTarget in SnapKit", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SNavWithSubTitle.init(frame: __C.CGRect) -> SEngine.SNavWithSubTitle in SNavBar.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.SCoinAlert.setupUI() -> () in SCoinAlert.o
  "protocol witness table for __C.UIView : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SPopEvaluateAlert.setSubUI() -> () in SPopAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopEvaluateAlert.setSubUI() -> () in SPopAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SPopContentAlert.setSubUI() -> () in SPopAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SPopContentAlert.setSubUI() -> () in SPopAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopNotificationAlert.setSubUI() -> () in SPopAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SPopNotificationAlert.setSubUI() -> () in SPopAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SPopUpgradeAlert.setSubUI() -> () in SPopAlert.o
      ...
  "protocol witness table for CoreGraphics.CGFloat : SnapKit.ConstraintOffsetTarget in SnapKit", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.SPopAlert.setupUI() -> () in SPopAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SPopAlert.setupUI() -> () in SPopAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SPopAlert.setupUI() -> () in SPopAlert.o
      ...
  "SnapKit.ConstraintViewDSL.updateConstraints((SnapKit.ConstraintMaker) -> ()) -> ()", referenced from:
      (extension in SEngine):Swift.Array.snp_updateConstraints((SnapKit.ConstraintMaker) -> ()) -> () in ConstraintArray+Extensions.o
      SEngine.ConstraintArrayDSL.updateConstraints((SnapKit.ConstraintMaker) -> ()) -> () in ConstraintArrayDSL.o
  "protocol witness table for Swift.Double : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #1 (SnapKit.ConstraintMaker) -> () in closure #1 () -> __C.UIView in SEngine.SNavBar.barView.getter : __C.UIView in SNavBar.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SAlert.layout() -> () in SAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SAlert.layout() -> () in SAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SFivePlateView.setupUI() -> () in SFivePlateView.o
  "protocol witness table for SnapKit.ConstraintViewDSL : SnapKit.ConstraintBasicAttributesDSL in SnapKit", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      ...
  "type metadata for SnapKit.ConstraintViewDSL", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      ...
  "SnapKit.ConstraintViewDSL.makeConstraints((SnapKit.ConstraintMaker) -> ()) -> ()", referenced from:
      SEngine.SInputAlert.layout() -> () in SInputAlert.o
      (extension in SEngine):Swift.Array.snp_makeConstraints((SnapKit.ConstraintMaker) -> ()) -> () in ConstraintArray+Extensions.o
      SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      closure #1 () -> __C.UIView in SEngine.SPopAlert.close.getter : __C.UIView in SPopAlert.o
      SEngine.SPopAlert.setupUI() -> () in SPopAlert.o
      SEngine.SPopEvaluateAlert.setSubUI() -> () in SPopAlert.o
      SEngine.SPopContentAlert.setSubUI() -> () in SPopAlert.o
      ...
  "(extension in SnapKit):SnapKit.ConstraintBasicAttributesDSL.right.getter : SnapKit.ConstraintItem", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in static SEngine.SHUD.(screenInfo in _C385F6BF54429932FC138C069CFBA008)(Swift.String) -> () in SHUD.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.ConstraintArrayDSL.distributeViewsAlong(axisType: __C.UILayoutConstraintAxis, fixedSpacing: CoreGraphics.CGFloat, leadSpacing: CoreGraphics.CGFloat, tailSpacing: CoreGraphics.CGFloat) -> () in ConstraintArrayDSL.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.ConstraintArrayDSL.distributeSudokuViews(fixedLineSpacing: CoreGraphics.CGFloat, fixedInteritemSpacing: CoreGraphics.CGFloat, warpCount: Swift.Int, edgeInset: __C.UIEdgeInsets) -> () in ConstraintArrayDSL.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SDKReceiveAlert.setupUI() -> () in SDKReceiveAlert.o
      closure #10 (SnapKit.ConstraintMaker) -> () in SEngine.SDKReceiveAlert.setupUI() -> () in SDKReceiveAlert.o
      closure #13 (SnapKit.ConstraintMaker) -> () in SEngine.SDKReceiveAlert.setupUI() -> () in SDKReceiveAlert.o
      closure #14 (SnapKit.ConstraintMaker) -> () in SEngine.SDKReceiveAlert.setupUI() -> () in SDKReceiveAlert.o
      ...
  "type metadata accessor for SnapKit.ConstraintItem", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      ...
  "protocol witness table for SnapKit.ConstraintItem : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      ...
  "SnapKit.ConstraintViewDSL.remakeConstraints((SnapKit.ConstraintMaker) -> ()) -> ()", referenced from:
      SEngine.SInputAlert.layout() -> () in SInputAlert.o
      (extension in SEngine):Swift.Array.snp_remakeConstraints((SnapKit.ConstraintMaker) -> ()) -> () in ConstraintArray+Extensions.o
      closure #1 () -> () in SEngine.STab.resetSelected() -> () in STab.o
      SEngine.ConstraintArrayDSL.remakeConstraints((SnapKit.ConstraintMaker) -> ()) -> () in ConstraintArrayDSL.o
      SEngine.SAlert.layout() -> () in SAlert.o
  "SnapKit.ConstraintViewDSL.removeConstraints() -> ()", referenced from:
      (extension in SEngine):Swift.Array.snp_removeConstraints() -> () in ConstraintArray+Extensions.o
      SEngine.ConstraintArrayDSL.removeConstraints() -> () in ConstraintArrayDSL.o
  "protocol witness table for CoreGraphics.CGFloat : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      ...
  "(extension in SnapKit):__C.UIView.snp.getter : SnapKit.ConstraintViewDSL", referenced from:
      SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #3 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #4 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      ...
  "protocol witness table for CoreGraphics.CGFloat : SnapKit.ConstraintMultiplierTarget in SnapKit", referenced from:
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.ConstraintArrayDSL.distributeViewsAlong(axisType: __C.UILayoutConstraintAxis, fixedItemLength: CoreGraphics.CGFloat, leadSpacing: CoreGraphics.CGFloat, tailSpacing: CoreGraphics.CGFloat) -> () in ConstraintArrayDSL.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.ConstraintArrayDSL.distributeViewsAlong(axisType: __C.UILayoutConstraintAxis, fixedItemLength: CoreGraphics.CGFloat, leadSpacing: CoreGraphics.CGFloat, tailSpacing: CoreGraphics.CGFloat) -> () in ConstraintArrayDSL.o
      closure #1 (SnapKit.ConstraintMaker) -> () in SEngine.ConstraintArrayDSL.distributeSudokuViews(fixedItemWidth: CoreGraphics.CGFloat, fixedItemHeight: CoreGraphics.CGFloat, warpCount: Swift.Int, edgeInset: __C.UIEdgeInsets) -> () in ConstraintArrayDSL.o
  "protocol witness table for Swift.Int : SnapKit.ConstraintRelatableTarget in SnapKit", referenced from:
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #5 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #6 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #7 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #8 (SnapKit.ConstraintMaker) -> () in SEngine.SInputAlert.layout() -> () in SInputAlert.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SImageAlert.setupUI() -> () in SPopAlert.o
      closure #2 (SnapKit.ConstraintMaker) -> () in SEngine.SPopEvaluateAlert.setSubUI() -> () in SPopAlert.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 10.0
 SnapKit Version         | e.g. 5.0.1
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️

**Comment by zxd-rsj** [comment]
I've tried a few ways to solve the problem
1. Remove DerivedData,pod install does not work
2.Add arm64 to "exclamated Architectures" that solve the problem of unable to find the compiled files

**Comment by zxd-rsj** [comment]
pods的原因

**Comment by dusmit** [comment]
> pods的原因

你好，请问可以详细说明一下吗？我也遇到了这个问题，谢谢

**Comment by XiaoYiS** [comment]
你好 有解决方案吗
