### ISSUE TITLE
Swift Compiler Warning - Deprecated protocol inheritance

### ISSUE THREAD

**Issue by osmar106** [SnapKit/SnapKit#715]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 14.5
 SnapKit Version         | 5.0.1
 Swift Version         | 5.3.1
 Xcode Version         | 12.5
 Integration Method      | Cocoapods
 

### Issue Description

Starting with Xcode 12.5 I am getting this warning from the compiler

_Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead_

**Comment by robertjpayne** [comment]
develop has some fixes I'll try and publish a new version over weekend

**Comment by vsanthanam** [comment]
Any updates on this?

**Comment by tr1ckyf0x** [comment]
When is it supposed to be published?

**Comment by dmitryrasulov** [comment]
There is no 'class' keyword in the actual repository. I suppose that issue should be closed

**Comment by robertjpayne** [comment]
I'll be doing a release soon to match Xcode 13 release timings

**Comment by dolzhenko-tony** [comment]
Any updates?

**Comment by Ewg777** [comment]
> develop has some fixes I'll try and publish a new version over weekend
@robertjpayne 
Which on of weekends?

Xcode 13 RC is available now

**Comment by jzdeng** [comment]
你好，我已经收到您发来的邮件，祝您身体健康，万事如意^_^     -邓江洲

**Comment by vsanthanam** [comment]
Any updates on this? Xcode 13 is has had a few releases now

**Comment by flipflopworld** [comment]
Have we removed **class** to **AnyObject**

<img width="812" alt="Screenshot 2022-01-09 at 2 57 37 PM" src="https://user-images.githubusercontent.com/53143500/148676802-ba08ed03-99f8-474d-b796-f4cb459cc2f1.png">

**Comment by jzdeng** [comment]
你好，我已经收到您发来的邮件，祝您身体健康，万事如意^_^     -邓江洲

**Comment by flipflopworld** [comment]
> 你好，我已经收到您发来的邮件，祝您身体健康，万事如意^_^     -邓江洲

太好了，当您考虑更新时...
