### ISSUE TITLE
Xcode12.5 module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by WGFcode** [SnapKit/SnapKit#719]
module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler: /Users/XXX/Library/Developer/Xcode/DerivedData/NXY-bdiioyaaxczbxlgusvqtvlkagrqv/Build/Products/Debug-iphoneos/SnapKit.framework/Modules/SnapKit.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by qyhongfan** [comment]
same problem

**Comment by corbin-miller** [comment]
So it still doesn't compile after 22 days?

**Comment by cguess** [comment]
I believe this is the solution to the problem (if it's the same I've been having) https://developer.apple.com/forums/thread/658129.

**Comment by robertjpayne** [comment]
Duplicate of #708
