### ISSUE TITLE
Status check of this project?

### ISSUE THREAD

**Issue by cguess** [SnapKit/SnapKit#727]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)
* [X] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | MacOS
 Platform Version        | V12.0 Beta
 SnapKit Version         | 5.0.1
 Integration Method      | cocoa pods
 

### Issue Description

I'm making this issue to ask for the status of this project? Given a [number](https://github.com/SnapKit/SnapKit/issues/719) [of](https://github.com/SnapKit/SnapKit/issues/708) [issues](https://github.com/SnapKit/SnapKit/issues/726) have been brought up and pretty much left aside about compiling on M1 chips, I'm wondering if there's a chance of this being updated in the future?

Given that very shortly (within weeks most likely) every Macbook sold will be ARM, this will have be resolved or else the project will somehow have to be marked as deprecated.

Since, if one is using this library in a project it's probably pretty fundamental and nearly impossible to refactor around, I'm going to personally try to fork it and see if I can get a version that at least *compiles* in the latest version of Swift on an M1, but as the maintainer @robertjpayne, any sort of guidance would be great.

I get it, maintaining open source is very hard, and less than thankless, so I'll just say this: Thank you for bringing the project to where it is now.

**Comment by cguess** [comment]
So I've found a solution for this in the medium term, described here: https://developer.apple.com/forums/thread/658129. I'll leave the rest of the comment up for the previous purpose of just checking status.

**Comment by robertjpayne** [comment]
@cguess this repo is very much still in a working stable state. I guess I've never had anyone actually give me a reproducible version of the compile bug.

I've got SnapKit running in multiple projects with no issues and I've tested it occasionally with Xcode and not had any issues so it's hard for me to continue to try and decipher issues that I have no reproducibility for.

**Comment by cguess** [comment]
It seems to be an issue when upgrading from an old version of Xcode and using Cocoapods.

I've managed to fix the issue using the guidance at the link above for people that do run into the issue. It looks like it's a compiler error on the ARM version of Xcode trying to compile to the simulator.
