### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by tadelv** [SnapKit/SnapKit#744]
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ x] I have looked at the [Documentation](http://snapkit.io/docs)
* [ x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        |  15.4
 SnapKit Version         | 5.0.1
 Integration Method      | cocoapods
 

### Issue Description

Hello, 
I am curious about the state of this project. As of 2019, there has not been a new release (even though commits/PRs were merged). I have seen a few issues asking about a new release with no definitive answers.
I tried to integrate the project via cocoapods using `git: '<git_url>', branch: 'develop'`, to get the latest changes, but the repo downloaded only the Readme and License files, no sources :(

So, does anyone have any info about this project and its next release?

Should we perhaps start a fork?

**Comment by robertjpayne** [comment]
Hey I'll have a look at the latest package managers and cut  a new release if needed.

As of now though I consider the "API" on the project to be "complete" and no further updates will likely be made.

**Comment by tadelv** [comment]
Thanks Robert!

I am mainly asking because the current version (5.0.1) has a deprecation warning regarding usage of `class` keyword instead of `AnyObject` and it triggers me :)

Thanks for building and maintaining such a helpful tool. You are greatly appreciated.

**Comment by robertjpayne** [comment]
Should be a new release up! Let me know if it doesn't work
