### ISSUE TITLE
remake_constraints doesn't remove all previous constraints

### ISSUE THREAD

**Issue by kchung14** [SnapKit/SnapKit#83]
If I don't specify a new value for the same attribute, remake_constraints tries to incorporate old constraints with the new ones.

for example:
viewA.remake... { make.left.equalTo(self.view) }

later on...

viewA.remake... { make.width.equalTo(self.view) }

sometimes, it says i have a constraint conflict with the old constraints. remake should completely erase all old constraints right?

**Comment by robertjpayne** [comment]
@kchung14 can you provide a deeper example of when it's complaining about constraint conflicts?

It should be removing all existing constraints but doesn't necessarily mean that the new ones don't have conflicts.

**Comment by kchung14** [comment]
Removing from superview then adding again before installing new constraints solved this issue.

But while I was preparing my code to copy paste in here (stripping away some app-specific offsets out of privacy concerns), I found that getting rid of one offset fixed the problem too. Maybe it's not an issue with Snap..

But this is a problem another developer working with Snap told me he encountered so I'm going to look back and search for a more concrete example.

I'll close this until then. Thanks.

**Comment by wjling** [comment]
I met the same problem. Can you tell me how to rid of one offset or are there any better solutions? Thank you
