### ISSUE TITLE
How can I set a horizontal Space Constraint?

### ISSUE THREAD

**Issue by steffimueller** [SnapKit/SnapKit#85]
I want to use SnapKit to create the same constraint as the following image shows:

![main_storyboard_ _edited](https://cloud.githubusercontent.com/assets/5350431/7395002/827162d8-ee97-11e4-99c2-a2c5c4d7bf06.png)

Is this the correct way of doing it?

```
box.snp_makeConstraints { (make) -> Void in
      make.leading.equalTo(superView.snp_leadingMargin)
}
```

**Comment by robertjpayne** [comment]
@steffimueller yup, that is the correct way, is that working for you or not?

**Comment by steffimueller** [comment]
@robertjpayne  And what if I want to change also constant, priority or multiplier like in this image: 

![main_storyboard](https://cloud.githubusercontent.com/assets/5350431/7400487/923c6728-eebd-11e4-8a9c-37a274015336.png)

**Comment by robertjpayne** [comment]
@steffimueller I strongly recommend you have a quick glance through the short but sweet docs page on http://snapkit.io/docs.

You will need to do something like:

```swift
box.snp_makeConstraints { (make) -> Void in
    make.leading.equalTo(superView.snp_leadingMargin).offset(263)
}
```

If you want to change it after it's installed:

```swift
box.snp_updateConstraints { (make) -> Void in
    make.leading.equalTo(superView.snp_leadingMargin).offset(300)
}
```

OR

```swift
let constraint: Constraint? = nil
box.snp_makeConstraints { (make) -> Void in
    constraint = make.leading.equalTo(superView.snp_leadingMargin).offset(263).constraint
}
constraint.updateOffset(300)
```

**Comment by steffimueller** [comment]
@robertjpayne Yes you are right. I read the docs but I was not sure what this meant. The ``Constant 263``from the image is in SnapKit words ``offset``? Isn't that a bit misleading?

**Comment by robertjpayne** [comment]
@steffimueller We felt `offset` was more fitting than constant for someone that hadn't used auto layout much prior to using SnapKit/Masonry. We also have `inset` which allows you to pass in `UIEdgeInsets` that get translated to the correct constant when doing more complex things like:

`make.left.top.right.equalTo(otherView).inset(UIEdgeInsetsMake(5,5,5,5))`

**Comment by robertjpayne** [comment]
Closing this as I believe your question(s) and issues have been resolved.

**Comment by steffimueller** [comment]
@robertjpayne It is a little bit confusing that when I do: 
```
      make.top.equalTo(box2.snp_top).offset(30)
      make.leading.equalTo(box2.snp_leading).offset(10)
      make.trailing.equalTo(box2.snp_trailing).offset(-10)
      
      make.size.equalTo(30).priority(100)
```
I get: 

![screenshot_01_05_15_14_12](https://cloud.githubusercontent.com/assets/5350431/7429987/23d5e494-f00c-11e4-9bfb-eda316b17032.png)

To get it right I have to set: 

```
 make.trailing.equalTo(box2.snp_trailing).offset(-10)
```

![screenshot_01_05_15_14_13](https://cloud.githubusercontent.com/assets/5350431/7429992/38bab3d0-f00c-11e4-8b9e-46d598ab4540.png)

Other than that I like your api very much. Good job. Thank you for sharing!

**Comment by steffimueller** [comment]
And when I do this: 
```
make.left.top.right.bottom.equalTo(box2).insets(UIEdgeInsetsMake(5, 5, 5, 5))
```
all the numbers are positive. Why is there a difference compared with the former api?

**Comment by robertjpayne** [comment]
@steffimueller this is entirely intentional `insets(...)` act like UIEdgeInsetsInsetRect or CGRectInset.

While it may seem counterintuitive you for right / bottom edges I think it would be even weirder if we tried to apply random heuristics. You can think of the DSL as always doing:

<leftAttribute> <relation> <rightAttribute> + <offset>

insets is simply a shortcut that sets inverts the offset to make it "inset".

**Comment by steffimueller** [comment]
Thank you that helped a lot!
