### ISSUE TITLE
What is the difference betwee these expressions?

### ISSUE THREAD

**Issue by confile** [SnapKit/SnapKit#86]
Is there any difference between these expressions? I alway get the same result: 

```
 make.top.equalTo(superView.snp_top)
 make.top.equalTo(superView.snp_topMargin)
 make.top.equalTo(superView)
```

**Comment by robertjpayne** [comment]
@confile the only one that is different is the second one.

`snp_topMargin` sets it to `NSLayoutAttributeTopMargin` which may or may not be different from `NSLayoutAttributeTop` depending on the `layoutMargins` of the view.

Otherwise they are all identical.

**Comment by confile** [comment]
Thank you!
