### ISSUE TITLE
Improve support for UIViewController's layout guides

### ISSUE THREAD

**Issue by aleffert** [SnapKit/SnapKit#91]
Maybe I'm missing something, but it seems to be impossible to constrain to the top of the bottomLayoutGuide.

One possible solution to this problem would be to expose a constructor for ConstraintItem for UILayoutSupport

**Comment by robertjpayne** [comment]
@aleffert you should be able to do:

```swift
make.top.equalTo(viewController.topLayoutGuide)
```

**Comment by aleffert** [comment]
@robertjpayne I'm confused. The top of the topLayoutGuide is at the top of the screen, the top of the bottomLayoutGuide is at the top of the toolbar or tab bar.

**Comment by aleffert** [comment]
So, as best I can tell, if you do ``make.bottom.equalTo(viewController.bottomLayoutGuide)`` it tries to anchor it to the *bottom* of the bottomLayoutGuide, which is at the bottom of the screen, not the top of the toolbar, which is what I need.

**Comment by robertjpayne** [comment]
@aleffert Not sure I follow the specifics, but the support for the layout guides is there in SnapKit you may just need to play around with what you're pinning to what?

Or are you trying to pin a layout guide to something else?

**Comment by aleffert** [comment]
I'm trying to pin a UILayoutSupport to a UIView. In particular, in the attached image, I am trying to anchor the ``bottom`` of the red view to ``bottomLayoutGuide.top``. SnapKit, as far as I can tell, does not let me specify an attribute for instances of ``UILayoutSupport``, only ``UIView``. So it only lets me anchor the bottom of the view to the bottom of the ``UILayoutSupport``. I can make this work by casting the ``UILayoutSupport`` to a ``UIView`` and then using ``snp_top`` on the layout guide, but that seems like an implementation detail I'd rather not depend on.

![bottomlayoutguide example](https://cloud.githubusercontent.com/assets/114396/7662435/6033597a-fb2a-11e4-97b0-160e331eae9d.png)

**Comment by robertjpayne** [comment]
See what you're saying, really what you want is to be able to do something like:

```swift
make.top.equalTo(viewController.bottomLayoutGuide.snp_bottom)
```

Unfortunately this is going to be really difficult because you can't provide extensions to protocols. Have you potentially tried using the iOS 8.0 layout margins instead of the layout guides? I believe they are more robust and are supported by SnapKit.

**Comment by aleffert** [comment]
Unfortunately, I still need to support iOS 7.

One possible solution would be to add functions like ``snap_top : UILayoutSupport -> ConstraintItem``. It's slightly different syntactically, but seems pretty straightforward.

A simpler solution would be to make the ConstraintItem constructor public or, to be a bit more type safe, add a UILayoutSupport specific one.

-Akiva Leffert

**Comment by robertjpayne** [comment]
Hmm it'd probably make most sense to add:

```
snp_topLayoutGuide
snp_bottomLayoutGuide
```

To UIViewControllers as an extension, these two properties would return a struct that then returns properly configured ConstraintItems.

For now use your UIView dynamic cast, I have a feeling these layout guides are going to be deprecated but if they remain in iOS 9 I'll build support for this into SnapKit.

**Comment by confile** [comment]
+1 It would be great to have: 

```
snp_topLayoutGuide
snp_bottomLayoutGuide
```

Casting to UIView is not a very elegant solution.

**Comment by robertjpayne** [comment]
Release with v0.12.0:

```swift
make.top.equalTo(viewController.snp_topLayoutGuideTop)
make.top.equalTo(viewController.snp_topLayoutGuideBottom)
make.top.equalTo(viewController.snp_bottomLayoutGuideTop)
make.top.equalTo(viewController.snp_bottomLayoutGuideBottom)
```

**Comment by i-schuetz** [comment]
How is this called after the Swift 3 migration? Couldn't find it in the migration guide.

**Comment by saltwat5r** [comment]
Alignment to bottomLayoutGuide top with inset not working.
