### ISSUE TITLE
Aspect Ratio Constraint?

### ISSUE THREAD

**Issue by sleroux** [SnapKit/SnapKit#92]
Hey there,

I can't find a way to set a view's aspectRatio constraint property using Snapkit. Is this supported?

**Comment by robertjpayne** [comment]
Hey @sleroux is this for an OS X application? or iOS? I'm not aware of any aspectRatio API's for auto layout?

**Comment by sleroux** [comment]
Sorry my bad. IB has an aspectRatio constraint as part of it's UI but there isn't one that exists through the code API.

**Comment by robertjpayne** [comment]
Will be possible in next release via your own extensions due to #693
