### ISSUE TITLE
Crashes when using release scheme on iOS 8

### ISSUE THREAD

**Issue by arbitur** [SnapKit/SnapKit#94]
When running using debug scheme it works on both ios 7/8 but when changing to release scheme which is the one used for appstore, it crashes for ios 8 on line 302 in Constraint.swift `installOnView!.addConstraints(newLayoutConstraints)`

Im testing on my device 8.2 and iphone simulator 7.1

**Comment by robertjpayne** [comment]
@arbitur can you provide a bit more info please:

* Can you post a full crash log ( or at least the relevant bits of a crash log )
* Can you confirm which version of SnapKit is embedded in your app ( and specifically are you certain it is of that version? )
* How are you embedding it into the iOS 7.1 simulator?

Thanks!

**Comment by arbitur** [comment]
@robertjpayne XCode doesnt give any crash messages at all, it just stops and puts a breakpoint on that line. Using XCode 6.3.

I installed SnapKit today using CocoaPods

Podfile: 
platform :ios, '7.1'
use_frameworks!

pod 'SnapKit', '~> 0.10.0'

Directly copied from http://snapkit.io/docs/ just changed platform

**Comment by robertjpayne** [comment]
@arbitur eep I probably need to update the docs. Can you update to 0.11.0? I think there were crashers in 0.10.0.

Also be careful, iOS 7.x doesn't support dynamic frameworks for app store submissions.

cheers,
Robert

**Comment by arbitur** [comment]
@robertjpayne Which are those frameworks? I didnt quite understand the documents. Can I fix it manually? I need to support ios 7 and 8.

**Comment by robertjpayne** [comment]
@arbitur all frameworks are dynamic, to use Swift on iOS 7.0 targets you have to embed the Swift code directly into your app target.

SnapKit is pretty straight forward since most of the API is accessed via the UIView's extension methods it's nearly identical to using it as a framework.

**Comment by arbitur** [comment]
@robertjpayne Ok I updated to 0.11.0 and now it doesn't crash.

I fond another thing but Ill make another issue about it ;)

**Comment by devxoul** [comment]
Thanks!
