### ISSUE TITLE
'SnapKit.ConcreteConstraint' does not implement methodSignatureForSelector

### ISSUE THREAD

**Issue by thomasdegry** [SnapKit/SnapKit#95]
Hey!

I get this error when running my app on some devices, not all of them and never on the simulator! Anyone knows what this might be?

```
2015-05-18 17:08:29.542 appName[2932:1136386] *** NSForwarding: warning: object 0x16d2fb50 of class 'SnapKit.ConcreteConstraint' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[SnapKit.ConcreteConstraint superview]
```

I earlier had issues with my pods not being signed or something, it threw an error in this style out of nowhere: `dyld: Library not loaded`, I fixed that but I feel the two might be related?

The test builds are being distributed over testflight and two people had no issues and two other ones had a crash that was related to the methodSignatureForSelector issue.

Anyone a clue where to start looking?

Thanks!

**Comment by robertjpayne** [comment]
@thomasdegry `dyld: Library not loaded` looks like a linker issue, how are you embedding SnapKit and what version of iOS are the users running that are getting crashes?

**Comment by thomasdegry** [comment]
@robertjpayne I fixed the dyld issue just throwing it out here in case that might affect the SnapKit one, I installed SnapKit using cocoapods and the crashes seem to be happening on iOS 8.3 so far!

**Comment by robertjpayne** [comment]
@thomasdegry right, so this is a separate issue too:

Can you:

* Confirm with me which version of SnapKit is installed?
* Are you using simulator or device or does it crash on both?
* Any chance you could provide a crash log if it's happening on device?

**Comment by thomasdegry** [comment]
@robertjpayne  Sure

- Snapkit 0.10.0
- I can't replicate the issue on the simulator, so it only happens for beta testflight users, I know about an iPhone 4s and 5, the same issue didn't happen on the 6. So maybe it's related to 32 bit devices?
- Crashlog: https://gist.github.com/thomasdegry/b4cad399a1091c399c16

**Comment by robertjpayne** [comment]
@thomasdegry please upgrade to 0.11.0 I believe it fixed some of the crashers.

**Comment by thomasdegry** [comment]
@robertjpayne seems to be fixed! Thanks man, awesome work on SnapKit! I love it.
