### ISSUE TITLE
Support iOS 7

### ISSUE THREAD

**Issue by marko1503** [SnapKit/SnapKit#96]
On website I find that Requirements iOS 7.0+ / OS X 10.9+
But in podfile you support only iOS 8

**Comment by robertjpayne** [comment]
@marko1503 as per the website on the docs page as an aside on requirements:

**While SnapKit supports iOS 7.0, frameworks are not supported for iOS 7.0 so you must manually embed the framework for non app store apps or integrate the source files directly.**

**Comment by robertjpayne** [comment]
If you need iOS 7.0 deployment:

1. Use the submodule checkout method as listed under `Embedded Framework` install instructions.
2. Either embed the SnapKit.framework or the *.swift files depending on whether you need app store deployments or not.

Hope this helps!
