### ISSUE TITLE
Please release 0.12

### ISSUE THREAD

**Issue by st3fan** [SnapKit/SnapKit#99]
Mostly interested in a tagged release because of the recent change of the deployment target to 8.0. Using 7.0 breaks integration builds for TestFlight.

**Comment by robertjpayne** [comment]
@st3fan not sure I follow? There is no v0.12.0?

**Comment by robertjpayne** [comment]
@st3fan I see you're after a version that works for iOS 7.0? Are you using it on an enterprise iOS 7.0 app where you can deploy frameworks?

**Comment by st3fan** [comment]
Hey Robert, let me explain. We are using SnapKit in Firefox for iOS. Wonderful library, thank you very much.

Firefox is for iOS 8 and up only so we include SnapKit as a framework. Now, when I include 0.11, everything builds and runs fine. But when I submit to the App Store, the application validation process fails horribly with errors like in this screenshot:

https://bug1158895.bugzilla.mozilla.org/attachment.cgi?id=8598096

This all looks pretty scary but the simple fix to make all of these go away is to change the deployment target of SnapKit to 8.0.

You already changed the deployment target to 8.0, but it happened after 0.11 and no release has been tagged yet. My request to tag a v0.12 release is just because we like to clearly pin our dependencies instead of using master.

**Comment by robertjpayne** [comment]
@st3fan Ahh! I see it was a minor change I didn't catch as queued for release sorry about that.

I'll get this out over the weekend.

**Comment by robertjpayne** [comment]
@st3fan now in trunk, let me know if this doesn't resolve your issues!
